### ISSUE TITLE
Shaky animation in WebKit based browsers during animated resize

### ISSUE THREAD

**Issue by Bunkerbewohner** [metafizzy/packery#107]
I'm experiencing very shaky animations using WebKit based browsers in the following testcase:

![testcase](https://f.cloud.github.com/assets/500529/1329135/68a06ce6-3511-11e3-8d23-7d14274155e1.jpg)

(https://www.dropbox.com/s/x9eadk875g2g73f/testcase.zip)

When clicking a tile it is via CSS resized to the full width of the parent container, the contained image to a fixed with of 800px. The resizing is animated as described in http://packery.metafizzy.co/appendix.html#animating-item-size. 

This works flawlessly in Firefox and IE, but not in Chrome or Safari. I've been looking for the problem all day but couldn't find it so far. My guess is that somehow to transitions are "battling" each other. I'm still playing around trying to fix it, but I thought maybe someone else can see the problem right away.

**Comment by desandro** [comment]
Closing this old issue :ghost:
