### ISSUE TITLE
Full width using grid-sizer breaks layout sometimes

### ISSUE THREAD

**Issue by rdourado** [metafizzy/packery#118]
I'm using a grid-sizer to makes elements always fill the whole space, but sometimes layout is breaking. How can I solve this? Thank you.

Code: http://codepen.io/rdourado/pen/xjIne
Working (screenshot): http://cl.ly/image/3K3c443R3Z0u
Not working (screenshot): http://cl.ly/image/3z0I1k2Y1D0H

**Comment by meinWebentwickler** [comment]
I don't know whether you are still working on this problem. I also encountered it and found out, that it's some kind of wrong timing. The initialisation seems to be pushed before the pkgd.min.js is fully loaded. 

I fixed it for me with a setTimeout of 400ms for the initialisation (jquery) in combination with animate.css to avoid the "hopping" and it works for me.

**Comment by rdourado** [comment]
@meinWebentwickler looks like it was fixed: #42
