### ISSUE TITLE
100% width fluid layout with fixed width gutter?

### ISSUE THREAD

**Issue by j-greig** [metafizzy/packery#140]
I'm trying to build a fluid centered 5 column layout, with fixed gutters of 60px between columns; that changes to 3 columns and 10px gutters on small screens.

Is there a way to do this? Or do I have to make everything percentage based?

Thanks :)

**Comment by z1haze** [comment]
whats the need with all this for the sizing? width: calc( ( 100% - 10px * 2 ) / 3 ); seems a little excessive. Cant you just make it to where we add margins on our grid elements and using box-sizing:border-box to contain it all?
