### ISSUE TITLE
Packery Problem on Responsive website

### ISSUE THREAD

**Issue by anteksiler** [metafizzy/packery#141]
Hi there,

We have purchased the developer license to include packery in one of our WordPress themes.

We are having a problem getting it to work flawlessly on mobile and on window resize:
http://themes.fuelthemes.net/uberstore/home-version-4/?ModPagespeed=off

If you resize your screens, the items get on top of eachother.

This is what we are doing at the moment:

```
packery: {
        selector: '.packery',
        init: function() {
            var base = this,
            container = $(base.selector);

            container.packery({
              itemSelector: '.product',
              gutter: 0
            }).end().imagesLoaded(function() {
                container.reloadItems();
                container.packery();
            });
        }
    },
```

Thanks in advance,

**Comment by AaronM503** [comment]
Im having the same issue but I am initilizing using HTML. Is there any way to fix this problem when using this code:

<div id="container" class="js-packery"
  data-packery-options='{ "itemSelector": ".item", "gutter": 10 }'>

I have this and the .JS files linked to my site
