### ISSUE TITLE
Vertical .layout possible?

### ISSUE THREAD

**Issue by BenRacicot** [metafizzy/packery#152]
Thank you for suggesting Packery, its awesome. I needed it for its Fit method. But now am wondering if on click I can .layout only the boxes underneath the clicked and enlarged item? (vertical only relayout)

This would possibly solve the slow response time when clicking? 
Please see my demo site at http://Scientifik.tk

*Update:* Packery does seem to slow down at 266 items. Also, in order to "force" the items to only rearrange vertically I made 3 seperate instances of Packery. This way the divs where narrow enough to force the items to rearrange vertically instead of all of my items rearranging horizontally.

**Comment by desandro** [comment]
Closing this request as it didn't get enough :heart:
