### ISSUE TITLE
Shuffle items except for class

### ISSUE THREAD

**Issue by vhuus** [metafizzy/packery#159]
Is there a possibility to randomize packery items on page load. Except for items with the class .ignore-shuffle?

Would be great if someone could help me out.

This is what I currently have:
http://codepen.io/vhuus/pen/xeAkw/

And the code should be something like this i guess?

<code>
function shuffle(a){

```
    var elem = document.querySelector('.item');

    var shuffled = [];
    var nonShuffled = [];

    if(classie.has( elem, 'ignore-shuffle' )) { 
        nonShuffled.push(elem);             
    } else {
        shuffled.push(elem);            
    }

    for (var i = shuffled.length - 1; i > 0; i--) {

        var j = Math.floor(Math.random() * (i + 1));
        var temp = shuffled[i];
        shuffled[i] = shuffled[j];
        shuffled[j] = temp;

    }

    // Put non shuffle items back in beginning of array
    shuffled = nonShuffled.concat(shuffled);        

    return shuffled;

}
```

**Comment by mawkor2** [comment]
another way is something like this... if you are calling methods like addItems and layoutItems directly
lodash/underscore has a shuffle built in
          var items = addImagesToOutput(json);// this will call addItems to the packery instance
          _tumblrPckry.imagesLoaded(function(){
            _tumblrPckry.packery('layoutItems', items, true);
            var pckry = _tumblrPckry.data('packery');
            var indexes = [];
            for (var idx=currentPhotoOffset - items.length;idx<currentPhotoOffset;idx+=1) { 
              indexes.push(idx);
            };

            var shuffledIndexes = _.shuffle(indexes);

            var timer = 0, counter = 20;

            for (var idx=0;idx<shuffledIndexes.length;idx+=1) {
              setTimeout(_.partial(revealItem, _tumblrPckry, pckry, shuffledIndexes[idx]), timer);
              timer += counter;
            };
          });
