### ISSUE TITLE
Submit packery.js to cdnjs.com

### ISSUE THREAD

**Issue by mikedidthis** [metafizzy/packery#16]
Firstly, super work! I have been waiting a while for this to be released.

Not an issue, but a small ask, but is there any chance to get packery.min.js submitted to: http://cdnjs.com/

Gzipped blocky goodness FTW!

Again, thank you for all the hard work!

**Comment by davefp** [comment]
FYI, it looks like someone has submitted packery here: https://cdnjs.com/libraries/packery

**Comment by davefp** [comment]
A quick look suggests that cdnjs now supports auto-updating, so a couple of the original cons are resolved: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/packery

**Comment by desandro** [comment]
Yup! I'll be linking to cdnjs in the next couple weeks.

**Comment by desandro** [comment]
[Packery docs now link to cdnjs](http://packery.metafizzy.co/#cdn)
