### ISSUE TITLE
Option to float or gravitate elements to left empty space

### ISSUE THREAD

**Issue by naoisegolden** [metafizzy/packery#165]
Is there a way to make elements that have been repositioned (for example with Draggabilly) to float, or gravitate, to the left, filling in the gaps (spaces) available?

An example would be having the bottom block of http://codepen.io/desandro/pen/Btvlz moving back to the left-most after dragging it to the right.

**Comment by aleksitappura** [comment]
+1
Are you planning to add this feature anytime soon?

**Comment by roelvermeulen** [comment]
+1 
If there could be an option to allow it to gravitate all elements up, down, left of right as one desires, that would be great so it doesn't leave gaps. I guess you could check at the end of a drag if there's an empty space above the dragged element and then just move it towards that position. Apparently the empty spaces above can be calculated already (see the "show spaces" demo at http://codepen.io/desandro/pen/shleG), so checking after a drag if there are empty spaces on top shouldn't be that hard.

**Comment by desandro** [comment]
[Packery v2 is out :tada: ](http://packery.metafizzy.co/) and has [all new drag behavior](https://twitter.com/desandro/status/694547335720751105). Dragging is way more intuitive. Dragged items will snap into position, reducing gaps. Other items shift up and down, so no more random movement. Plus, Packery adds a [drop placeholder](http://packery.metafizzy.co/draggable.html#drop-placeholder) so you can display where the item is going to land.

Time to close this one up! Thanks for your interest over the years. If you run into any issues with the new drop placeholder, please open a new issue :grin:

**Comment by chanaka1** [comment]
@desandro I still have the gap issue with v2

![image](https://user-images.githubusercontent.com/1998968/31120815-7b0d2888-a853-11e7-8f2f-ad7e39d43b3e.png)

Please see this demo https://codepen.io/cwishva/pen/YrrQPj

Even if we flick the drag item the gaps comes, calling the layout will fix this but that going to re arrange the layout 👎 .

I notice that the Left values changes even if we flick the item in the same position. Hope this helps. 

Thanks.
