### ISSUE TITLE
"appended" method not working with jQuery custom coded infinite scroll

### ISSUE THREAD

**Issue by kunalm** [metafizzy/packery#173]
I have a custom coded jquery infinite scroll as you can see below.

<pre>

// this called on document.ready when the page loads first
var $container = $('#post-container');

        // initialize Packery after all images have loaded
        $container.imagesLoaded( function() {
          $container.packery({
            // options...
            itemSelector: '.item',
            transitionDuration: '0.8s'
          });
        });

var page_count = 2; // current page no, first 15 items are already shown when the page is loaded so we need to show next page onwards on scroll
var total_pages = 3; // dynamically calculated using php
var is_page_loading = false;

$(window).scroll(function(){
            if  ($(window).scrollTop() == $(document).height() - $(window).height()){
               
               if (page_count > total_pages || is_page_loading){
                    return false;
                }else{
                    console.log('LOADING PAGE NO.: '+page_count.toString());
                    
                    is_page_loading = true;
                    $.fancybox( 'Loading posts...', {closeBtn:false, modal:true });
                    
                    $.get( "ajax_show_posts.php?pgno="+page_count.toString(), function( data ) {
                        

                        $(data).imagesLoaded( function() {
$container.append(data);
                            i$container.packery( 'appended', data );
                        });
                    });
                }

               page_count++;
            }
        }); 
</pre>

ajax_show_posts.php?pgno=X returns the next set of items as the following. Note, this is just the wrapper item I am showing here:

<pre>
&lt;div class="item w220">
&lt;/div>
</pre>

The problem is that all appended items are lapping over each other and not positioning properly. Please help!

**Comment by kdesigns** [comment]
I am having this same issue.
You 'solution' works but it's not very nice.
Why doesn't $container.packery( 'appended', elements ) work, like in the docs?
Also the page jumpt back to the top.

**Comment by kdesigns** [comment]
From another post I just fixed it by first creating a var.

If you change something like this:

```javascript
var $masonryContainer = $('#masonryContainer');

$('#loadMoreArticles').on('click', function(){
    $.get('URL', function(data){
        $masonryContainer.append(data);
        $masonryContainer.imagesLoaded(function(){
            $masonryContainer.packery( 'appended', data );
        });
    });
});
```
into this:
```javascript
var $masonryContainer = $('#masonryContainer');

$('#loadMoreArticles').on('click', function(){
    $.get('URL', function(data){
        var $data = $(data); // <<-----
        $masonryContainer.append($data); // <<----
        $masonryContainer.imagesLoaded(function(){
            $masonryContainer.packery( 'appended', $data ); // <<---
        });
    });
});
```
it works!
