### ISSUE TITLE
Infinite Scroll Integration

### ISSUE THREAD

**Issue by benjamindenboer** [metafizzy/packery#18]
Hey there,
I'm trying to make Infinite Scroll (by Paul Irish, https://github.com/paulirish/infinite-scroll) play nice with Packery, while using Packery's appended method, but to no avail. Is it already possible?

**Comment by tinanewtonart** [comment]
@desandro  http://places-2-go.tumblr.com/ is the current version...

**Comment by desandro** [comment]
[Infinite Scroll v3](https://infinite-scroll.com) has been released as a complete re-write, now as a proper Metafizzy product. Packery now can be directly integrated via the [`outlayer` option](https://infinite-scroll.com/options.html#outlayer)

``` js
// jQuery
// init Packery
var $grid = $('.grid').packery({
  // Packery options...
  itemSelector: '.grid__item', 
});

// get Packery instance
var pckry = $grid.data('packery');

// init Infinite Scroll
$grid.infiniteScroll({
  // Infinite Scroll options...
  append: '.grid__item',
  outlayer: pckry,
});
```

``` js
// with Packery & vanilla JS
// init Packery
var pckry = new Packery( '.grid', {
  // Packery options...
  itemSelector: '.grid__item', 
});

var infScroll = new InfiniteScroll( '.grid', {
  // Infinite Scroll options...
  append: '.grid__item',
  outlayer: pckry,
});
```

I'm closing this issue as resolved. Please open a new issue if you run into issues with Infinite Scroll v3 and Packery.
