### ISSUE TITLE
Resize north/west + "empty stamp" behaviour + jQueryUI touch

### ISSUE THREAD

**Issue by kosir** [metafizzy/packery#181]
Hello,
your library is addictive for me, every day I got new ideas... 
Thank you so much for your work!
I try to do some ui stuff, where I need to resize packery items in all directions. Unfortunately good resizing ux is possible only in east and south directions.
I created snippet for this: http://codepen.io/kosirm/pen/lmgsa

In packery if you try to resize item in west/north directions, item will move after resize event (except if it is the last one in a row), but I want resized item to stay where it is, and other items to move (like if you resize east/south).
I'm looking for possibility to change this behaviour at the end of resize event. Any idea?

Any input highly appreciated!
Best regards,
Milan

**Comment by desandro** [comment]
Closing this as an edge case
