### ISSUE TITLE
Nested containers

### ISSUE THREAD

**Issue by avaneste** [metafizzy/packery#185]
Hello,

First of all thanks for this great library !

I wonder if it's possible to have nested containers. Actually I managed to nest containers but the events seems to be propagated to the inner container some it gives some stange result :)

Thanks !
Arnaud.

and +1 for drag/drop between multiples containers. ;)

**Comment by kosir** [comment]
But with Drag across multiple packery containers #27 (if you plan to implement) it would be very useful pattern imho
