### ISSUE TITLE
save (and reuse) different sort order after dragging

### ISSUE THREAD

**Issue by mgrn0** [metafizzy/packery#19]
maybe I missed it, is there any way to re-use a different sort order after the user manually drag/dropped elements? (I could store the order in localstorage or save it with an ajax request, but can I apply a different sort order to a packery instance on loading the page)?

Thanks in advance, Michael

**Comment by jhawas** [comment]
how can i save layout using packery and retrieve the original layout.

**Comment by desandro** [comment]
Packery v2 has new drag behavior, which requires a new technique to save & restore drag position. Closing this issue here, picking it up in #337
