### ISSUE TITLE
Draggabilly highlight drop area

### ISSUE THREAD

**Issue by jeffjenk** [metafizzy/packery#190]
When you drag an item the interface leaves a space large enough for the element to be dropped. I wanted to place a div there temporarily to indicate that this is where the element will be dropped. All I really need is a way to get the x, y co-ordinates for where the dragged element will come to rest once released but I can't seem to figure out how to get that information.

currently I am doing something fairly similar to conventional usage: 
http://codepen.io/desandro/pen/CKbkw

and I am using a dragMove listener which is where I expect to display my div and provide it with the correct co-ordinates:

    draggie.on( 'dragMove', function(draggieInstance, event, pointer) {
        //code to display and position ghost div
    });

Any assistance would be much appreciated.

**Comment by kabalage** [comment]
+1

**Comment by Koopax** [comment]
+1

**Comment by rantav** [comment]
+1
Sortable has a `ghostClass` which is a class appended to a positioned replica or the currently dragged element. It's very nice and easy to user. 
https://github.com/RubaXa/Sortable#ghostclass-option

The also have a `chosenClass` which is the class added to the currently dragged object. 
https://github.com/RubaXa/Sortable#chosenclass-option

**Comment by coolwebs** [comment]
+1

**Comment by desandro** [comment]
[Packery v2 is out](http://packery.metafizzy.co/) :tada: and it now adds a [drop placeholder element](http://packery.metafizzy.co/draggable.html#drop-placeholder) :point_left: 

![screen shot 2016-02-16 at 5 43 51 pm](https://cloud.githubusercontent.com/assets/85566/13093742/ed6371c0-d4d4-11e5-9183-1a840be3b920.png)

If you run into any issues with the drop placeholder, please open a new issue :strawberry:
