### ISSUE TITLE
Packery and Draggabilly in Angular.js application

### ISSUE THREAD

**Issue by amergin** [metafizzy/packery#193]
I'm trying to use Packery & Draggabilly in a Angular.js application. It works mostly okay (although I sometimes run into the issue of overlapping windows, which I guess is related to [this issue](https://github.com/metafizzy/packery/issues/1)).

My problem is rearranging the divs as shown in this [Codepen](http://codepen.io/amergin/pen/cKAqv) and then adding a new div.
1. The code initially displays three divs (green, gray, lightgrey), and adds a yellow div after 4 seconds and orange div after 10 seconds.
2. Drag gray to green's position.
3. Wait until the 4s timeout is triggered and the yellow div is added.
4. After adding the yellow div, Packery switches back the green & gray div positions.

Any suggestions as to how I could avoid this problem? I realize it probably is related to how ng-repeat digest cycle operates then it sees `$scope.windowItems` content updated, but is there a way to get around this Packery-wise? 

I assume I would see same kind of problems if I were to remove an object from `$scope.windowItems`.

**Comment by INIW1112SA** [comment]
I am using packery to  have grid layout and draggability to drag and drop my cards in user prefered position  but draggability does not support  when am using react ..is there any tutorial or any kind of help where i can enable drag and drop  of cards using packery
