### ISSUE TITLE
HTML5 drag event breaks Packery when using with jQuery UI Draggable handle option

### ISSUE THREAD

**Issue by waltermacambira** [metafizzy/packery#206]
Packery's `bindUIDraggableEvents` expects a `ui` parameter. The problem is that when the event is not triggered by jQuery, no `ui` parameter is passed. This causes an attempt to access `position` of `undefined`.

Don't know if dragabilly handles it correctly. 

To reproduce the error, access http://jsfiddle.net/4tee5qav/1/
There, you should select the "content" text, and drag it. 

My temporary fix wast to add an `if (!ui) return;` on Packery's bindings.

**Comment by desandro** [comment]
Thanks so much for reporting this issue. It will be fixed in the next release.
