### ISSUE TITLE
layoutStart events

### ISSUE THREAD

**Issue by Soviut** [metafizzy/packery#207]
It would be nice if there were `layoutStart` and `fitStart` events. Ideally, the event object they pass would provide size information the way `layoutComplete` does, without having to wait for the transition to finish. This would make it possible to resize the parent container to match the size of the child elements without having to wait.

It could potentially allow for the event cancelling as well.

**Comment by desandro** [comment]
Thanks for the suggestion! I'll keep this in mind if I consider adding centering as a feature. See also #8
