### ISSUE TITLE
Licence issues

### ISSUE THREAD

**Issue by ghost** [metafizzy/packery#212]
As explained in [this ticket](https://github.com/staaky/strip/issues/2), you cannot release you code under GPL for non-commercial use only.

**Comment by desandro** [comment]
Packery v1.4.0 has shipped with revised licensing model. GPL by default. Purchasing a commercial license allows use outside of the GPL, under the Commercial License terms. Read details at: http://packery.metafizzy.co/license.html

Thanks all for your input in this matter. I'm happy to resolve this.
