### ISSUE TITLE
 Having issue on IE8 IE9 IE10 

### ISSUE THREAD

**Issue by AbhiThakare** [metafizzy/packery#226]
Hi Desandro,

I am having issue with Packery for all IE.
We have category Landing Page, in that we have 4 product in a row if we have 2 or 3 (<4) products for last row so in IE last row products are right align, for Mozilla and other browser it is Left align and our requirement is it should be left align.
 
can you please help me here?

Regards
Abhi

**Comment by desandro** [comment]
I'm sorry, but I cannot debug your live site. There's too much going on in the HTML for me to identify what could be causing this bug. If you are able to produce a **reduced test case**, I can take another look.
