### ISSUE TITLE
after ajax load(infinity scroll) packery postion is not being added to loaded items

### ISSUE THREAD

**Issue by syedazampasha** [metafizzy/packery#231]
Iam Implementing Packery JS with Infinite Scroll in Drupal 7.

Issue : Assume i set the items to be loaded onpage load is 3, styles will be added to all the 3 containers, and whenever i scroll Ajax is triggered(Infinite scroll - Drupal Api). at this time styles are not adding for rest of the containers. Any Solution..

![packery issue](https://cloud.githubusercontent.com/assets/10113003/5646816/fe8384a4-96a5-11e4-92fd-0fb86eb6c51b)

http://stackoverflow.com/questions/27819592/after-ajax-loadinfinity-scroll-packery-postion-is-not-being-added-to-loaded-it

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by syedazampasha** [comment]
Dear David,

Thanks for your reply,
I cannot Show a demo, Because the integration which I am doing is in Drupal.
Can you please let me know any other workaround can be done.


Thanks Again!!

**Comment by riscaonderwater** [comment]
remove me from the list please this is so unfair to my inbox and life you
guys are awsome but i need out of this conversation good night xo be well
make cool shit rock on just kick me out please

{eL\Le} Onderwater
