### ISSUE TITLE
Option to set dragTimeout?

### ISSUE THREAD

**Issue by DaanDD** [metafizzy/packery#232]
Hi, are there any plans to add a dragTimeout option? Right now it is hardcoded at 40ms, but it feels a bit sluggish. When I set the dragTimeout at 0 in the source code, the interface feels a lot snappier.

**Comment by desandro** [comment]
Not likely. The dragTimeout is there so it [debounce](http://www.paulirish.com/2009/throttled-smartresize-jquery-event-handler/) running `layout` every frame, thus improving performance. If you would prefer to remove the debounce, you can overwrite `itemDragMove`

``` js
Packery.prototype.itemDragMove = function( elem, x, y ) {
  var item = this.getItem( elem );
  if ( item ) {
    item.dragMove( x, y );
  }

  this.layout();
};
```
