### ISSUE TITLE
Packery Gutter out of nowhere

### ISSUE THREAD

**Issue by Ralphunter** [metafizzy/packery#233]
When using padding-bottom to maintain aspect ratio, packery creates a small gutter that disappears when you resize the window.

Codepen here. [http://codepen.io/Ralphunter/pen/bNqwEX](http://codepen.io/Ralphunter/pen/bNqwEX)

**Comment by desandro** [comment]
Hmm, this sounds like it might be related to the scroll bar. I've added `html { overflow-y: scroll; }` Does this resolve it? See http://codepen.io/desandro/pen/pveEaN

**Comment by Ralphunter** [comment]
That sorted it pal.
