### ISSUE TITLE
Item with height in % is not positioned properly

### ISSUE THREAD

**Issue by tommyJS** [metafizzy/packery#234]
Hi All,

When I try to set the height of an item like this:
`height: 50%;`

Then I receive the following problem:
![image](https://cloud.githubusercontent.com/assets/1756774/5741354/e2f49a7e-9c0a-11e4-8c48-8655e9c93c21.png)
At the top is header and at the bottom is footer. I just uploaded the content div.
When I press F12 in order to display Chrome Dev Tools, the layout looks appropriately (after reflow and rerendering):
![image](https://cloud.githubusercontent.com/assets/1756774/5741411/3ce4eac0-9c0b-11e4-86ba-cd8553cd7f90.png)
Do you know maybe what can be the root cause of not positioning properly at first?
Have you ever met this kind of issue in Packery?

Thank you for all your help.

**Comment by desandro** [comment]
Can you try adding a persistent scrollbar?

``` css
html { overflow-y: scroll }
```

I could better diagnose the problem with a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by tommyJS** [comment]
The problem was that I performed:
```
var container = document.querySelector('#container');
var myPackery = new Packery( container, {
  // options...
});
```

too early - not whole scripts have been loaded yet.
I put scripts in the `<head>` tag.
