### ISSUE TITLE
LayoutComplete not firing on 'center-out-corner' branch

### ISSUE THREAD

**Issue by dhowe** [metafizzy/packery#235]
Not sure if this a Packery issue or an issue with my code (and/or with using the center-out-corner branch), but the layoutComplete event doesn't seem to be firing. Code here: 

            var p = new Packery('#container', {
                centered : { y : 500 },
                itemSelector : '.item',
                gutter : 1
            });
            
            p.on('layoutComplete', function() { console.log('done'); } );

thanks much

**Comment by desandro** [comment]
The [`center-out-corner` branch](https://github.com/metafizzy/packery/tree/center-out-corner) is experimental. Things are likely to break. Sorry, but I won't be able to devote time to look in to this.
