### ISSUE TITLE
Spaces using Firefox

### ISSUE THREAD

**Issue by br0k3n** [metafizzy/packery#237]
Hi guys,

thanks a lot for this plugin :)
I came across a problem like using firefox. All seems to work correctly with Chrome, but with Firefox some spaces appears between the items :(

Here's the url: http://goo.gl/W1n6Tt

![spaces](https://cloud.githubusercontent.com/assets/1009655/5908912/d969b41c-a5ab-11e4-90eb-a66686e2b205.png)

Please, could you help me?

Thanks in advance

**Comment by desandro** [comment]
Hi there! Thanks for bringing this to my attention. It looks like the version of [Packery layout mode for Isotope](http://isotope.metafizzy.co/layout-modes/packery.html) didn't have some of the recent fixes for Packery v1.3.2. Can you try installing [packery-layout-mode.pkgd.min.js](https://raw.githubusercontent.com/metafizzy/isotope-packery/master/packery-mode.pkgd.min.js) v1.1.1, and seeing if this resolves the issue?

**Comment by br0k3n** [comment]
Hi!

thanks so much! It fix the issue :)

Cheers

Br0k3n
