### ISSUE TITLE
Webpack + Bower + Packery = broken

### ISSUE THREAD

**Issue by antitoxic** [metafizzy/packery#239]
I have a project with bower dependency management.  I use webpack for loading and bundling. 

However Packery doesn't play nice. It requires some non-existent files.

Right now as a workaround I have to fool Packery that `module`, `exports` and `define` are `false`. Also I have to fool it that `this` is `window`.

Using this technique:
https://github.com/webpack/docs/wiki/shimming-modules#disable-some-module-styles

Is there a chance this is improved?

**Comment by desandro** [comment]
Thanks for reporting this issue.

Packery, with its dependencies, uses the [UMD](https://github.com/umdjs/umd/blob/master/amdWebGlobal.js) spec for its exports. You shouldn't need to mock that `module`, `exports` and `define` are anything because this is handled in the UMD conditionals. It appears that [Webpack does support UMD](https://github.com/webpack/webpack/commit/b742264a4d868290a0cb8605b0cd8ae7ff7131ed), so I'm wondering where the problem lies.

Packery works Browserify. I'm curious if [Webpack for Browserify](http://webpack.github.io/docs/webpack-for-browserify-users.html) would work here.

**Comment by antitoxic** [comment]
I think the problem lies partly in bower packaging. I haven't checked how packery is distributed in npm but I'm guessing it installs dependencies like `desandro-classie` and `get-size` and they are discoverable through `require` but bower installs them in a diffent way.

Alternatively to hacking `define`, `require`... etc, one can use a special `webpack` Loader for bower components that read the `bower.json` and load the correct fule, but that hasn't been much fun because some packages (not referring to the dependencies of packery) don't define the `main` attribute correctly in `bower.json`. Some even don't define it. 

Another problem lies in `EventEmitter` by Oliver Caldwell, that is packaged the packery, which is wrapped in a function with an argument of `this` instead of `window` which requires mocking `this` to `windo`.

What the solution you would pick?

**Comment by desandro** [comment]
One question: are you trying to use a `pkgd.js` file? This file will work with an AMD loaded like RequireJS. Otherwise, I recommend using the Webpack for Browserify solution mentioned above.

**Comment by antitoxic** [comment]
I tried both the packaged and non-packged versions.

I'm using bower so npm and Browserify is out of scope for me. I was referring to: http://webpack.github.io/docs/usage-with-bower.html

Using webpack's bower loader + the having in mind modules that don't have correctly defined `main` file in `bower.json`  has the potential of making the loading very diverse. By which I mean: 

I will load packery simply by `require('packery')` because it plays nice but I will have to load other packages as `bower_components/another/module/main.js` which is having double standards a bit. 

I think we can close this issue. I was simply raising the discussion that it loading packery without a special loader causes a problem. This can be documented may be? May be I should rename the issue or open another one?

**Comment by desandro** [comment]
Ah, yes, there is a problem with packery's `main`, in that it lists all 4 files it requires, but within `packery.js`, it requires the 3 other files. I will be resolving this in a later release.

**Comment by activelogix** [comment]
Any tips to get this working with Webpack (no Bower)?  I've installed `packery`, `desandro-classie`, `get-size`, and `outlayer` with npm yet still getting errors with `require('packery')`.  All of my attempts at disabling the module styles have failed.

**Comment by desandro** [comment]
Okay, after some debugging, here's what I've found to work.

Install Packery and [imports-loaded](https://github.com/webpack/imports-loader) with npm.

``` bash
npm install packery
npm install imports-loader
```

In your [config file](http://webpack.github.io/docs/configuration.html), `webpack.config.js`, use the [`imports` loader](https://github.com/webpack/imports-loader) to disable `define` and set `window` for `packery` modules.

``` js
module.exports = {
  module: {
    loaders: [
      {
        test: /packery/,
        loader: 'imports?define=>false&this=>window'
      }
    ]
  }
};
```

You should be able to `require('packery')` no problem.

``` js
// main.js
var Packery = require('packery');

var pckry = new Packery('.container');
```

``` bash
webpack main.js bundle.js
```

**Comment by simenbrekken** [comment]
If you've switched to npm@3.x.x this issue will reappear again and since npm 3 flattens dependencies the `test: /packery/` won't work anymore.

The solution is disabling bower completely for everything node_modules:

```javascript
{
  test: /.js/,
  loader: 'imports?define=>false',
  include: /node_modules/
}
```

An optimization would be to do this manually for each of packery's dependencies but I just couldn't be bothered so feel free to comment if you've done so.

**Comment by NeXTs** [comment]
@simenbrekken You are lifesaver :+1:

**Comment by Slgoetz** [comment]
Thank you for actually putting in a clear solution.  Most threads end with _I solved it_ and no solution

**Comment by desandro** [comment]
Packery v2.0.0 is out :tada: It dependencies have resolved the need for `webpack.config.js`. You can now `require('packery')` no problem. See [Packery - Webpack](http://packery.metafizzy.co/extras.html#webpack). If you have any additional issues with Webpack and Packery, please open a new issue :strawberry:

**Comment by ibsenvalath** [comment]
@simenbrekken @desandro  Thanks, that saved my day
