### ISSUE TITLE
Strange layout in Firefox v14

### ISSUE THREAD

**Issue by ghost** [metafizzy/packery#24]
This is not an issue since it's solved but I thought I would still write about it here.

I used Packery on Chrome and Safari. Both worked fine.
I then tried it on Firefox and the layout didn't change dynamically. The items would resize accordingly to the CSS of course but their position would be set and would not respond to the media queries.

Refreshing the page resulted in the layout displaying as expected though.

The problem was solved by updating to the latest version of Firefox.

**Comment by JustMaier** [comment]
Hate to open something so old, but I seem to be having this issue with the latest FF and Packery:
[Example](http://zamplebox.com/shop/all)

**Comment by desandro** [comment]
@JustMaier If you can reproduce this in a [reduced test case](https://github.com/metafizzy/packery/blob/master/contributing.md#reduced-test-case-required), I can take a look. Please open a fresh issue.
