### ISSUE TITLE
Packery doesn't work if the container is set to 'display: none;'

### ISSUE THREAD

**Issue by melloman** [metafizzy/packery#240]
Packery will only work if the container is visible. If the container is invisible when packery is run and then made visible, it doesn't arrange the elements inside the container.

Please see fork of Packery example from the website:
http://codepen.io/anon/pen/vEpEVX

The only changes I have made is to make the container 'display: none;' and added a button to click to change the container to show.
Once the container is shown, you have to resize the browser window for the Packery rearragement to take place.
If you look at the official example here: http://codepen.io/desandro/pen/fIbHB it arranges the items on page load. The only difference between the 2 examples is that one starts with the container invisible and the other starts with the container visible.

I'm working on a project where I need to the container to be invisible and shown at moments and I can't seem to find a way around this happening.

**Comment by desandro** [comment]
The best way to resolve this is to initialize Packery instance while it is visible, then hide it. See http://codepen.io/desandro/pen/myprNm

``` js
// init packery, then hide
var $packery = $('.packery').packery({...}).hide();
// show on click
$('#showpack').click(function() {
  $('.packery').show().packery();
});
```
