### ISSUE TITLE
CSS equal columns

### ISSUE THREAD

**Issue by dt1973** [metafizzy/packery#241]
Hi!

I'm using Packery to organize the groups inside this dropdown generated with https://github.com/brianreavis/selectize.js/:

http://jsfiddle.net/z4tmqu4m/show/

I was wondering though, does anybody know how to 1) make all the borders as long as the entire dropdown, 2) remove the border on the leftmost column?

Thanks!

**Comment by desandro** [comment]
Thanks for the test case! The border issue is not quite related to Packery. Check out other solutions to [CSS equal columns](https://www.google.com/search?q=css%20equal%20columns)

**Comment by dt1973** [comment]
Thanks for the tip. I'll keep you posted.
