### ISSUE TITLE
Add a 'cancel' option to Draggabilly to limit dragging on children of the handle

### ISSUE THREAD

**Issue by sephus** [metafizzy/packery#242]
http://codepen.io/anon/pen/wByJxJ

In the above example, I don't want the menu buttons, icon, or text on the header to be draggable.

Jquery's sorting has a cancel option so i can define a class like "nodrag" and apply it to items that i don't want to be draggable.

**Comment by sephus** [comment]
I'm sure this is not the best way to handle the "issue", especially since i'm manually stripping out the "." from the cancel classname, but I got it to work by modifying the onmousedown event to the following:

        Draggabilly.prototype.onmousedown = function (event) {
            // dismiss clicks from right or middle buttons
            var button = event.button;
            if (button && (button !== 0 && button !== 1)) {
                return;
            }
            *if (event.target.classList.contains(this.options.cancel.replace(".",""))) {
                return;
            }*
            this.dragStart(event, event);
        };

**Comment by desandro** [comment]
I recommend using [Draggabilly's `handle` option](http://draggabilly.desandro.com/#handle)

> handle is useful for when you do not want all inner elements to be used for dragging, like inputs and forms. [See back handle example on CodePen.](http://codepen.io/desandro/pen/znAuH)
