### ISSUE TITLE
Setting columnWidth to a % via a class = problems with bootstrap

### ISSUE THREAD

**Issue by sephus** [metafizzy/packery#243]
http://codepen.io/anon/pen/jEzpjP

In the example above I'm using bootstrap and my main 'object' size is defined by the class col-lg-4 (33.333%).  Inside that object i have 3 smaller elements, each with the col-lg-4 class.

I'm setting up packery to handle a page full of these 'objects' so I specify the column width as '.col-lg-4' since I can't specify it as 33.3333% of the page size.  This normally works fine, however, these objects have the ability to scale in size, to say .col-lg-8 or .col-lg-12.  

If the first object on the page scales that way, the selector (code below) finds the first instance of the columnWidth class, in this case it is one of the elements inside of the object (which is much smaller than the parent).  It then calculates the size of that element and uses that size as the column width.  The result is that the _applyGridGutter calculation is thrown off and all of the 'objects' are placed at x=0 giving the appearance of a single column of objects.

            // use querySeletor if elem is string
            if (typeof elem === 'string') {
                elem = document.querySelector(elem);
            }

My current workaround is to apply a class to the child elements that use .col-lg-4 and set the columnWidth like this:
columnWidth: '.col-lg-4:not(.skipForPackery)'

Would you be willing to add support for supplying a percentage value to use for the columnWidth?

**Comment by desandro** [comment]
Have you looked into using [element sizing](http://packery.metafizzy.co/options.html#element-sizing) for percentage width?

**Comment by sephus** [comment]
D'oh! That's exactly what I needed :)
