### ISSUE TITLE
Getting error when using packery with draggabilly

### ISSUE THREAD

**Issue by fifigyuri** [metafizzy/packery#246]
I'm getting errors: `Uncaught TypeError: Cannot read property 'x' of undefined` for the newest versions of packery (1.3.2) and draggabilly (1.2.1). I see there are several dependencies for both the packages. Maybe some of their dependencies are not loaded.

This same issue happens also on draggabilly codepen examples:

http://codepen.io/desandro/pen/ciAdD
http://codepen.io/desandro/pen/aGvIq
http://codepen.io/desandro/pen/Gsexn

**Comment by desandro** [comment]
Thanks for reporting this bug!

This is likely caused by a backwards-incompatible change with Draggabilly v1.2.x. I recommend you using [Draggabilly v1.1.x](https://github.com/desandro/draggabilly/tree/v1.1.2/dist) until I can properly fix this.

**Comment by jorupp** [comment]
Ran into this before I saw this bug.  If it helps, I changed the recommended code:

    packery.bindDraggabillyEvents(draggie);

to the following, and it seems to work:

    draggie.on( 'dragStart', function() {
      packery.handleDraggabilly.dragStart(draggie);
    } );
    draggie.on( 'dragMove', function() {
      packery.handleDraggabilly.dragMove(draggie);
    } );
    draggie.on( 'dragEnd', function() {
      packery.handleDraggabilly.dragEnd(draggie);
    } );

I'll probably just downgrade Draggabilly.

**Comment by pmoelgaard** [comment]
Downgrade worked fine for me... thanks for the heads up !

**Comment by holbrookab** [comment]
Was this tested with the jquery implementation?  I'm trying the latest commit with latest packery, I get the same error
