### ISSUE TITLE
layout method didn't really work when using packery combined jqueryui draggable

### ISSUE THREAD

**Issue by ekarudianto** [metafizzy/packery#248]
so I've been using jquery plugin packery combined with jqueryui draggable for the dragging functionality.. so far it's been great, the thing is..

after I dragged the packery item the method to packery() didn't really work..

so I use these plugin in my angularjs project..

at first I was installed the packery method in the draggable it self

```
elm.draggable({
                        axis: "X",
                        containment: "#treeview",
                        distance: 10,
                        handle: '.dragging',
                        stack: '.packery-item',
                        scroll: true,
                        snap: false,
                        stop: function(event, ui) {
                            console.log("stop dragged", event, ui);
//below is the packery method
                            packeryCtrl.container.packery(packeryCtrl.packeryConfig);
                        }
                    });

```

but then the method didn't work.. after did a dragging the items didn't relayout, then I make an event binding in here

```
 packeryCtrl.container.packery("on", 'dragItemPositioned', function(packery, items) {
                        console.log("Drag item positioned", packery, items)
                        packeryCtrl.container.packery(packeryCtrl.packeryConfig);
                    });
```

but the dragItemPositioned event didn't always fire and the reason is I don't know why

then I tried it here

```
 packeryCtrl.container.packery("on", 'layoutComplete', function(packery, items) {
                        console.log("layout complete", packery, items)
                        packeryCtrl.container.packery(packeryCtrl.packeryConfig);
                    });
```

at first the method was working... then after sometime on my firebug console it gives an error like "too much recursion" and the dragging ability didn't work either... is there some workaround to do this thing ? please help me...

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
