### ISSUE TITLE
Error on layoutComplete

### ISSUE THREAD

**Issue by kevinr89** [metafizzy/packery#250]
By using the "layoutComplete" event to recursively call to Packery produces the following error: "Uncaught TypeError: Cannot read property 'once' of undefined"

    $container = $('.packery').packery({
        itemSelector: '.item',
        gutter: 20,
        isInitLayout: false
    });

    inited = 0;
    
    $container.packery( 'on', 'layoutComplete', function() {
        //Do stuff
        if (inited > 4) return;
        inited++;
        $container.packery();
    });
            
    $container.packery();

**Comment by kevinr89** [comment]
http://codepen.io/anon/pen/EaOvra

**Comment by desandro** [comment]
That's for reporting this error. Yes, your code is an infinite loop. I'm curious what you're trying to achieve?

**Comment by kevinr89** [comment]
My english is not to good. I will try to explain.
I'm checking if the component works for me, then purchase the license.
The idea is that each item fits through Packery, depending on which column the element is, resize the element. In the end may remain overlapped elements or disorderly elements, then run again Packery. The cycle is repeated until no changes in size.

http://codepen.io/anon/pen/EaOvra

The strange thing is that when using a "setTimeout", the error does not occur.

http://codepen.io/anon/pen/YPRJPV

**Comment by desandro** [comment]
This looks to be more of an issue with the implementation. Sorry, I won't be able to resolve this one.
