### ISSUE TITLE
Packery - Images show up on top of eachother

### ISSUE THREAD

**Issue by AaronM503** [metafizzy/packery#252]
Hello -
I am working on a Wordpress site with an image gallery using Packery. It seems to be working fine but only when you drag the browser small and then back to large again, upon load the images seem to show up on top of each other. I am initializing Packery using html like this:

<div id="container" class="js-packery" >
<div class="item">
<img src="/gallery-image-13.jpg"/>
</div>
<div class="item w2">
<img src="/gallery-image-12.jpg"/>
</div>
</div>

Is there code I can add to this to help fix it? I've spent hours trying to fix it with CSS but nothing will work. Thanks!

**Comment by desandro** [comment]
See http://packery.metafizzy.co/faq.html#overlapping
