### ISSUE TITLE
Empty space at start

### ISSUE THREAD

**Issue by SebastienGarciaz** [metafizzy/packery#254]
Hi !

![capture d ecran 2015-03-23 a 15 54 01](https://cloud.githubusercontent.com/assets/4662009/6782571/3c457e1e-d175-11e4-945c-c5083f261541.png)

Everything go fine when i resize, but at the start of Packery i get these strange blank space, and after several day i really don't get why.

This is my script :

var $container = $('#container_home').imagesLoaded( function() {
$container.packery({
isInitLayout: false,
columnWidth: $container.find('.grid-sizer')[0],
rowHeight: '.grid-sizer',
gutter: 0,
itemSelector: '.item'
});
});

$container.packery();

Thanks !

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
