### ISSUE TITLE
Container height too low when initializing with jQuery, but correct when doing it in vanilla JS

### ISSUE THREAD

**Issue by PanzerKunst** [metafizzy/packery#255]
Hi,

I unfortunately don't have time to create a JsFiddle to show that issue.

I am Packerizing a unordered list whose items can change from time to time. The way I've been handling these changes is to reinit the Packery on content change.

But when doing it via jQuery (`this.$list.packery({itemSelector: ".blueprint-area-panel"});`), I noticed that the container height was calculated incorrect (too low). Whereas the container height is correct when doing this initialization in vanilla JS (`new Packery(this.list, {itemSelector: ".blueprint-area-panel"});`).

The only difference in my code between the container height issue vs. non-issue, is jQuery vs. Vanilla JS.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by PanzerKunst** [comment]
I'll try to find the time and write a JsFiddle for it.
