### ISSUE TITLE
Adjust "main" in bower.json for better usability with wiredep

### ISSUE THREAD

**Issue by danieldiekmeier** [metafizzy/packery#256]
In most packages, "main" points to a file in /dist, like in jQuery, where it's `"main": "dist/jquery.js"`. In Packery, it points to four files in /js. When I put these into [Wiredep](https://github.com/taptapship/wiredep), I still don't have the full capability of Packery. It's not a jQuery plugin, for example. Would it be possible to adjust this?

**Comment by desandro** [comment]
[bower.json `main` has been a contentious point](https://github.com/bower/bower/issues/935). I feel like it's best used like `npm`'s `main`.

+ One file per filetype
+ Entry points, not distribution builds

This allows packages to be consumed by module loaders like RequireJS and Browserify.

Currently Packery has all its source files listed in main. In the next version, it will only have `packery.js`. 

I realize this breaks Wiredep's functionality. I'll have to handle that separately.
