### ISSUE TITLE
Lack of callback event for resizeContainer()

### ISSUE THREAD

**Issue by klip** [metafizzy/packery#257]
I needed to add an additional space on the bottom of the container after it's resize due to design requirement. Currently the "layoutComplete" triggered before the resize is done and any container resize operation is overridden when resizeContainer() invoked. I have added event trigger for this method in my project:
Line 2258:

Outlayer.prototype.resizeContainer = function() {
  if ( !this.options.isResizingContainer ) {
    return;
  }
  var _this = this, size = this._getContainerSize();
  if ( size ) {
    this._setContainerMeasure( size.width, true );
    this._setContainerMeasure( size.height, false );
  }
  _this.emitEvent( 'resizeComplete', [ _this, size ] );

};

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
