### ISSUE TITLE
Getting the following error:

### ISSUE THREAD

**Issue by idanb11** [metafizzy/packery#258]
`Cannot read property 'paddingRight' of undefined`
`    at a.layoutPosition (packery.pkgd.min.js:14)`
`    at a.goTo (packery.pkgd.min.js:14)`
`    at n.g._positionItem (packery.pkgd.min.js:14)`
`    at n.g._processLayoutQueue (packery.pkgd.min.js:14)`
`    at n.g._layoutItems (packery.pkgd.min.js:14)`
`    at n.g.layoutItems (packery.pkgd.min.js:14)`
`    at n.g.appended (packery.pkgd.min.js:14)`

Please help me understand and resolve the reason for this error.
Thanks,

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
