### ISSUE TITLE
Packery not aware of changing container width due to added elements

### ISSUE THREAD

**Issue by adrian-e** [metafizzy/packery#259]
Hi, I wanted to report a very small bug that I detected today.
The bug happens when the width of the elements is proportional to the page width and the packery is initiated with the page without scroll and after positioning the elements the page has scroll. Since packery takes the width before the scroll, after positioning the elements there is a horizontal scroll bar because the elements do not fit in the new width with the scroll bar.
I solved this in my code, making sure that the scroll on the page is always visible before calling packery for the first time. I just thought it would be worthwhile to share it.

Sorry I do not have time right now to create an example.

Regards !

**Comment by desandro** [comment]
Any chance you could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by adrian-e** [comment]
Here it is. If you press once "Add items" you'll see what I mean.

http://codepen.io/anon/pen/OPeRGY

**Comment by desandro** [comment]
Thanks for that. Looks like this is an issue with the scrollbar changing the width of the window. The easiest fix is to add CSS

``` css
/* force vertical scroll bar */
html { overflow-y: scroll; ]
```
