### ISSUE TITLE
Animation on first load

### ISSUE THREAD

**Issue by xabatar** [metafizzy/packery#260]
This is not an issue but I just want to know if it is possible to do it with packery.
For isotope I used the following function, by pulling the items from a container to another:
$(function(){ 
  var $alpha = $('#alpha');
  var $container = $('#beta');
  $container.isotope({
    itemSelector: '.item'
  }).isotope('insert', $alpha.find('.item')); 
});
I know that packery doesn't have the insert function, but despite any variation I can't make it to work with packery. I tried the following:
$(function(){ 
  var $alpha = $('#alpha');
  var $container = $('#beta');
  $container.packery({
    itemSelector: '.item',
    gutter: 10
  }).packery('addItems', $alpha.find('.item')); 
});	
but with no result. Is is possible to make it this way?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by xabatar** [comment]
Thanks for your response. I solved the problem.
The above shorter code doesn't work so I took it on the long way.
So my code now is:
$(function() {
	var $container = $('#alpha');
	$container.packery({
    itemSelector: '.item',
  })
	var elems = $container.packery('getItemElements')
	var $container = $('#beta');
    $container.packery({
    itemSelector: '.item',
	gutter: '.gutter-sizer',
	columnWidht: '.grid-sizer',
  })
  $container.append( elems );
  $container.imagesLoaded( function() {
  $container.packery( 'appended', elems );
 }); 
});
And it's working great.

**Comment by dt1973** [comment]
@xabatar for future reference please also see https://css-tricks.com/reduced-test-cases/.

**Comment by xabatar** [comment]
@dt1973 To set up a reduced test case takes time and since I solved my problem there is no point to set up one. Thanks anyway.

**Comment by dt1973** [comment]
@xabatar that's why I said for future reference.

It's not cool to demand help but at the same time being too lazy to set up a test case. People are not psychic - it's almost impossible for them to guess your problem. They need to actually **run your code**.

**Comment by xabatar** [comment]
@dt1973 Chill man. Consider it closed and forget it.
Be sure that if didn't solved the problem you would see a reduced test case, but like I said there is no point to make one since I solved it before was asked for one.
