### ISSUE TITLE
Always align items to the left in chronological order

### ISSUE THREAD

**Issue by rohan-deshpande** [metafizzy/packery#261]
I think perhaps this is related to https://github.com/metafizzy/packery/issues/165 but I'm actually not concerned about dragging at all. 

![packerytest](https://cloud.githubusercontent.com/assets/1079637/7335644/68365e2a-ec10-11e4-833c-10689de66e24.png)

I've attached an image to make things more obvious, basically what I want is for item 6 to appear under item 2 and then for item 7 to appear under item 3. I guess kind of forcing a "chronological" left aligned layout at all times. 

Is this possible?

PS. The code I'm using currently is really simple, just a bit of css to fix the widths and then instantiating packery, that's all. Like this;

```
$('#container').packery(
{
    itemSelector:'.card',
    gutter:0,
    percentagePosition:true
});
```
The cards just have set percentage widths with some padding. If you want me to still provide a test case, let me know.

**Comment by rohan-deshpande** [comment]
Okay, this seems to have solved my issue https://github.com/michieldewit/isotope-modulo-columns 

Is there any chance this solution might get worked into the master branch? I've seen a lot of posts all over the place asking for a solution to this issue, and I think it's fair enough because you are potentially dealing with visual representations of data where a logical order needs to be enforced for the representation to make sense. 

Just a thought. Happy to use this solution for now! The code looks like it would still work for a while unless some core stuff in isotope really changes.

**Comment by desandro** [comment]
Thanks for this feature request. I understand this could be a nice feature, but it would require completely overhauling the Packery's layout algorithm. This would be a huge change. It may be more appropriate as an option for Masonry layout.
