### ISSUE TITLE
Packery fitRows layout mode with imagesLoaded?

### ISSUE THREAD

**Issue by brianfor44** [metafizzy/packery#262]
I would like to use packery and have something similar to fitRows in isotop. I saw that David DeSandro has posted about this here: https://github.com/metafizzy/packery/issues/126

I got that to work by initializing it from the html. It works great, with the exception that sometimes the images aren't fully loaded and it messes up the layout completely. 

How do I initialize that in my js file from inside the images loaded function?

Thank you for any help!!!

**Comment by desandro** [comment]
With jQuery

``` js
var $container = $('#container').imagesLoaded( function() {
  $container.fitRows();
});
```

with vanilla JS

``` js
var containerElem = document.querySelector('#container');
imagesLoaded( containerElem, function() {
  new FitRows( containerElem )
} );
```

**Comment by brianfor44** [comment]
Hi David, here is what I have, but I get the error "p.fitRows is not a function". Which is because I have the var inside fitRowsDefinition, but if I move it outside, I get other errors. How do I get around this? Thank you for the help!

```javascript
function fitRowsDefinition(Outlayer) {

    // create an Outlayer layout class
    var FitRows = Outlayer.create('fit-rows');

    FitRows.prototype._resetLayout = function() {
        this.getSize();
        this.x = 0;
        this.y = 0;
        this.maxY = 0;
    };

    FitRows.prototype._getItemLayoutPosition = function(item) {
        item.getSize();

        // if this element cannot fit in the current row
        if (this.x !== 0 && item.size.outerWidth + this.x > this.size.innerWidth) {
            this.x = 0;
            this.y = this.maxY;
        }

        var position = {
            x: this.x,
            y: this.y
        };

        this.maxY = Math.max(this.maxY, this.y + item.size.outerHeight);
        this.x += item.size.outerWidth;

        return position;
    };

    FitRows.prototype._getContainerSize = function() {
        return {
            height: this.maxY
        };
    };

    return FitRows;

}

if (typeof define === 'function' && define.amd) {
    // AMD
    define(['outlayer/outlayer'], fitRowsDefinition);
} else {
    // browser global
    fitRowsDefinition(
        window.Outlayer
    );
}

var $packeryContainer = $('.container-collection').imagesLoaded( function() {
    $packeryContainer.fitRows();
});
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by brianfor44** [comment]
Hi David,
here is the link to my reduced test case. Thank you for having a look at this! 
http://codepen.io/brianfor44/pen/EjPxaj

**Comment by desandro** [comment]
This was a bug on my part. Changed `Outlayer.create('fit-rows')` to `Outlayer.create('fitRows')`. See demo http://codepen.io/desandro/pen/jPWWBq. Everything else works :whale:

**Comment by brianfor44** [comment]
Thank you David, that works great now.
