### ISSUE TITLE
Multiple packery containers with Tab control

### ISSUE THREAD

**Issue by hytka81** [metafizzy/packery#263]
Hi!

I have been trying to solve this issue for quite some time now. It seems that for some reason when I'm using tab control (similar thing happening with both jQuery UI tab control and Kendo UI TabStrip) and each tab item has one packery container the layout of these packery containers is not always correct (horizontal) but vertical. Then after resizing browser window or moving some item the layout gets corrected.

I'm using latest version of Packery and Draggabilly.

This is how first tab looks after loading the app (which will create tab control item and add elements to packery containers):
![image](https://cloud.githubusercontent.com/assets/1454844/7412348/891ebc80-ef4a-11e4-908a-ea24db7c667c.png)

Second tab looks like this when activated for some reason:
![image](https://cloud.githubusercontent.com/assets/1454844/7412369/c09341ea-ef4a-11e4-80ae-f5073fb22038.png)

I'm using draggabilly to enable moving of "tiles" in my Dashboard application. If I set "width" of the packery to some prefixed width and don't use "max-width" : "100%" it does not stack items vertically in any case but of course then the items don't change places if browser width is reduced.

This is how I'm initializing packery for each tab item when they are created:
```
            $rootScope.container['tab-' + tabId] = $('.packery-' + tabId).packery({
                columnWidth: 200,
                itemSelector: '.item',
                //rowHeight: 200,
                gutter: 5
            }).css({
                "background-color": "white", "max-width": "100%"
            });
```
I'm using AngularJS, so what I'm trying to do here is to create $rootScope.container['tab-someID'] for each packery instance which can then be used to add elements to that instance.

Here's how I add elements to certain container:
```
$rootScope.container['tab-' + tabId].append($items);
$rootScope.container['tab-' + tabId].packery('appended', $items);
$rootScope.container['tab-' + tabId].packery();
```
So although .packery(); in the end will layout first tab items correctly the other tabs have vertical layout... This might also happen sometimes after browser's size is changed and then some tab item is activated. Also I noticed that dragging items on first tab works great but for other tabs I get weird movement, almost seems like movement is done more than once and from different direction than where I dragged the item...

Do you have any ideas on how to fix these issues?

-Kalle

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

One solution would be to trigger [.packery()](http://packery.metafizzy.co/methods.html#layout) after a tab has been revealed.
