### ISSUE TITLE
Disabeling draggability on items swallows touch events

### ISSUE THREAD

**Issue by donzorro** [metafizzy/packery#266]
I want to toggle on/off the capability of drag and drop on items in packery. i use the function draggability.disable and i tried destroy too, which they stop the element from dragging but they seems to swallow touch events. I quickly looked at your code and i believe you should be calling the base class of draggability to disable the "disable default event" method call, but i havent tested whether that is the original cause of problems.

**Comment by donzorro** [comment]
small correction: it swallows being able to scroll on the container, click still works

**Comment by kabalage** [comment]
:+1:
As a workaround I have to destroy and recreate the draggabilly objects when toggling edit mode in our app for now.

**Comment by desandro** [comment]
Closing this issue as its been quiet for a while 👻
