### ISSUE TITLE
Building pkgd files with grunt broken

### ISSUE THREAD

**Issue by anamarialazar** [metafizzy/packery#267]
Thanks for the library. It is a huge help. 

I am not familiar with grunt so please bear with me. When I use grunt --force the file generated gives the following error in the browser: 

TypeError: PluginClass is undefined
if ( PluginClass.prototype.option )

Also in the cmd I get: Aborted due to warnings.

Any ideas?

Thank you.

**Comment by desandro** [comment]
Can you fully explain what build process you are doing?

**Comment by anamarialazar** [comment]
I run grunt --force in the cloned packery folder to regenerate the files. I am running the Gruntfile.js with the configuration that is already there. I have yet to modify anything.

**Comment by desandro** [comment]
Thanks for that. If you're trying to build packery.pkgd.js with the grunt task, you'll need to install dependencies with Bower

``` 
bower install
grunt
```

**Comment by anamarialazar** [comment]
I have all the dependencies installed with bower already.

I did some debugging and it appears that the error is in pkgd-edit package:

var definition = contents.match( definitionRE )[0];

I checked the match and is correct but it looks like during the build the match returns null.

Thank you.

**Comment by desandro** [comment]
I wasn't able to reproduce that bug, but I did catch a bug with the grunt uglify task, similar to gruntjs/grunt-contrib-uglify#315. Installing a newer version of `grunt-contrib-uglify` resolve this bug. Try pulling the most recent commit, `npm update`, and running `grunt` again.
