### ISSUE TITLE
webpack + react + packery disaster

### ISSUE THREAD

**Issue by yonatanmn** [metafizzy/packery#270]
Hi,
I've just downloaded [Packery](https://github.com/metafizzy/packery) with npm for experimenting with that.
I'm using react + webpack, and when I try to build the project it fails because in some of the npm modules there is this code : 
```
 if ( typeof define == 'function' && define.amd ) {
    // AMD
    define( [
        'classie/classie'  // ...
```

the solutions provided [here](https://github.com/arasatasaygin/is.js/issues/100) doesn't help, since I'm doing `require('packery');` from my code, and when I add this to webpack.config : 
```
module: {
  loaders: [
    { test: /packery/, loader: "imports?define=>undefined" }
  ]
}
```
The require itself stops working.
The only solution I have is changing the npm's module code (forcing `if` to be always `false`).
Any better approach?

**Comment by desandro** [comment]
Have you tried solution at https://github.com/metafizzy/packery/issues/239#issuecomment-74073208 ?

**Comment by yonatanmn** [comment]
Working, thanks. 
Forgot to install `imports-loader`
