### ISSUE TITLE
Percentage sized items don't keep there position on resizing

### ISSUE THREAD

**Issue by danielvonmitschke** [metafizzy/packery#271]
Hi, I have a "problem" with percentage sized items that don't keep their "initial" position when resizing the browser window.
Please have a look at this codepen: http://codepen.io/anon/pen/XbKybx (i simplified this from a real world example).
If you resize the browser window below 545px (width) most of the items get a new position.
I suppose this is due to some rounding "error", but is there a way to prevent this from happening?
Couldn't we introduce some kind of threshold value that takes rounding errors into account?

thanks

**Comment by desandro** [comment]
I'm not able to see this bug in Chrome. What browser are you using?

Could [`percentPosition: true`](http://packery.metafizzy.co/options.html#percentposition) be what you're looking for? http://codepen.io/desandro/pen/jPrJMY

**Comment by danielvonmitschke** [comment]
I can see it in Chrome, FF and Safari.
All on Mac.

I made a quick screencast to illustrate the "problem": 
https://dl.dropboxusercontent.com/u/8257170/screencast-packery.mov

As you can see at 00:18s the layout is changed (blue box goes down, black box goes up etc.).

From my understanding the layout should always be the same if working with percentage sized items.
But somehow (in this example) the layout (relative position of the items) is calculated different below 545px window width.

I'll also give percentPosition:true a shot.

thanks

**Comment by danielvonmitschke** [comment]
Sorry, didn't realize that you already forked my CodePen and added percentPosition.
Unfortunately that doesn't help.
The behavior is still the same.

**Comment by desandro** [comment]
Thanks for that. this is just a result of how you set up the item sizes. At 540px window width:

+ First yellow item: 37% width = 199.8px
+ Blue item: 54% width = 291.6px
+ + 50px gutter

```
199.8px + 291.6px + 50px = 541.4px
```

So the blue item cannot fit in that top row. If you want perfectly proportional gutter, then use [element sizing](http://packery.metafizzy.co/options.html#element-sizing). See demo: http://codepen.io/desandro/pen/Wvxqyz

**Comment by danielvonmitschke** [comment]
Thanks a lot. Should have thought about the gutter being a pixel value myself. :)
That of course totally makes sense now.

But now I have a feature request :)
Could you implement an option to enter the gutter as percentage value?
I know this can be achieved with element sizing, but element sizing will also require an (otherwise) redundant element.

thanks

**Comment by desandro** [comment]
Element sizing may require an extra element, but it adds the additional benefit of allowing you to control that gutter size with media queries.
