### ISSUE TITLE
full packing ensure - beautiful  images grid

### ISSUE THREAD

**Issue by azexo** [metafizzy/packery#272]
Hello,

What is the best way to make images grid layout without empty spaces automatically?
I can resize and crop images but I not want upscale it and I want to crop it as minimum as possible.
I just want to make beautiful  images grid - something similar to brick wall.

Thank you

**Comment by desandro** [comment]
There is no one way to lay out a grid of images to ensure no gaps. A simple solution is to use a a defined grid with standardized item sizes (1x1, 2x1, 1x2). But there still can be gaps and perhaps uneven bottom edges. Another method is to count the number of items and adjust their sizes before laying them out. How you do it is up to you.
