### ISSUE TITLE
Firefox Specific Issue, Moving Elements Between Packery Instances.

### ISSUE THREAD

**Issue by JesseR5095** [metafizzy/packery#275]
For a couple days, I struggled with a bug where if I moved a Packery element from instance A to instance B, then back to instance A—the leftmost element in instance B would inherit a 'top' value near to the 'height' value of the A element that was removed. This would occur after I dragged the leftmost element in instance B to the right in the row.

Then, most accidentally, I discovered this bug is exclusive to Firefox—the thing looks great in Safari and Chrome. I have since replicated the bug in Firefox versions 38, 36 and 30 on Ubuntu and Mac. My code features two Packery instances layered on top of each other, with pointerEvents disabled, and enough row spacing to create the illusion of alternating rows of two different heights.

This Codepen features a delayed layout method call on dragItemPositioned: http://codepen.io/anon/pen/VLpeNK (which is what I want).

This Codepen is identical with the delayed layout call removed: http://codepen.io/anon/pen/eNvZdO (I think it demonstrates the issue better).

I hope someone can help me! Thanks.

**Comment by desandro** [comment]
Thanks for reporting this issue. Moving items between Packery instances is not officially supported just yet. See #27. While it's awesome to see you have achieved this result, I'm not ready to debug this until the feature has been properly implemented. :watermelon:
