### ISSUE TITLE
Packery 1.4 broken with rails assets

### ISSUE THREAD

**Issue by frankie-loves-jesus** [metafizzy/packery#277]
Packery 1.3.2 works fine in Ruby on Rails (via the Bower proxy https://rails-assets.org/). 1.4, however, does not. I'm not getting any errors in development mode, but in production mode I get:

https://github.com/desandro/classie:
```
Uncaught TypeError: Cannot read property 'extend' of undefined:

// inherit EventEmitter
utils.extend( Item.prototype, EventEmitter.prototype );
```

I've reproduced the issue here:

http://code.runnable.com/VYKjSKVPv5N8foWB/packery-bug-repro

**Gemfile**
```
source "https://rails-assets.org"

gem "rails-assets-packery"
gem "rails-assets-jquery-bridget"
```

**app/assets/javascripts/application.js**
```
//= require get-style-property
//= require get-size
//= require matches-selector
//= require eventEmitter
//= require eventie
//= require doc-ready
//= require classie
//= require jquery-bridget
//= require matches-selector
//= require outlayer/item
//= require outlayer
//= require packery/rect
//= require packery/packer
//= require packery/item
//= require packery
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like you are missing [`fizzy-ui-utils/utils.js`](https://github.com/metafizzy/fizzy-ui-utils). This dependency is listed in Outlayer's bower.json and package.json.

**Comment by frankie-loves-jesus** [comment]
Superb. Onwards!
