### ISSUE TITLE
percentPosition not always considered: sometimes left position set as pixels in any case.

### ISSUE THREAD

**Issue by danielefenix** [metafizzy/packery#278]
Good morning,

First of all i would like to thank you for the amazing library.

I am currently experiencing the following issue: even if Packery is initialized with percentPosition: true sometimes the left position of the items is set as pixel in any case. Refresh after refresh the behavior changes randomly.

Version used: Packery 1.4.1

I have a grid that has to be responsive. Its width depends on its container and it is possible to place two kind of item in it: a full-width item or a half-size item. In the moment the grid container is re-sized the grid and its items should re-size accordingly. 

I am following the structure defined in http://packery.metafizzy.co/options.html#percentposition to have responsive items and currently the initialization of the Packery instance takes these parameters

```javascript
{
  itemSelector: '.fx-analysis-item',
  percentPosition: true, 
  columnWidth: '.grid-sizer',
  rowHeight: '.fx-analysis-item'
}
```

Should I keep in mind also something more to make it work?

I can provide you the link of the prototype of the web application the library is used for and where is possible to replicate the error:

http://fenix.fao.org/demo/cstat/afg/analysis.html

The page has a body with a grid in it and a lateral menu that can be closed. Elements within the grid are added dynamically. The packery grid is initialized with the configuration you find above (here the code: https://github.com/FENIX-Platform/fenix-ui-analysis/blob/feature/Feature-modules-with-plugin/js/structures/Fx-fluid-grid.js#L88)

In order to add elements please click on the button you find on top-right of the page. 
A modal will be shown, click on CONTENT > Sector and select Population. Select one of the result. Do it at least twice to have two element within the grid.

Close then the lateral menu and please check the left attribute of the packery element.

In case it is difficult to use the provided example I will provide you a simpler one.

Thank you very much

**Comment by desandro** [comment]
Thanks for reporting this issue.

> In case it is difficult to use the provided example I will provide you a simpler one.

Yes, could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues). Just the Packery instance showing the demo. It's hard to investigate what options are being set with your current setup.

**Comment by danielefenix** [comment]
Thank you @desandro i will provide it asap!
