### ISSUE TITLE
It does not work when upload content through Load More

### ISSUE THREAD

**Issue by evgenyshev** [metafizzy/packery#280]
On this page http://mysli.u8138.shiva.vps-private.net/heroes is the context to which it applies Packery, but the content is loaded on click. When upload content, the script is not used correctly.You could orient what am I doing wrong?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by evgenyshev** [comment]
I did not understand you. What do you need to provide?

**Comment by evgenyshev** [comment]
![2015-06-28 20-54-22 sli -](https://cloud.githubusercontent.com/assets/12575690/8397546/fbacb6a6-1dd7-11e5-9039-7a7d4019d537.png)
![2015-06-28 20-54-44 sli -](https://cloud.githubusercontent.com/assets/12575690/8397547/00798876-1dd8-11e5-9050-c8222a2d7204.png)

**Comment by desandro** [comment]
You have broken JS. Sorry, I won't be able to debug this for you.
