### ISSUE TITLE
Packery not respecting the order of the items.

### ISSUE THREAD

**Issue by sharathdaniel** [metafizzy/packery#282]
May be i'm missing something or don't understand the working of packery, the order of each boxes(item) is getting changed. Link to screenshot: http://imgur.com/R0neAiu
As you can see <strong>item 6</strong> is coming after <strong>item 4</strong> instead of <strong>item 5</strong>.

Can anybody shed some light on it? How can i avoid this?

**Comment by desandro** [comment]
Packery does not maintain left-to-right ordering. It's layout algorithm is based on fitting an item into the next available spot, closest to the top. You may want to use [Masonry Ordered](http://masonry-ordered.tasuki.org/) instead.

**Comment by coffeebite** [comment]
Have there been any updates on this? We'd love to use Packery but need to be able to define ordering!

**Comment by desandro** [comment]
@coffeebite See https://github.com/desandro/masonry/issues/873
