### ISSUE TITLE
x-axis inaccuracy with percentPosition + Draggabilly

### ISSUE THREAD

**Issue by NeXTs** [metafizzy/packery#284]
Hi

I've added drag-and-drop to packery with percentPosition mode and it works. But items come back with a small inaccuracy at x-axis.
y-axis works fine.

![packery](https://cloud.githubusercontent.com/assets/1753208/8556991/2014c344-2503-11e5-8e07-0bcd012ebaff.gif)

http://codepen.io/NeXTs/pen/LVdgRW
win7, chrome 43

**Comment by desandro** [comment]
Thanks for reporting this issue. This bug is likely related to metafizzy/isotope#948. I'll take a another look at this after the Outlayer fix has landed.

**Comment by desandro** [comment]
This is fixed in Packery v1.4.3. Give that demo another try.

Thanks again for reporting this bug :pear:

**Comment by NeXTs** [comment]
Hurray! This works great! Thank you so much!
