### ISSUE TITLE
How to un bindDraggabillyEvents?

### ISSUE THREAD

**Issue by NeXTs** [metafizzy/packery#286]
Hi, is it possible to **un**bindDraggabillyEvents?

I see that I could add unbind method [here](https://github.com/metafizzy/packery/blob/master/js/packery.js#L487-L491) by myself, but maybe it can be done by default?

**Comment by desandro** [comment]
Thanks for this question. Currently, there is no `unbindDraggabillyEvents` method in Packery's API, but you can add it yourself

``` js
Packery.prototype.unbindDraggabillyEvents = function( draggie ) {
  draggie.off( 'dragStart', this.handleDraggabilly.dragStart );
  draggie.off( 'dragMove', this.handleDraggabilly.dragMove );
  draggie.off( 'dragEnd', this.handleDraggabilly.dragEnd );
};
```

Then use it:

``` js
// jQuery
$container.packery( 'unbindDraggabillyEvents', draggie );
```

``` js
// vanilla JS
packery.unbindDraggabillyEvents( draggie );
```

**Comment by NeXTs** [comment]
@desandro In theory - yes, but in practice it doesn't helped. I've already tried it by myself few days ago and without luck, somehow packery continue to drag, even after this unbinding. Seems that it's manage events somewhere deeper.

But anyway, I'll double check it again in the evening and I'll let you know if it helps.

**Comment by NeXTs** [comment]
@desandro Nope, this doesn't did the trick.
I took codepen from your your [dragabilly example](http://packery.metafizzy.co/draggable.html#draggabilly), added unbindDraggabillyEvents method and call it, but tiles are still draggably.
http://codepen.io/NeXTs/pen/qdQyQb

**Comment by desandro** [comment]
Thanks for the demo. Turn out `unbindDraggabillyEvents` will work. I fixed up the demo code. See http://codepen.io/desandro/pen/VLqzgQ

To use `unbindDraggabillyEvents`, you need to pass it the same `Draggabilly` instance that it was binded with. If you're using jQuery, you can do this with `$( itemElem ).data('draggabilly')`

``` js
$container.find('.item').each( function( i, itemElem ) {
  // get Draggabilly instance
  var draggie = $( itemElem ).data('draggabilly);
  // unbind Draggabilly events
  $container.packery( 'unbindDraggabillyEvents', draggie );
});
```

I'm using Draggabilly's `enable` and `disable` methods to completely toggle dragging in this demo.

**Comment by NeXTs** [comment]
Cool! Thank you :+1:
