### ISSUE TITLE
Responsive Packery Grid

### ISSUE THREAD

**Issue by rxssmcdxwell** [metafizzy/packery#288]
Hello!

Wouldn't strictly call this an issue, but I am building a wordpress site which uses Packery to tile my posts into a lovely looking grid.  

The tiles themselves are square, with featured posts appearing double the height and width of a standard post.  All tiles are flush against one another, with no gutter.
This is a good representation of my layout: http://codepen.io/desandro/pen/BEJhd

I have this all working and its pretty fantastic, however I really like the idea of the tiles resizing and repositioning so that it is always 100% of the container.  As well as this, the tiles should never get smaller than a certain amount, say 240px wide. Once they are smaller than 240px, the grid reshuffles the tiles so that there are less tiles in each row.
The closest to this I have found is this example:  http://codepen.io/desandro/pen/VLPPdJ

But I cannot work out how to rewrite it or to adapt it for my needs. I have tried a few things but am unable to even remove the spaces between posts.  

I am looking for something that is almost exactly the same as this: http://prothemeus.com/demo/litho/ but using Packery instead.

Is this something which is possible?

Thank you 

EDIT: This is where I'm at currently : http://codepen.io/anon/pen/yNRdwd you may need to resize the window to get it to work initially.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by slorber** [comment]
@rxssmcdxwell you have to do the maths by yourself to handle responsiveness.

I've done a LESS mixin that helps doing so:

```
.withColumnNumberMixin(@columnNumber,@spacing) {
    @allHorizontalMargins: (@spacing * (@columnNumber - 1));
    @columnPercentage: 100% / @columnNumber;
    @widthInPxToRemovePerCard: @allHorizontalMargins / @columnNumber;
    > .grid-sizer {
      width: calc(~"@{columnPercentage} - @{widthInPxToRemovePerCard}");
    }
    > .card {
      width: calc(~"@{columnPercentage} - @{widthInPxToRemovePerCard}");
    }
    > .gutter-sizer {
      width: @spacing;
    }
  }
```
