### ISSUE TITLE
Sometimes images dont load right in page

### ISSUE THREAD

**Issue by thallysondias** [metafizzy/packery#290]
I'm used Packery for auto ajust images on site:
http://jsfiddle.net/tryjkvg3/

    var container = document.querySelector('#container');
    var pckry = new Packery(container, {
        // options
        itemSelector: '.lista-isotope',
        gutter: 0
    });

sometimes the images show this way:
[![enter image description here][1]][1]

the correct is:
[![enter image description here][2]][2]

But, if resize the window, images ajust and stay fine.
How force images show every time correct without  do a resize in the window

  [1]: http://i.stack.imgur.com/ZnTJ3.png
  [2]: http://i.stack.imgur.com/ahAfY.jpg

**Comment by desandro** [comment]
Try using [imagesLoaded](http://packery.metafizzy.co/appendix.html#imagesloaded)
