### ISSUE TITLE
Automatic override element to fill grid/gap?

### ISSUE THREAD

**Issue by kiettran** [metafizzy/packery#291]
Hi there,

I am currently using Packery in a big project where I load a fixed amount of elements. Some of these elements can be 1x1, 2x1 or 2x2 size, which means that the grid needs to be dynamic. So, I've read some comments that Packery has an amazing algorithm to fix this kind of grid that auto fills the grid until there are no gaps.

But for some reason, the grid leaves me some gaps while I have hoped that it automatic recognize them, autosize them and place them in the grid.

An example of what happens;
After the grid has been loaded, there is always a gap in the 3rd row (of 4 rows in total). The gap is a 1x1 size and I would like that the last element (of row 4) auto resize himself to a 1x1 fit the 3rd row.

[x][x][xx]
[x][xx][x]
[x][x][x]
[xx]

The javascript code that I am using is;

    initPackery: function(item) {
      if($(item)[0] && Packery) {        
        var packery = new Packery(item, {
          itemSelector: '.item',
          columnWidth: '.item-1x1',
          rowHeight: '.item-1x1',
          percentPosition: true
        });
        
        $('img').imagesLoaded(function() {
          resizeGrid();          
          packery.layout();
        });

        $(window).resize(function() {
          resizeGrid();
          packery.layout();
        });
        
        var resizeGrid = function() {
          $(packery.getItemElements()).each(function() {
            if($(this).hasClass('item-1x1') || $(this).hasClass('item-2x2')) {
              $(this).css('height', $(this).width() + 20);
            }
            
            if($(this).hasClass('item-2x1')) {
              $(this).css('height', ($(this).width() / 2) + 10);
            }
          });
        };
      }
    }

**Comment by desandro** [comment]
Thanks for reporting this approach.

Typically, I recommend against adding this kind of resizing item logic as it can get complex when paired with Packery's layout algorithms. If it's working for you, that's great.
