### ISSUE TITLE
Grid help: First item off by width of ".gutter-sizer"

### ISSUE THREAD

**Issue by rzzo** [metafizzy/packery#292]
First off, you are doing some amazing work, thanks!

http://codepen.io/rzzo/pen/vOMGvr

I have been trying to make Packery work with Susy, and if I stick with a static gutter (i.e. gutter: 10 ) every thing is ok. When I try to pull everything in responsively... My first item is always off by what seems to be the sizing element. I tried a bunch of things but just can't seem to get this to function. Any ideas?

**Comment by desandro** [comment]
Thanks for the test case. Looks like the problem was that the code was initializing Packery twice

``` js
var $container = $('#container').packery();
// init
$container.packery({
  gutter: $container.find('.gutter-sizer')[0],
  itemSelector: '.item'
});
```

We can fix this by initializing Packery with the options. See http://codepen.io/desandro/pen/vOqEyq

``` js
// init
var $container = $('#container').packery({
  gutter: '.gutter-sizer',
  itemSelector: '.item'
});
```

I changed `$container.find('.gutter-sizer')[0]` to `'.gutter-sizer'` to simplify the code.
