### ISSUE TITLE
Applying layout after dragging

### ISSUE THREAD

**Issue by RCDevelopment** [metafizzy/packery#293]
I'm initializing Packery without a rowHeight because I'm working with varying image sizes.  Because of this, after dragging an object, the images don't always snap into place.  To account for this, I'm trying to call layout() in the 'dragItemPositioned' callback, but the behavior is jumpy and doesn't always result in a proper reinitialization (http://jsfiddle.net/nbPp8/175/).  

If I put the layout() call in a 1 second setTimeout() I get the desired outcome which leads me to believe there's a conflict with the built-in 'dragItemPositioned' events.  

Can you please advise on the best we to apply a layout after dragging images without a set rowHeight?

Thank you

**Comment by desandro** [comment]
Thanks for reporting this issue. Packery currently does not support a feature that allows you to condense the layout to reduce gaps after dragging. We've opened an issue to track it: #165 

As for the setTimeout hack: it may work, but this is a hack. I recommend against it as it could be problematic.
