### ISSUE TITLE
Overlapping Issue using Layout Complete Packery

### ISSUE THREAD

**Issue by abdullah1908** [metafizzy/packery#295]
Hi,
I am using Packery and facing overlapping issue while click on the image. I have set the grid item width in %age.
Kindly guide me ASAP.
Thanks
Regards
Abdullah

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
