### ISSUE TITLE
Add ability to group items when dragging and rearranging

### ISSUE THREAD

**Issue by Nuru** [metafizzy/packery#296]
I have a use case where some of the items in my layout come in pairs. I keep the items together as best as the layout allows (since they all come in different sizes) by keeping them next to each other in the container's list of children. I'd like to similarly keep them together when rearranging the layout using Draggabilly. Specifically, I want them to stay next to each other and in the same order as they move up and down the list of elements. 

The key complication is that I'd like them to remain independently arranged. When I drag one of the pair, the other one comes along for the ride, but need not move at all graphically, or could move from below the dragger to above it or vice versa. 

I don't know how popular such a feature would be, so if it's not easy to add to the library, I'd understand it if you close this issue without implementing it, but I would hope you could at least provide some guidance about how I might be able to code this up for my site.

**Comment by desandro** [comment]
Thanks for this feature request. **+1 this issue** if you'd like to see this feature added.

**Comment by desandro** [comment]
[Packery v2 is out :tada: ](http://packery.metafizzy.co/) and has [all new drag behavior](https://twitter.com/desandro/status/694547335720751105). Dragging is way more intuitive. Dragged items will snap into position, reducing gaps. Other items shift up and down, so no more random movement. Plus, Packery adds a [drop placeholder](http://packery.metafizzy.co/draggable.html#drop-placeholder) so you can display where the item is going to land.

Time to close this one up! Thanks for your interest over the years. If you run into any issues with the drag behavior, please open a new issue :grin:
