### ISSUE TITLE
Rails 4 Partial, refresh grid, losing guttering in Packery grid

### ISSUE THREAD

**Issue by tomgallagher** [metafizzy/packery#297]
Hi

Packery is awesome, that's the first thing I'd like to say.

The second is, I'm using the Packery gem for Rails. I have the grid in a Rails partial, with a refresh button that delivers the updated grid using Ajax. I imagine this is very common.

On the initial page load everything works.  On the partial page refresh, all works fine with the exception of the guttering, which disappears. I have tried putting the guttering in the HTML data options. It does not help. This is being caused by the initial JS not being run when the partial is rendered, I think.

Have you come across this before? I was thinking that maybe I should re-initialise the grid with JQuery document.ready in the Rails refresh.js.erb.

Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by tomgallagher** [comment]
Hi thanks for getting back.
Almost impossible to provide a reduced test case, I'm sorry to say. Would there be any point in putting my Rails code up here?

**Comment by desandro** [comment]
Sorry, without a live demo that demonstrates the issue, there's no good way for be to debug this.

**Comment by tomgallagher** [comment]
OK just in case anyone comes and finds this later...

When using a Packery grid in a rails partial,  there are two things to remember:
1) do not use the packery container itself as the $('.object) to be the target for replacing HTML in your  page using Rails js.erb method. Put the container in a wraparound div otherwise you can end up with multiple instances of the container (and of packery).
2) make sure the js.erb re-initialises all the features of your packery grid. I could not get the grid to initialise properly on partial render just using the HTML 5 data options. I'd love to hear about ti if anyone can.
