### ISSUE TITLE
Inefficient packing in certain situations

### ISSUE THREAD

**Issue by Nuru** [metafizzy/packery#298]
I randomly came across a case where Packery fails to correctly pack the bins. Not much more I can say other than there seems to be some sort of bug in the bin packing algorithm. This is not a complicated configuration and there are only 5 items.

Reduced example at http://codepen.io/anon/pen/wKzrzJ

If you have a quick fix, I'd appreciate it, because this in production and looks bad. It also might be contributing to another issue I'm having with drag-and-drop, so I'd like to get this fixed and see if the other issue goes away.

**Comment by desandro** [comment]
Thanks for reporting this issue. I wouldn't say that packing has 'failed', but that the packing algorithm has produced gaps. Unfortunately, there is no quick fix. For best results, you may want to re-order elements in the DOM so that the largest items are before the smallest items.

**Comment by Nuru** [comment]
@desandro, I respectfully disagree. The goal of the packing algorithm is to pack the items into the smallest space possible, and it has failed that goal. If the resulting container height were the same in the Packery versus hand-packed cases, I'd agree with you that the placement of the gaps is not a failure, but in this case all the algorithm had to do was move one item (the second one) to the left by one grid unit and the rest of the items would flow naturally into a maximally efficient packing, reducing the container height by a full grid unit.

Though I'm willing to put up with Packery changing it somewhat to fill the grid, I care about the order the items are displayed in. Putting the largest elements first is not an acceptable workaround. 

I understand the full on optimal bin packing is NP-hard and you want to use a simple algorithm like first-fit, but perhaps you can add a second pass that looks to see how much white space is left in the final results and consider a second-pass cleanup of some sort. An even simpler (though less desirable) workaround would be to have a measure of trapped empty space available to the `layoutComplete` event handlers. That way people could do their own second-pass processing. 


Hopefully someone more familiar with the topic than I am can recommend a specific algorithm, either a better first-pass one or a useful second-pass one. I suggest leaving this issue open for such comments and suggestions even if you are not going to take action without such help.

Thank you.

**Comment by Nuru** [comment]
Thinking about this a little more, I see that by using a first-fit algorithm, (assuming a left-to-right, top-to-bottom layout) the order of items on the first row is completely fixed. Starting with the first item in the list everything it laid out strictly left to right in the order of the list until you get to an item that will not fit on the first row. After the first row is laid out, no other item is guaranteed a row or column position, so this first row is specially privileged. 

I think removing this first-row privilege might be a significant improvement if done correctly. I wonder how we might do that and how we could test the results.

**Comment by desandro** [comment]
Thanks for your input here. Packery's packing algorithm is designed to keep elements higher up in the DOM, higher up in the layout. This is intuitive behavior.

If you unsatisfied with the packing algorithm, you may want to try forking Packery and coding your own solution.

Closing as `wontfix`
