### ISSUE TITLE
remove method automatically removes element from DOM

### ISSUE THREAD

**Issue by desandro** [metafizzy/packery#3]
The [remove method](http://packery.metafizzy.co/methods.html#remove) actually does two things:
1. Hides the elements
2. Removes it from the DOM

Perhaps a better API would be two methods `.hide()` that just hides the element, and `.remove()` with hides and removes it.

If you would like to see something like this, please +1 and explain your use case.

**Comment by bryceadams** [comment]
@desandro still interested in adding a friendlier method or just sticking to hide()? :smile:

**Comment by desandro** [comment]
@bryceadams Still interested. I've done some work on it recently, see https://github.com/metafizzy/outlayer/commit/d89057ada3ec022fef4b734b93e289c409a3500e

**Comment by pliablepixels** [comment]
@desandro - how does one use the outer layer API? I am using packery.pkgd.js.
