### ISSUE TITLE
fit method documentation

### ISSUE THREAD

**Issue by rachy** [metafizzy/packery#300]
This is more so in regards to the fit method documentation and the codepen demo that exists. It was driving me crazy as to why it didn't work when there was content inside the items and that content was clicked on. 

using ('fit', event.currentTarget, 0, 0) would be more appropriate for the documentation since currentTarget allows for the children to be clicked on and still have the method work. So simple, yet easy to miss and drive a person a little crazy till the aha moment .

**Comment by desandro** [comment]
Thanks for this feedback! Changed in docs and in CodePens.
