### ISSUE TITLE
Block resizing and behavior of inner blocks

### ISSUE THREAD

**Issue by spirit-infernal** [metafizzy/packery#301]
For some unknown reasons, current code is giving two bugs: gaps between blocks and requirement for four time clicking. Is it a possible issues with code or bugs in packery?
codepen reduced test is here: http://codepen.io/spirit-infernal/full/XmjQXM/

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm sure I understand what the bugs are. Everything appears to be behaving as expected. Can you provide more detail on the issues?

**Comment by spirit-infernal** [comment]
which details need to clarify?
all code are on codepen example. also further test with adding :hover effect on first one block is solved problem. animation is doing correct block need to have one click to expand and animate, one click for collapse and replace using masonry. Is it strange, or it is a normal behaviour of masonry, ehich probably didn't fit for such responses?

**Comment by spirit-infernal** [comment]
one more strange thing. If all blocks have hovering part, they are animating proper - need exactly one click on block to expand, one click for collapse, but collapsing click is need to be done on hover part of block. problem with gap on right bottom corner still alive. updated codepen on http://codepen.io/spirit-infernal/full/QjpBvO/

**Comment by desandro** [comment]
Take a look at the Animated item resizing demo: http://packery.metafizzy.co/appendix.html#animating-item-size There's transition end JS you need to add. `reloadItems` is not necessary.
