### ISSUE TITLE
Best way with Ember.

### ISSUE THREAD

**Issue by ginolon** [metafizzy/packery#303]
Looking at this questions:

- http://stackoverflow.com/questions/32823929/ember-cli-masonry-isotope-packery-how-to-use

and

- http://stackoverflow.com/questions/33083807/ember-ember-cli-masonry-isotope-packery-how-to-use

I want to know the right way to use Packery and Isotope with Ember 2 (ember-cli).

The component's way is ok? Is it right?

Why I'm getting the same error?

```
Uncaught TypeError: this.$ is not a function
```

**Comment by desandro** [comment]
Sorry, I don't have expertise with Ember.

Please chime in if you have any Ember knowledge!
