### ISSUE TITLE
Spacing between item rows not correct just after Packery instance creation

### ISSUE THREAD

**Issue by slorber** [metafizzy/packery#305]
```
var PackeryOptions = {
    itemSelector: '.item',
    columnWidth: ".grid-sizer",
    gutter: ".gutter-sizer",
    percentPosition: true,
    transitionDuration: "0s"
};

docReady( function() {
  var container = document.querySelector('.packery-container');
  var pckry = new Packery(container,PackeryOptions);
  
    
  setTimeout(function() {
      pckry.layout();
  },2000);

});
```

On certain CSS/HTML cases, the delayed HTML layout (2s later) will lead to different .item positions.

Notice my box items have a % based width, and a height that is proportional to their width, using the trick described here: http://stackoverflow.com/a/10441480/82609
I could not reproduce in my real world app by using fixed heights.

I could not even reproduce in a JsFiddle sandbox, but to give you an idea of my env, it looks like this: http://jsfiddle.net/cAZfE/17/

It almost works perfectly fine, but on the initial layout in my case, it is like the gutter between item rows (no problem with columns) is slightly bigger initially, and gets fixed after the 2nd layout. I mean if I use a gutter of 15px, it seems to be like 17px initially, and then it is put back to 15px after the 2nd layout.

For example I use gutter with `width: 15px;`

After Packery instance creation, I get these heights and positions:
All items have height 177.547px;
The first card of the 1st row is: top: 0
The first card of the 2nd row is: top: 196px;
So the spacing is 18.45px

After 2nd layout, I get these heights and positions:
The first card of the 1st row is: top: 0 and height: 177.547px;
The first card of the 2nd row is: top: 192px;
So the spacing is 14.45px

So in first layout, the spacing between rows is a bit bigger. Even after 2nd layout, the spacing is not exactly 15px (gutter size): is this expected?

It does not seem to be a problem of the browser computing properties asynchronously, because the following also produces a better spacing between rows:

```javascript
var container = document.querySelector('.packery-container');
  var pckry = new Packery(container,PackeryOptions);
  pckry.layout();
```

It affects at least Chrome and Firefox with Packery 1.4.1 and Packery 1.4.3 (only tested those).
Maybe it's something wrong in my env but I could not find out. Just wanted to make you aware of this problem.

**Comment by NeXTs** [comment]
You could handle spaces between items without gutter property by using simple paddings.
http://jsfiddle.net/hz8oumhb/

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
