### ISSUE TITLE
Packery item, content size changes, item remains the same

### ISSUE THREAD

**Issue by tomgallagher** [metafizzy/packery#306]
Hi 

Thanks very much for Packery, it's really working well.

One question:

I have content in the grid items, photos and tables, which can change in size, sometimes unpredictably.

When this happens the content overflows the item edges. The dimensions and sort order of the items are saved in the database. Can you point me in the general direction of where I can start to address this issue? I've had a look through all the docs and it's not immediately obvious. An 'autofit' option would clearly be totally awesome but any kind of ability to measure the size of content and control the dimensions of items before loading would also be good.

Cheers!

Tom

**Comment by desandro** [comment]
Hi Tom, Thanks for reporting this issue. I'm  having trouble understanding your request. Any chance you could put together a **reduced test case** for us to look at? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

Have you looked at using the [`fit` method](http://packery.metafizzy.co/methods.html#fit)?

**Comment by tomgallagher** [comment]
Hi David

I haven't tried forking on code pen before. I've done it and this is the address:
http://codepen.io/anon/pen/avjeJg

Alternatively there's a gist on github:
https://gist.github.com/tomgallagher/d3030cd3623d6327e4ad

Let me know if either of those work

The problem is a very simple one really. If you have html content inside a packery item with fixed dimensions, how can you handle unexpected changes in the size of the HTML content?

Thanks very much for getting back

Tom

**Comment by tomgallagher** [comment]
Sorry I think this is the CodePen fork address:
http://codepen.io/tomgallagher/pen/Yyjmvp

Thanks

**Comment by desandro** [comment]
How you fit content inside item elements is up to you. If an item element size changes, you can either trigger [`.packery()`](http://packery.metafizzy.co/methods.html#layout) to layout all items, you  [`.packery('fit', elem)`](http://packery.metafizzy.co/methods.html#fit) to keep the position of that item.
