### ISSUE TITLE
Limit tile reorder to tiles after the destination position

### ISSUE THREAD

**Issue by Sovenger** [metafizzy/packery#307]
If I drag a tile in the middle of a large collection of tiles, they reorder tiles before and after the one I moved rather than the expected ones after the position I am dragging to.

Is there a way to configure Packery so that dragging an item on a row only reorders items after the destination position and not before? More of a "cascade" reorder maybe. It could be that the bounding box for detecting which "row" I am dragging into is so sensitive that it thinks a minor few pixels into the upper row means I want to reorder from that point.

Here is a codepen showing what I mean: http://codepen.io/Sovenger/pen/JYaENZ

Dragging the blue tile between the red tiles will usually trigger a reorder of all tiles before and after the red tiles. If you keep your mouse really still as you move horizontally, you can make it reorder only the tiles after the destination position.

**Comment by desandro** [comment]
Thanks for this feature request. This sounds similar to #55. Closing here
