### ISSUE TITLE
Bootstrap .h2 class conflicting with example CSS

### ISSUE THREAD

**Issue by bdm4** [metafizzy/packery#309]
This is pretty much a non issue, but bootstrap has classes defined for .h2. This will add a margin to the top and bottoms of things. It was a little confusing why the demo was adding weird spacing.

**Comment by desandro** [comment]
Thanks for the heads up!

**Comment by desandro** [comment]
[Packery doc demos](http://codepen.io/desandro/pens/tags/?grid_type=list&selected_tag=packery-docs) now use `.grid-item--height2`.

Thanks again for reporting this issue! :pineapple:
