### ISSUE TITLE
Rectangular hierarchical objects on the concentric

### ISSUE THREAD

**Issue by pzelchenko** [metafizzy/packery#311]
Looking for a package that can work the following requirement. See attached image.

Essentially a hierarchical rectangle-packing scheme on a concentric, based on hierarchical weighting. Nodes will be multiply linked to other nodes with weights attached to each link. How close is packery to providing this type of functionality?

![shouquan](https://cloud.githubusercontent.com/assets/7409590/11021847/4662df96-8614-11e5-9704-5d729a56f4ff.png)

**Comment by desandro** [comment]
Thanks for this feature request. Take a look at #62 . Closing here as a duplicate.
