### ISSUE TITLE
Adding unbiased sorting

### ISSUE THREAD

**Issue by lopeax** [metafizzy/packery#312]
Heya! Loving using packery and have been using it for a while. However, one thing that I've been looking for is an unbiased shuffling bit to add. I've used this sorting function as an extension of the array prototype which is a simple implementation of the fisher-yates shuffle

```javascript
Array.prototype.shuffle = function(){
    var m = this.length, t, i;
    while (m) {
        i = Math.floor(Math.random() * m--);
        t = this[m];
        this[m] = this[i];
        this[i] = t;
    }
    return this;
}
```

I was wondering if you would be able to implement this into packery? I imagine that the code would look something akin to

```javascript
Packery.prototype.shuffle = function(){
    var m = this.items.length, t, i;
    while (m) {
        i = Math.floor(Math.random() * m--);
        t = this.items[m];
        this.items[m] = this.items[i];
        this.items[i] = t;
    }
    this.layout();
}
```

**Comment by desandro** [comment]
Yes, that'll work! See demo http://codepen.io/desandro/pen/zvbrrK

**Comment by lopeax** [comment]
Awesome! Found it especially useful in a card matching game that I made :) Would it be able to be put into packery in the future?

**Comment by desandro** [comment]
I appreciate the work here, but I don't feel its necessary to be added as a feature, when it can easily be added in your own code.

**Comment by lopeax** [comment]
Ah, ok then, that's a shame
