### ISSUE TITLE
Programmatically change order of items in layout

### ISSUE THREAD

**Issue by Nuru** [metafizzy/packery#313]
I've read #19 and the included examples carefully, but I still cannot get my (slightly different) use case to work in Packery 1.4.3 using jQuery. In #19 the order of the items is being set before Packery does its first layout. I want to change the order *after* items are already on the screen. 

I layout a container using `$container.packery({ itemSelector: '.tile', columnWidth: 80, columnHeight: 80})` and bind `Draggabilly`. I let the user drag-and-drop to rearrange the items. However, I want to enforce that some items are in certain ordinal (not graphical) positions, so I reorder the items in `$container.data('packery').items`. (Actually, I create a new array with the items in the new order and assign that to `items`.) 

Nothing I've tried after that will get the container to layout correctly. I cannot `destroy` or `remove` and recreate Packery because I want to leave the original DOM in place. (I'm showing a preview until the new layout is ready to be saved and want to be able to revert.) `$container.packery()` and `$container.data('packery').layout()` both fail to update the layout at all, while `$container.packery('layoutItems', $container.data('packery').items, false)` appears to layout the items below their previous space. 

I would like to have the ability to reset the layout after reordering the items in `pckry.items`. If this is currently possible, please tell me how. If it is not possible, then please consider this a feature request.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**, perhaps forking the demos in https://github.com/metafizzy/packery/issues/19#issuecomment-16834246 ? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by Nuru** [comment]
See the example at http://codepen.io/anon/pen/epXrRZ

**Comment by desandro** [comment]
Thanks for the demo. But I'm still having trouble understanding what you are trying to achieve. 

After dragging an item, Packery will automatically re-sort the order of `pckry.items`. You do not need to add extra logic to do this.

**Comment by Nuru** [comment]
After Packery re-orders the items, I want to change the order to enforce that some items ("B" in the test case) remain at certain indexes. You can see the desired outcome if you follow the instructions on the test case, including clicking "Layout Again". The desired behavior is to achieve that result without needing a second, asynchronous call to `pckry.layout`.

**Comment by desandro** [comment]
Sorry, but Packery is not well suited for dragging and then re-sorting items. I won't be able to resolve this request. If you do make any progress, feel free to document it on this issue.

**Comment by Nuru** [comment]
@desandro I don't particularly want to re-sort the items. Conceptually what I'm asking for is similar to "stamp", it is just that instead of fixing an item in space I want to fix it in ordinal position in the list of items. I'm only re-sorting the items because the feature I want is not implemented. How do you feel about adding that feature?

**Comment by c01gat3** [comment]
@Nuru did you manage to find any solution to this? I have a similar use case: I want to have an item always be located in the last position of the grid. Each item is a dashboard widget, and I want a final one to be an "add another widget" link. 
http://stackoverflow.com/questions/40876073/force-item-to-always-be-in-last-position-using-packery

**Comment by desandro** [comment]
@c01gat3 Look at using [Isotope with sorting](http://isotope.metafizzy.co/sorting.html). It has a packery layout mode

**Comment by jarvelov** [comment]
Just wanted to share what I came up with when I wanted to programmatically reorder the items in a Packery layout.

I was having trouble dragging and dropping items with [draggabilly](http://draggabilly.desandro.com) and noticed that it was a lot easier to drag and drop when there was an item in the column above where I wanted to drop the item. I figured that if I had an item permanently at the top of each column, then the problems with the drag and drop would be gone.

At first I tried setting my static items `stamped` at the top but that didn't work unfortunately. It seems like any stamped items are taken out of the equation altogether when an item is being dragged around, and so my static items were of little help when they were stamped.

Anyway, I came up with this solution. This code inside `repositionStatics` is built after my needs, but the code is reusable with small changes. Basically, get the items in packery, loop over them and place them where you want them. If you are placing an item statically like I am then you know what boundaries the other items in Packery are not allowed to intersect, and if they are, you have to move them.

### Before you dive into the code
**Note that it's untested and is meant to be taken as a concept of how to approach this topic**

This is a small example of what I did to achieve something which works well enough for me. Please feel free to modify it and put it up on jsbin, codepen or wherever.

```html
<div class="grid">
  <div class="grid-item static">Static</div>
  <div class="grid-item static">Static</div>
  <div class="grid-item static">Static</div>
  <div class="grid-item static">Static</div>
  <div class="grid-item">1</div>
  <div class="grid-item">2</div>
  <div class="grid-item">3</div>
  <div class="grid-item">4</div>
</div>
```

```js
const element = document.querySelector('.grid')
const options = {}
// Initialize Packery
const grid = new Packery(element, options)

// Hook up draggabilly
const draggies = grid.getItemElements().map(element => new Draggabilly(element))

// Every time an item is dragged or the layout is updated we want to do some repositioning
grid.on('dragItemPositioned', (updatedItem) => repositionStatics(grid, [updatedItem))
grid.on('layoutComplete', (updatedItems) => repositionStatics(grid, updatedItems))

function repositionStatics (grid, items) {
  // Get items in packery that should be static
  const items = grid.items .filter(item => item.element.classList.contains('static'))

  // Loop over them and set their position
  items.forEach((placeholder, index) => {
    // Put the statics at the top of each column
    const x = ((index * placeholder.rect.width))
    placeholder.goTo(x, 0)
  })

  // Check if we received any items whose positions we have to modify
  if (updatedItems && updatedItems.length > 0) {
    updatedItems.forEach(item => {
      // We're not interested in any item with the static class
      const isStatic = item.element.classList.contains('static')
      if (!isStatic && item.position.y === 0) {
        // Set the new vertical position if the item is not static
        // and is currently at the top
        const y = item.position.y + (item.layout.gutter + 1)
        item.goTo(item.position.x, y)
      }
    })
  }

  // Tell Packery to update the layout with the changes we've made
  grid.sortItemsByPosition()
}
```
