### ISSUE TITLE
Packery fit + Layoutcomplete = recursive calls

### ISSUE THREAD

**Issue by JustasKuizinas** [metafizzy/packery#314]
I want my answer block always stay after  active question block on resize so I have this function

```
app.grid.on("layoutComplete", function ( event, laidOutItems) { positionDUKanswer(); });

function positionDUKanswer(){
		if($(".duk-block").length === 0){
			return;
		}else if($(".duk-block.is-active").length === 0){
			return;
		}


		var $self = $(".duk-block.is-active");
		var offset = ($self.offset().top - $self.closest(".grids").offset().top) + $self.outerHeight();
		app.grid.packery( 'fit', $self.next()[0], 0, offset);
		

}
```

But when "layoutComplete" is fired it goes into recursive hole. Is there a way to fire "fit" method without firing "layoutComplete" event?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
