### ISSUE TITLE
Packery broken inside jQuery tabs 

### ISSUE THREAD

**Issue by lionhurt** [metafizzy/packery#317]
packary broken inside jQuery tabs i here is my code : 

<code>
var c = $('.container');
          c.packery({
              itemSelector: ".column",
              gutter: 10,
          });
</code>

and here the result inside the second tab :
http://prntscr.com/98z0xv

sure it works normally in first tab 

Update : 

here is the case study : http://codepen.io/anon/pen/BoXbRB

**Comment by desandro** [comment]
When using Packery inside tabs, you'll need to trigger layout when a tab has been shown. Packery needs its item elements to be visible so it can measure them for layout.

With your example, I was able to add a click event handler to trigger layout. See demo http://codepen.io/desandro/pen/ea845c24a2eefd15046976d19f10bc19/?editors=001

``` js
  $tabs.on( "click", "a", function() {
      // disable transition
      c.packery( 'option', { transitionDuration: 0 });
      c.packery('layout');
      // re-enable transition
      c.packery( 'option', { transitionDuration: '0.4s' });
  });
```

**Comment by lionhurt** [comment]
Thank you so much you are a life saver :+1:
