### ISSUE TITLE
Sorting axis without rowHeight?

### ISSUE THREAD

**Issue by JvanderHeide** [metafizzy/packery#319]
I'm using [Draggabilly](draggabilly.desandro.com/) with Packery and I am trying to create a grid allowing the user to sort items in a container.

The items however have variable heights (yes,Masonry), the widths will always be percentages and multiples of the smallest available block (thus allowing us to base the columns of off that).

http://codepen.io/JvanderHeide/pen/qbZExr

Dragging actually works pretty fine except for one situation; 
- Drag an item to the left of another (ie. 3rd item in front of the 1st)
- Drag the 3rd item up to the left top corner where the 1st block was (above the top border so to speak)
- The 3rd item now takes the 1st item's place and all is well
- _Now reload the page and try again;_ __However__;
- This time drag the 3rd item left of the 1st but let go of the item a little below the top border of the items
- When not calling Packery again (see ``line 20``+) the item stays put
- I do however call Packery and expect the item to gravitate upwards and fill the gap there
- It does however gravitate to the right instead of to the nearest empty space where space is already reserved for it. 

Does anyone have any idea how to replicate the behaviour before the reload and thus making it behave like I expected?

**Comment by desandro** [comment]
Hello! Thank you for this feedback. I agree, the dragging and layout behavior with Packery can be un-intuitive. I'm currently experimenting with a refined dragging-layout algorithm that addresses this issue. I hope to release this new algorithm in 2016.

**Comment by JvanderHeide** [comment]
Thank you for your reply. That is excellent, another reason to look forward to 2016!

Happy holidays, thank you for the great things you create.

**Comment by coolwebs** [comment]
Any possible update on this issue? I'm just trying out the the draggabilly lib on Packery and having strange results. If "tile" is correctly dragged over the item to replace it works, but has weird and unpredictable (and buggy) events when only partially dragged over the tile. Here is a JS Fiddle of what I'm talking about -  https://jsfiddle.net/rpf0fyem/2/. I'm hoping I can set the behaviour to 'snap' into either starting position or make it into the new position if its dragged over far enough. The examples given on http://packery.metafizzy.co/draggable.html work well of course but if items are dragged small increments, it leaves white space and grid doesn't reflow.

**Comment by coolwebs** [comment]
+1 to this issue. Any possible update on this issue? I'm just trying out the draggabilly lib on Packery and having strange results also. I'm hoping I can set the behaviour to 'snap' into either starting position or make it into the new position if its dragged over far enough. I end up with the draggable operation initiated by the user fighting (or coming into conflict) with the packery sorting algorithm. Simply put, sometimes when i drag something to go somewhere, it does not go there and the whole screen layout is done by packery.

**Comment by desandro** [comment]
@coolwebs Packery v2 will be released next week with new dragging behavior

> Drag layouts more intuitive, no longer feel random, snap to fitted drop position 

[See preview video on Twitter](https://twitter.com/desandro/status/694547335720751105)

**Comment by JvanderHeide** [comment]
That looks great, can't wait to give it a go!
Does anyone have a DeLorean I can borrow?

**Comment by desandro** [comment]
[Packery v2 is now out](http://packery.metafizzy.co/) with all new drag behavior. Drag items now drop into fitted position.

**Comment by coolwebs** [comment]
Woot woot! Yes I have been using it since you released it on your website approx 1 week ago. It works so much better than before. THANK YOU David.
