### ISSUE TITLE
SVG Support?

### ISSUE THREAD

**Issue by villanus** [metafizzy/packery#320]
My goal is to "sprite" or "nest" various SVG graphics to take best use of space.  
SVG does not work with CSS absolute positions and rather uses CSS translate to move objects around. 

Question:
Will Packery, Isotope or even Masonry be adaptable for this type of work?

Thanks

**Comment by desandro** [comment]
Sorry, no, Packery, Isotope or Masonry will not work with nodes in SVG.

**Comment by villanus** [comment]
Thank you for the clarifications.  
Will it work with individual SVGs ?

**Comment by desandro** [comment]
Yes, you can treat whole SVG elements just like regular elements.

**Comment by villanus** [comment]
I know this is an old question but can 90 degree rotation be supported?  
The use case is arranging different SVG files for printing

**Comment by desandro** [comment]
> can 90 degree rotation be supported

Sorry, no.

**Comment by villanus** [comment]
Thanks
