### ISSUE TITLE
Resize handle in gutter-sizer

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [metafizzy/packery#323]
When making the packery item elements resizable (as showed in an example), the _gutter-sizer_ gets a resize handle too. I solved the issue by removing the gutter-sizer from the elements in `$itemElems` by  using a _lodash_ function. Is there a better method to do that?

```javascript
  var $itemElems = $($container.packery('getItemElements') );
  _.remove($itemElems, function(el) {
 		return ~el.className.indexOf('gutter-sizer');
	});
  $itemElems.draggable().resizable();
```

**Comment by desandro** [comment]
Thanks for reporting this issue. I recommend setting [`itemSelector`](http://packery.metafizzy.co/options.html#itemselector).

> Setting itemSelector is always recommended. itemSelector is useful to exclude sizing elements.
