### ISSUE TITLE
layoutComplete event firing to early? is there another init-event?

### ISSUE THREAD

**Issue by danielvonmitschke** [metafizzy/packery#324]
Hi, I try to "fit" an element after packery has been layed out (on page load).
I thought I could just call packery("fit") on the layoutComplete event, but it seems this is too early:
"cannot call methods on packery prior to initialization; attempted to call 'fit'"

Is there another "init"-event to use when packery is fully initialized (same question goes for flickity as I had a similar problem there as well)?

Here is a codepen to demonstrate the issue:
http://codepen.io/anon/pen/XXaxKa

thank you,

daniel

**Comment by kokarn** [comment]
You haven't initiated packery from what I can see?

IIRC $('.container').packery() doesn't init but layout.

http://packery.metafizzy.co/methods.html#layout

**Comment by danielvonmitschke** [comment]
Of course calling .packery() does "init" packery.
How else would you do it?

**Comment by desandro** [comment]
Initial layout does not have a transition duration, so you can immediately use `fit`. See demo http://codepen.io/desandro/pen/86b435eea3a27b04daa9f957d5e16b3a/

``` js
var $container = $(".packery").packery();
var firstItem = $container.find(".item").first();
firstItem.addClass("gigante");
$container.packery("fit", firstItem.get(0));
```

**Comment by danielvonmitschke** [comment]
Sometimes it's so easy. :)
thanks
