### ISSUE TITLE
How to set Packery scroll position

### ISSUE THREAD

**Issue by JayWIlsonJr** [metafizzy/packery#325]
After packery expands a selection, I'd like to scroll the expanded section to the top of the window. After the expanded section is shrunk back down, I'd like to return to the initial scroll position. My reduced test case is here: 

http://codepen.io/JayWIlsonJr/pen/wMPMaP

The logic in my mind is something like this: 
1. Set current scroll position.
2. Scroll document to the top of the window offset by the height of the navbar on my site. 
3. After element is finished shrinking, return document to the original scroll position. (or even as the element is shrinking)

When I tried to use jQuerys scrollTop method on one of the div's it kept returning 0 for a element that was midway down the page. So any help that can provide would be awesome. 

Thank you for your time, and assistance.

**Comment by desandro** [comment]
Try using [`layoutComplete` event](http://packery.metafizzy.co/events.html#layoutcomplete)

``` js
$grid.on( 'layoutComplete', function() {
  // set scroll position
});
```

**Comment by JayWIlsonJr** [comment]
Fantastic! Thank you very much, that worked like a charm.
