### ISSUE TITLE
how to make this dynamic?

### ISSUE THREAD

**Issue by kickthemooon** [metafizzy/packery#326]
So I have galleries in my back-end and I want to display the gallery images on the front the meticulous way as packery is calling it.

I really have no idea how to approach this.

I mean I need to pass the images the user uploads to a gallery in the back-end to the front-end
that is no problem, I am have the images on my front already but now I need the images to get ordered in this way:

http://codepen.io/desandro/pen/tonpx

do I have to dynamically check the image and then apply w2 or w4 and such css classes to the item so that they get ordered like this?

So any ideas suggestions on how to display a gallery like this?

Thanks a lot.

**Comment by desandro** [comment]
> do I have to dynamically check the image and then apply w2 or w4 and such css classes to the item so that they get ordered like this?

Yes. The 2x1, 1x2, and 2x2 CSS classes all need to be added in your HTML. Packery does not control this. I would start by using a grid with all 1x1 items. Then add logic to add the larger CSS classes. This could be based on measuring the image's size, or using other data you might have – featured items, popular items.
