### ISSUE TITLE
Best way to shrink a expanded element

### ISSUE THREAD

**Issue by JayWIlsonJr** [metafizzy/packery#327]
When a element is in the expanded state I have a close icon in the corner, when that icon is clicked I use jQuery to remove the `is-expanded` class and then run the `.packery()` method to reflow the layout. 

Is this the correct way to force a element to shrink, or is there another way to control the shrinking? 

I ask because I am running into a positioning issue after the expanded element is shrunk down, and my guess is that it has something to do with the way I am forcing the element to shrink. Any help you provide this beginner is greatly appreciated.

Thanks!

**Comment by desandro** [comment]
> Is this the correct way to force a element to shrink

Yes, I recommend toggling a class to expand or shrink an element.

>  I am running into a positioning issue after the expanded element is shrunk down

You can use [`fit` method](http://packery.metafizzy.co/methods.html#fit) to fit a shrunken element in its current position

**Comment by JayWIlsonJr** [comment]
Thanks!
