### ISSUE TITLE
How to keep track of packery items position and size information

### ISSUE THREAD

**Issue by geohuz** [metafizzy/packery#328]
I use packery with jquery ui draggable and resizable, items are added into packery container dynamically(button click) and can be resized repositioned, now the interaction works fine. But I'm facing the problem of recording the position(left, top) and size(width, height) information for each item. Could somebody tell me on which event handler I can write the logic?

**Comment by desandro** [comment]
I would recommend listening for [layoutComplete](http://packery.metafizzy.co/events.html#layoutcomplete) and [dragItemPositioned](http://packery.metafizzy.co/events.html#dragitempositioned)
