### ISSUE TITLE
columnWidth in responsive layout ?

### ISSUE THREAD

**Issue by fabiobonzini** [metafizzy/packery#331]
Hello,
how can i specify "columnWidth" in my JS function just for media queries < 767px ?
my actualyy function in JS :+1: 
				$( function() {
				  var $container = $('.packery').packery({
				    itemSelector: '.grid-item',
				    columnWidth: 150,
				    gutter: 0
				  });
				});

thanks !

**Comment by desandro** [comment]
Have you looked at [element sizing](http://packery.metafizzy.co/options.html#element-sizing)?
