### ISSUE TITLE
Error resize

### ISSUE THREAD

**Issue by iliyaZelenko** [metafizzy/packery#333]
I have a problem in [this example](http://codepen.io/desandro/pen/ksAEn), where the change in the size, then if some political side to increase more than once, the size does not change correctly: add extra pixels on my number of pixels = 2 \* Border. Because of this, other elements are resting not as planned.

**Comment by iliyaZelenko** [comment]
To make it more clear, I have attached a picture. To see the bug need to expand the purple block and move the unit with an arrow.
![default](https://cloud.githubusercontent.com/assets/13103045/13117241/b6cba352-d5a7-11e5-8d44-983648a986df.png)

**Comment by desandro** [comment]
Sorry, but I will not be able to debug this issue.
