### ISSUE TITLE
Maintain vertical order & empty space after drag

### ISSUE THREAD

**Issue by waltermacambira** [metafizzy/packery#334]
A colleague just pointed out (@brenovieira) that when you have a gap in a column and you start dragging anything from another column, if there is an element on the same column of the gap that can fit in it, it will move itself inside the gap. I had the same problem when I wrote some modifications on Packery to have the same behaviour 2.0 has now. What I suggest is that you should keep the vertical order (every object trying to move should not go above the y-value of the closest element above it).

Later I will try to add a reduced test case. Here is a prinstscreen to illustrate the bug:

![image](https://cloud.githubusercontent.com/assets/3537591/13116046/88fbd76a-d581-11e5-8f65-984a5601c999.png)

When you start dragging tile 2, tile 1 fills the gap highlighted in yellow.

**Comment by waltermacambira** [comment]
Reduced test case: 

http://codepen.io/anon/pen/obRaqv

**Comment by desandro** [comment]
Thanks for reporting this issue. **+1 this issue** if you'd like to see Packery add this feature: maintain vertical ordering after dragging.

Packery v2 has just been released so I'm interested to see what the response is. This is a bit tricky as one of Packery's features is that it fills gaps. There's also the complexity of figuring out vertical order in a Packery layout.

**Comment by brenovieira** [comment]
+1

**Comment by iliyaZelenko** [comment]
+1

**Comment by waltermacambira** [comment]
@desandro you are correct that Packery is filling a gap as it is supposed
to, but you are not even touching that column and then something moves. I
believe that one of the reasons 2.0 is out is to make drag n drop more
friendly.

Walter Macambira - pelo celular
Em 19/02/2016 18:03, "David DeSandro" <notifications@github.com> escreveu:

**Comment by GarrisonJ** [comment]
+1

**Comment by MrAndrewAu** [comment]
+1

**Comment by desandro** [comment]
This issue has been mostly quiet. I feel the problems encountered here might be resolved by Packery v1's drop behavior. See #353. I'm closing this issue here.
