### ISSUE TITLE
Outlayer undefined when installing with Bower

### ISSUE THREAD

**Issue by promptdev** [metafizzy/packery#335]
`TypeError: undefined is not an object (evaluating 't.Outlayer.Item')`

Also, `fizzy-ui-utils` & `'get-size'` conflict if Flickity around.

$ bower install packery --save
bower packery#*                 cached git://github.com/metafizzy/packery.git#1.4.3
bower packery#*               validate 1.4.3 against git://github.com/metafizzy/packery.git#*
bower packery#*                    new version for git://github.com/metafizzy/packery.git#*
bower packery#*                resolve git://github.com/metafizzy/packery.git#*
bower packery#*               download https://github.com/metafizzy/packery/archive/v2.0.0.tar.gz
bower packery#*                extract archive.tar.gz
bower packery#*               resolved git://github.com/metafizzy/packery.git#2.0.0
bower outlayer#~2.0.0       not-cached git://github.com/metafizzy/outlayer.git#~2.0.0
bower outlayer#~2.0.0          resolve git://github.com/metafizzy/outlayer.git#~2.0.0
bower get-size#~2.0.2       not-cached git://github.com/desandro/get-size.git#~2.0.2
bower get-size#~2.0.2          resolve git://github.com/desandro/get-size.git#~2.0.2
bower get-size#~2.0.2         download https://github.com/desandro/get-size/archive/v2.0.2.tar.gz
bower outlayer#~2.0.0         download https://github.com/metafizzy/outlayer/archive/v2.0.1.tar.gz
bower get-size#~2.0.2          extract archive.tar.gz
bower get-size#~2.0.2         resolved git://github.com/desandro/get-size.git#2.0.2
bower outlayer#~2.0.0          extract archive.tar.gz
bower outlayer#~2.0.0         resolved git://github.com/metafizzy/outlayer.git#2.0.1
bower ev-emitter#~1.0.0     not-cached git://github.com/metafizzy/ev-emitter.git#~1.0.0
bower ev-emitter#~1.0.0        resolve git://github.com/metafizzy/ev-emitter.git#~1.0.0
bower fizzy-ui-utils#~2.0.0 not-cached git://github.com/metafizzy/fizzy-ui-utils.git#~2.0.0
bower fizzy-ui-utils#~2.0.0    resolve git://github.com/metafizzy/fizzy-ui-utils.git#~2.0.0
bower ev-emitter#~1.0.0       download https://github.com/metafizzy/ev-emitter/archive/v1.0.2.tar.gz
bower fizzy-ui-utils#~2.0.0   download https://github.com/metafizzy/fizzy-ui-utils/archive/v2.0.1.tar.gz
bower ev-emitter#~1.0.0        extract archive.tar.gz
bower fizzy-ui-utils#~2.0.0    extract archive.tar.gz
bower ev-emitter#~1.0.0       resolved git://github.com/metafizzy/ev-emitter.git#1.0.2
bower fizzy-ui-utils#~2.0.0   resolved git://github.com/metafizzy/fizzy-ui-utils.git#2.0.1
bower desandro-matches-selector#~2.0.0       not-cached git://github.com/desandro/matches-selector.git#~2.0.0
bower desandro-matches-selector#~2.0.0          resolve git://github.com/desandro/matches-selector.git#~2.0.0
bower desandro-matches-selector#~2.0.0         download https://github.com/desandro/matches-selector/archive/v2.0.1.tar.gz
bower desandro-matches-selector#~2.0.0          extract archive.tar.gz
bower desandro-matches-selector#~2.0.0         resolved git://github.com/desandro/matches-selector.git#2.0.1

Unable to find a suitable version for fizzy-ui-utils, please choose one:
    1) fizzy-ui-utils#~1.0.1 which resolved to 1.0.1 and is required by flickity#1.1.2
    2) fizzy-ui-utils#~2.0.0 which resolved to 2.0.1 and is required by outlayer#2.0.1

Prefix the choice with ! to persist it to bower.json

? Answer 2

Unable to find a suitable version for get-size, please choose one:
    1) get-size#~1.2.2 which resolved to 1.2.2 and is required by flickity#1.1.2
    2) get-size#~2.0.2 which resolved to 2.0.2 and is required by outlayer#2.0.1, packery#2.0.0

Prefix the choice with ! to persist it to bower.json

? Answer 2
bower fizzy-ui-utils#~2.0.0                     install fizzy-ui-utils#2.0.1
bower get-size#~2.0.2                           install get-size#2.0.2
bower packery#^2.0.0                            install packery#2.0.0
bower outlayer#~2.0.0                           install outlayer#2.0.1
bower ev-emitter#~1.0.0                         install ev-emitter#1.0.2
bower desandro-matches-selector#~2.0.0          install desandro-matches-selector#2.0.1

fizzy-ui-utils#2.0.1 bower_components/fizzy-ui-utils
└── desandro-matches-selector#2.0.1

get-size#2.0.2 bower_components/get-size

packery#2.0.0 bower_components/packery
├── get-size#2.0.2
└── outlayer#2.0.1

outlayer#2.0.1 bower_components/outlayer
├── ev-emitter#1.0.2
├── fizzy-ui-utils#2.0.1
└── get-size#2.0.2

ev-emitter#1.0.2 bower_components/ev-emitter

desandro-matches-selector#2.0.1 bower_components/desandro-matches-selector

**Comment by desandro** [comment]
Can you confirm what module loader you are using? Wiredep? See metafizzy/outlayer#33

**Comment by promptdev** [comment]
Yeap, wiredep.
metafizzy/outlayer#33 definitely did the trick.

overriding `outlayer`

```
"overrides": {
    "outlayer": {
      "main": [
        "item.js",
        "outlayer.js"
      ]
    }
  }
```
