### ISSUE TITLE
jQuery UI Draggable does not work on mobile

### ISSUE THREAD

**Issue by awcoding** [metafizzy/packery#336]
dragabilly homepage works but this error doesn't work in chrome or firefox
http://codepen.io/desandro/share/zip/CKbkw/

something I'm missing?

**Comment by desandro** [comment]
Thanks for reporting this issue. jQuery UI Draggable does not have support for touch events, but you may be able to add support with [jQuery UI Touch Punch](http://touchpunch.furf.com/)

**Comment by awcoding** [comment]
thx
