### ISSUE TITLE
Packery.fit() doesn't seem to work well with percent divs

### ISSUE THREAD

**Issue by nedtwigg** [metafizzy/packery#338]
Here's a simple example on codepen that demonstrates the issue:

http://codepen.io/nedtwigg/pen/pgXqPv

**Comment by desandro** [comment]
Yeah, animating item size is a bit tricky. See [Animating item size](http://packery.metafizzy.co/extras.html#animating-item-size) and the [animate responsive item size](http://codepen.io/desandro/pen/paFEH).

> You cannot transition or animate the size of an item element and properly lay out. But there is a trick — you can animate a child element of the item element.

**Comment by nedtwigg** [comment]
I'm not worried about animating the item size, my problem is with calling `fit()` to make percentage div occupy the top row.  The animation is just to make the layout changes clearer.

**Comment by nedtwigg** [comment]
I turned off all the CSS animation in the example to try to make it more clear that the problem has to do with calling packery.fit().

**Comment by desandro** [comment]
Thanks for that. The fix is to set [`columnWidth`](http://packery.metafizzy.co/options.html#columnwidth). See demo: http://codepen.io/desandro/pen/96cf65733572e4a2ddb5c12ec609ab5d/

`fit` works by looking for the closest item to replace position. You can help it out adding more positions to look for by adding `columnWidth`.

**Comment by nedtwigg** [comment]
In [my original codepen](http://codepen.io/nedtwigg/pen/pgXqPv), the screen starts out like this:
![packer-0](https://cloud.githubusercontent.com/assets/2924992/13234314/dfe03a46-d96c-11e5-8f9f-c8aa4e69c19e.png)

If you hover over A, it turns to this:
![packer-1](https://cloud.githubusercontent.com/assets/2924992/13234321/e7e8845a-d96c-11e5-986f-c2908e029407.png)

If you hover over B, it turns to this:
![packer-2](https://cloud.githubusercontent.com/assets/2924992/13234325/ed523314-d96c-11e5-86f5-c5c12201ed48.png)

And if you hover over C, it turns to this.  **This (hover over C) is the bug.**
![packer-3](https://cloud.githubusercontent.com/assets/2924992/13234354/15368ace-d96d-11e5-90e2-a85c27369ac2.png)
I'm trying to make it look something like this:
![image](https://cloud.githubusercontent.com/assets/2924992/13234394/450c65a2-d96d-11e5-8b3c-699ae846a326.png)

I'm trying to accomplish this like so:

```
var pos = $(activeCard).position();
// always position the active card at the top
if (pos.left == 0) {
    console.log('left')
    packery.fit(this, 0, 0);
} else {
    console.log('right')
    packery.fit(this, pos.left / 2, 0);
}
packery.layout()
```
This is what I'm seeing in your demo:

![packer-what-im-seeing](https://cloud.githubusercontent.com/assets/2924992/13233863/ac9cbd64-d96a-11e5-8e9f-d7e20f460e85.png)

[I went ahead and forked my codepen demo](http://codepen.io/nedtwigg/pen/qbzzaB) to try a `grid-sizer` div, but I get exactly the same behavior as before.  In the demos, I can see packery doing a very impressive job finding places for things.  But it seems to ignore that I'm calling `fit()` and explicitly placing the item on the top.

I feel like in my demo, packery is prioritizing preserving the order of the elements over meeting my layout constraints.  But in the demos, I seem to see elements getting reordered quite a bit.  I can't figure out what I'm missing.

**Comment by nedtwigg** [comment]
I ended up going with plain-old CSS and a sprinkling of javascript.
http://codepen.io/nedtwigg/pen/JGgdmx

I think what I needed was too simple for packery.  Fantastic library, thanks a ton for building it!
