### ISSUE TITLE
.gutter-sizer and .grid-size are being ignored

### ISSUE THREAD

**Issue by esgardilion** [metafizzy/packery#339]
Hi there, first of all, this is a great library!

This is the first time I am actually implementing it, and I am having some troubles getting my layout to work... I am using the library to render both a squared layout gallery of pictures and also a news section kind of Pinterest Layout...
The problem is, i guess, in my code 
`<div class="gutter-sizer-news"></div>
<div class="grid-sizer-news"></div>`, 
when the HTML is rendered they are styled with position:absolute, top:0 and left: X values... Hence, the first two blocks of content are being rendered not in line with the rest of the blocks 
(see http://imgur.com/PdIRZVS)

This is my code:

``` js
//SQUARED PICS
var $container = $('#grid').imagesLoaded( function(){
	$container.packery({
		gutter: ".gutter-sizer-pics",
		columnWidth: ".grid-sizer-pics",
		rowHeight: ".item", //fixes the top margin in the first two elements
		itemSelector: ".item"
	});
});

//PINTEREST LIKE GRID
var $container_masonry = $('#grid-masonry').imagesLoaded( function(){
	$container_masonry.packery({
		gutter: ".gutter-sizer-news",
		columnWidth : ".grid-sizer-news",
		itemSelector: ".item"
	});
});
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by esgardilion** [comment]
Sure... this is a testing environment in which you can see it live
http://dev2.intertech.mx/noticias/

**Comment by esgardilion** [comment]
This is the codePen http://codepen.io/esgardilion/pen/VeJJLv, but I am not being able to reproduce the same error as in the image (or the live site)

Any advice on how could i attack the problem?

**Comment by desandro** [comment]
`.gutter-sizer` and `.grid-sizer` are both commented out. Can you provide a **reduced test case** that demonstrates the issue?
