### ISSUE TITLE
Turn Packery On/Off on window size

### ISSUE THREAD

**Issue by ghost** [metafizzy/packery#34]
Hello,

I am just playing around with packery I am trying to get to turn on and off based on the size of the window.

I have it working where if the browser width is re-sized to less than 600px then packery kicks in. I am just having a difficult time that once the user re-sizes the browser back to anything greater than 600px to disable or turn off packery.

I took a look at the on/off methods in the docs but I am just a little confused on how to use them.

This is what I currently have

http://jsfiddle.net/Tjp7a/5/

Any suggestions would be greatly appreciated!

**Comment by tomsabin** [comment]
We can use `matchMedia` to make this [more efficient](https://jsperf.com/matchmedia-vs-resize/3):

```JS
if (Modernizr.matchmedia) {
  var mq  = matchMedia('(min-width: 660px)');
  var $container = $('[data-packery-target]');
  var packeryOptions = {
    itemSelector: '.item'
  };

  if (mq.matches) {
    $container.packery(packeryOptions);
  }

  mq.addListener(function(mql) {
    if (mql.matches) {
      $container.packery(packeryOptions);
    } else {
      $container.packery('destroy');
    }
  });
}
```

Support is decent: http://caniuse.com/#feat=matchmedia
