### ISSUE TITLE
New ajaxed items not being added to packery

### ISSUE THREAD

**Issue by andrey-lizunov** [metafizzy/packery#340]
Hello!
I'm trying to make editable gallery with infinite scrolling and dragging.
This library should solve this task, but I'm having problems with drag after adding new elements. Packery is not applied to new elements and drag starts work wrong.
Sorry if I'm doing something wrong and the problem on my side.
Below is the link to the example
http://codepen.io/andrey_lizunov/pen/NxQWdy

**Comment by desandro** [comment]
Thanks for reporting this issue. The issue is that you need to add the same jQuery object for `append` and `.packery( 'appended`,. [See demo](http://codepen.io/desandro/pen/2f1961f9d18ca7abcb6b5ac3ebf612d7/)

``` js
var $html = $(html);
$('[role="grid"]').append($html).packery('appended', $html);
```

**Comment by andrey-lizunov** [comment]
Thx David, works perfect!
