### ISSUE TITLE
imagesLoaded / Images stacking with CDN src

### ISSUE THREAD

**Issue by babxcka** [metafizzy/packery#341]
Hi David,

First of all, thanks for the brilliant plugin. It's been a joy to use so far and a lot of your documentation and responses to threads here have been so helpful.

I'm having some trouble with imagesLoaded... it's not working at all it seems. I am delivering my images with Cloudinary CDN, could this be the issue?

If I resize the window to any point, Packery kicks in and arranges the images as intended. 
But without doing that, it's just a big clump of images. 

Looking forward to being schooled. 

Thanks
![screen shot 2016-02-24 at 7 07 31 pm](https://cloud.githubusercontent.com/assets/13367065/13279210/1ac9116e-db2a-11e5-9963-77cbcb21857a.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery and imagesLoaded. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
