### ISSUE TITLE
packery not working properly with firefox

### ISSUE THREAD

**Issue by jhawas** [metafizzy/packery#342]
##i got this error in my console 	  if ( !item.isIgnored ) { in firefox but in chrome works properly

this is the link of the site that i am working on.
http://thesolarpages.com/francis/packery.php

you can see that the packery in chrome works properly but in firefox not.

**Comment by desandro** [comment]
Thanks for reporting this issue. I appreciate you providing a live URL, but I'm not able to reproduce this issue in Firefox 44. Can you put together a **reduced test case** that demonstrates the issue?

**Comment by jhawas** [comment]
reduced test case? i didn''t understant what you mean.  i'm new to this club.

**Comment by desandro** [comment]
See [Submitting issues guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#reduced-test-case-required)
