### ISSUE TITLE
No such method 'shiftLayout' for packery instance

### ISSUE THREAD

**Issue by andreibaracuda** [metafizzy/packery#344]
Can't use ShiftLayout method, am I missing something?
This is what I'm trying to do:

                var $pack=$container.packery({
                    columnWidth: '.resize',
                    rowHeight: '.packeryRowHeight',
                    itemSelector: '.tcl-tile',
                    percentPosition:true
                });

                setTimeout(function () {
                    $pack.packery('shiftLayout');
                }, 5000);

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
