### ISSUE TITLE
Dragging all elements to left-most column in masonry causes loss of use of other columns

### ISSUE THREAD

**Issue by ExciteM-Blog** [metafizzy/packery#345]
This is very self-explanatory (I hope). In the masonry demo at the start of 'http://packery.metafizzy.co/', I dragged all the elements to the left-most column; thereafter, I was not able to drag anything out of this column. I also tried by moving everything to the middle column, and that rendered the right-most column useless.
![screen shot 2016-02-25 at 5 25 01 pm](https://cloud.githubusercontent.com/assets/16438321/13340431/168ca3fc-dbe5-11e5-9bbd-fe4a0c93e909.png)

**Comment by desandro** [comment]
Thanks for reporting this issue! Looks like we we're following our own advice.

[Grid drop positions](http://packery.metafizzy.co/draggable.html#grid-drop-positions):

> We recommend setting columnWidth (or rowHeight for horizontal layouts) to help align dropped items to a grid . Without columnWidth set, dragged items can only be dropped in place of other items.

**Comment by ExciteM-Blog** [comment]
Great, thank you. I just saw it on the website demo and it threw me off.
