### ISSUE TITLE
enable/disable dragability via packery, no jQuery - (but without keeping record of draggables)

### ISSUE THREAD

**Issue by pliablepixels** [metafizzy/packery#346]
Hello, I am using packery to manage a movable gallery. I am trying to toggle draggability via a button.
Is it possible to do it in a way that I don't have to keep an array of all drag objects? Since pckry is a list of the entire set of items, is there a way to iterate the packery items and enable/disable drag for each?

I went through https://github.com/metafizzy/packery/issues/286 --> but that needs the instance of the drag object for each item

I am on vanilla JS.

thx

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by pliablepixels** [comment]
Hi @desandro here is a codepen. I'm not really facing a problem - I'm looking at how to dynamically enable/disable drag without having to keep an array of drag objects. My goal is since I am maintaining a list of packery objects, I should be able to get a handle to drag from iterating it. 

http://codepen.io/pliablepixels/pen/VaYpQj?editors=1010

Please see function toggleStatus() -- I've added a comment on what I want to do

This is note really a completely reduced test case, but its very straightforward - it uses angular

**Comment by pliablepixels** [comment]
thank you for the clarification.
