### ISSUE TITLE
Dragging items causes others to float up

### ISSUE THREAD

**Issue by GarrisonJ** [metafizzy/packery#347]
You can reproduce this bug on any of the drag-and-drop examples on the Packery website: http://packery.metafizzy.co/. 

If a block is 'hanging' underneath or on top of a block it will fall when you move a different block. (This is hard to describe, see gifs.)

Also, I am unsure if being able to stick an item underneath another (like in the first gif) is expected behavior. 

![Dragging an item underneath another](https://cloud.githubusercontent.com/assets/1311932/13446127/9a8c68f2-dfc5-11e5-9497-ae292759f3e4.gif)
![Dropping through another block](https://cloud.githubusercontent.com/assets/1311932/13446129/9ec7db9a-dfc5-11e5-9a54-920255292d8a.gif)

**Comment by desandro** [comment]
Thanks for reporting this issue. We already have another issue opened for it. Closing here, follow along at #334
