### ISSUE TITLE
Drag pack items horizontally

### ISSUE THREAD

**Issue by lgm42** [metafizzy/packery#348]
The behavior of the pack method doesn't fit my needs

I'm in vertical alignement but when I put an item before an other, i would like it goes to the left and not to the end of the line.

See attached gif animation before and after:
![animation before](https://cloud.githubusercontent.com/assets/6039130/13530726/2042991c-e223-11e5-934b-b6b6f36e4160.gif)

![animation_after](https://cloud.githubusercontent.com/assets/6039130/13530729/260522f2-e223-11e5-91e5-ade411a723cd.gif)

To make this works for my needs I have changed packed method at line 178 of packery.js

```javascript
proto._getPackMethod = function() {
  return 'rowPack';
};
```

this is an quick and dirty modification but works for me. Maybe an option to set in the packery ctor instead ?

**Comment by desandro** [comment]
Thanks for reporting this issue.  Another solution is to set [`horizontal: true`](http://packery.metafizzy.co/options.html#horizontal)

**Comment by lgm42** [comment]
No horizontal change also the layout. If I have 5 widgets they are all on
the same column instead of being on the same line. This behavior hasn't to
be binded to horizontal disposition I think.

**Comment by kalenjohnson** [comment]
I have a similar use case. I will have set height and width boxes, and I would like the ability to drag and drop to order the items, however the current functionality of having items move up to fit looks nicer but doesn't make sense from a sorting point of view.

Would you be open to a PR to allow setting the pack method as an option for packery?

**Comment by desandro** [comment]
Sounds like both use cases would prefer the [drag & pack behavior from Packery v1](http://packery.metafizzy.co/v1/draggable.html). I'd like to hear more feedback before adding more code.

**Comment by cbtdev** [comment]
There is a [new issue](https://github.com/metafizzy/packery/issues/353) open on this subject where they are collecting feedback and support for this particular feature request. It sounds like if there is enough support for this they will consider adding v1 drag and pack behavior as an option.

**Comment by desandro** [comment]
Yes, please [**+1 or add a :+1: reaction** to #353](https://github.com/metafizzy/packery/issues/353)  if you'd like to see Packery v1 drag packing behavior be added back to Packery v2.

**Comment by kaisermann** [comment]
+1 Also in need of this :)

**Comment by UranusCEO** [comment]
+1

**Comment by neuropass** [comment]
yes please. Great idea. Also see this for a serialize option: https://github.com/metafizzy/packery/issues/397

**Comment by desandro** [comment]
Closing here. Please see #353 for Packery v1 drag behavior issue.
