### ISSUE TITLE
hide/unhide packery element

### ISSUE THREAD

**Issue by pliablepixels** [metafizzy/packery#350]
Hello, I am looking at hiding/unhiding a packery element dynamically. I want the element to remain in the pckry list but just not displayed. Doing it directly in my template using ng-if or similar constructs throws the packery layout into disarray as packery still thinks its displayed.

I found this old issue https://github.com/metafizzy/packery/issues/3 - but it looks like work in progress.

Is it possible to let me know if I can do something like:

```
pckry.getItemElements().forEach(function (itemElem) {
  if (someCondition) itemElem.hide() else itemElem.show();
});
```

thanks!

**Comment by desandro** [comment]
Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

What you're asking for sounds very similar to [Isotope's filtering behavior](http://isotope.metafizzy.co/filtering.html). Isotope does have a [packery layout mode](http://isotope.metafizzy.co/layout-modes/packery.html).

**Comment by pliablepixels** [comment]
Thanks I'll check out isotope. Will the same code you posted for packery save and restore layout work with isotope too? Also I have purchased a license for packery. If I need to change to isotope will I be required to purchase a new license? Thanks.

**Comment by desandro** [comment]
>  Will the same code you posted for packery save and restore layout work with isotope too? 

No, Isotope does not support dragging

> Also I have purchased a license for packery. If I need to change to isotope will I be required to purchase a new license?

No, email yo@metafizzy.co so we can make the switch.

**Comment by pliablepixels** [comment]
Ouch - thanks @desandro  - then I can't use isotope if it does not support dragging. I'll set up a codepen for you as requested using packery.

**Comment by pliablepixels** [comment]
I'm closing this - I resolved it by essentially hiding it using ``ng-show`` in angular so it doesn't really get removed from the DOM and the packery array doesn't get confused, followed by a ``packery.layout()``
