### ISSUE TITLE
.grid container resizes on its own

### ISSUE THREAD

**Issue by z1haze** [metafizzy/packery#351]
Hi I have been battling an issue all day with this plugin and the .grid container resizing all on its over after moving a few grid items. It seems to only have if you move and entire columns worth of items from one side to the other, then you are unable to move them back because the grid container has shrunken a few pixels making it be be able to fix.

For example my top row has 4 25% width grid items.
the second row has 2 50% grid items. If i move to top far right grid item in the first row down to the left side, then move the second grid item in the second row over to the left side as well, something weird happens and the .grid resizes a few pixels making it impossible to move the elements back to where they came from. 

Oddly enough a window resize event seems to fix this issue, but it doesnt really help much because a person isnt going to resize their window every time they move a module. Please look into this.

**Comment by z1haze** [comment]
https://gyazo.com/edc1a72f84ca53360b68da25fb2f7609
https://gyazo.com/d979a53fa1292550303d90caf5d177e9

here are two examples of some weird resizing and spacing going on.. Also in the second one i am trying to place the boxes back at the top and they wont go to the right they just keep pushing down.

**Comment by z1haze** [comment]
I think it only have the problem if the window is maximized? maybe if that can help guide you

**Comment by desandro** [comment]
Sounds like you want [drag packing behavior of Packery v1](http://packery.metafizzy.co/v1/draggable.html). Packery v2 changed its drag behavior so that items only move up or down.

**Comment by z1haze** [comment]
No not at all.. Look at the animated gifs. If you can't tell from those let me
Know and I'll make an actual video

**Comment by desandro** [comment]
[Do you have `columnWidth` set?](http://packery.metafizzy.co/draggable.html#grid-drop-positions)

> We recommend setting columnWidth (or rowHeight for horizontal layouts) to help align dropped items to a grid . Without columnWidth set, dragged items can only be dropped in place of other items.

**Comment by z1haze** [comment]
Yes of course column width is set

**Comment by z1haze** [comment]
What I'm saying is this.. With my screen maximized on first load of the grid, the grid container is 1600px ok? If I move grid items from one side to the other the grid container resizes itself to to something like 1587px thus making it impossible to put my grid items back where they came from because they won't fit.

**Comment by desandro** [comment]
aah, I think this may just be an issue with the vertical scroll bar. You can force a scroll bar with

``` css
html { overflow-y: scroll; }
```

**Comment by z1haze** [comment]
I never thought to check that's a good thought I'll let you know what happens

**Comment by z1haze** [comment]
Ok, seems that was the issue, however shouldn't this be marked as a bug.. The behavior of the scroll bar should be compensated for and the grid should be adjusted on its own I believe.. To drop a hint as to where I think you can fix it: During a window resize event, something happens in the script where it fixes itself.. So many on drag placement or something, make that bit of code execute on its own?
