### ISSUE TITLE
Strange overlap on a single grid item

### ISSUE THREAD

**Issue by z1haze** [metafizzy/packery#352]
If you can take a look at the animation below, you'll see that for some reason the 'website traffic' module and the auction payment history module just hide one another.. The website traffic module content does load via ajax, but I just $grid.packer() after it finishes, so shouldnt that take care of the grid sizing?

https://gyazo.com/399facebe5e6488871b84a9ec4045c72

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
