### ISSUE TITLE
Elements can stuck on one side after dragging

### ISSUE THREAD

**Issue by andrey-lizunov** [metafizzy/packery#356]
Hello David!
I have some proplem and not sure is it bug or a feature))
I asked a question several weeks ago and now use example from that issue.
http://codepen.io/desandro/pen/2f1961f9d18ca7abcb6b5ac3ebf612d7/
If you open this example and start to move all elements from left side to the right, than with time all items will gather on the right side and lined up in one line. I expect that they will line up in the order of the current sorting after the drag and will fill all space.
How can I avoid this behavior? 
I provide an image with this issue.
![2016-03-22 05 56 33](https://cloud.githubusercontent.com/assets/1709731/13940908/0982febe-eff3-11e5-9cdc-8840ca8f3171.png)

**Comment by andrey-lizunov** [comment]
oh, sorry. I'm so stupid((
I can use `layout` method.
My bad. Hope this ussue will help somebody)

**Comment by andrey-lizunov** [comment]
I think I find some strange behavior
Last elements change its position two times. 
https://youtu.be/OOJnGSXFE9Y
And on this video item dissapears after drag.
https://youtu.be/i9402DtTzOE
I provide an codepen example.
http://codepen.io/andrey_lizunov/pen/aNJMQa

**Comment by desandro** [comment]
This is the problematic code:

``` js
    $grid.on( 'dragItemPositioned', function() {
      $grid.packery();
    });
```

Triggering `layout` after `dragItemPositioned` lays out items again, which is why the dragged item jumps around.

You may be interested in adding back Packery v1's drag behavior. See  #353
