### ISSUE TITLE
In some cases packery resolves to a long one column grid

### ISSUE THREAD

**Issue by karatefish** [metafizzy/packery#357]
Hello, 
while i was playing with the example at http://codepen.io/desandro/pen/jGJKL
I realized that when you always click with the top-right element ( also when it is expanded )
The grid will end up in one long column. Is this part of the logic? Can the priority be set somewhere ( as in prefer to fill the grid by width rathen then by height?

thanks

**Comment by desandro** [comment]
Thanks for reporting this issue. Yes, this is the intended behavior with Packery v2. You can trigger `layout` to re-pack all items to take up an gaps in horizontal space.

You may also be interesed in #353
