### ISSUE TITLE
Disable set container size

### ISSUE THREAD

**Issue by yairEO** [metafizzy/packery#358]
http://packery.metafizzy.co/options.html#containerstyle

Clearly says:

> disable any styles being set on container

**Yet** the grid container is being set with a `height` style! and incorrect one also! 
whats up with that? I want nothing, as the name and description says. 

-------------
My container is set-up like this:

    position:absolute;
    top:50px;
    right:50px;
    bottom:50px;
    left:50px;

Seems to give the ol' script a hard time for some odd reason

**Comment by desandro** [comment]
You can disable Packery from setting container size with an undocumented option `resizeContainer: false`:

``` js
$grid.packery({
  resizeContainer: false
})
```

[`containerStyle`](http://packery.metafizzy.co/options.html#containerstyle) is used to set `position: relative` on the container.
