### ISSUE TITLE
Contain elements inside

### ISSUE THREAD

**Issue by khalilgharbaoui** [metafizzy/packery#359]
Hi how you doing?

I'm kind of experimenting with draggable packery.

how can i contain the grid elements inside the box?

look at it: 

http://rubber-duck-puzzle.bitballoon.com

i don't want them to be placeable outside... please help.

**Comment by desandro** [comment]
Sounds like you are interested in Packery v1 drag/ pack behavior. See #353

**Comment by khalilgharbaoui** [comment]
That made the difference 😁✌️

Thanks.
