### ISSUE TITLE
Dragabilly - Add class name to items that are not active

### ISSUE THREAD

**Issue by Jessekevon** [metafizzy/packery#361]
Hello, do you have a method to add a class name to the items that are currently inactive? I've tried adding a conditional statement to achieve this but no luck. Wondering if you had something like this built in.

For example, if '.item' hasClass 'is-dragging' then all OTHER items would have a class of lets say 'inactive' so that we could style those in an inactive state.

Let me know if that makes sense.

thanks,

Jesse

**Comment by desandro** [comment]
You could add this behavior with Draggabilly's [`dragStart`](http://draggabilly.desandro.com/#dragstart) and `dragEnd` events.
