### ISSUE TITLE
Cannot drag item to empty column

### ISSUE THREAD

**Issue by alvarotrigo** [metafizzy/packery#362]
Great library!!
I'm probably doing something wrong, but what is it?

[Reproduction online](http://jsfiddle.net/1kxzf2d4/1/embedded/)

![untitled screencast](https://cloud.githubusercontent.com/assets/1706326/14208489/948e4190-f817-11e5-9412-8d84a9c01b76.gif)

I started using masonry.js and moved to packery because I need to be able to sort the elements as I wish.
I'm not quite sure to understand the difference between a *Draggable Masonry layout* and a *Draggable dashboard*, so not quite sure if my problem can be related with that.

Also, I guess there's no difference between using Draggabilly or jQuery UI?

Update
===
It seems to be related with leaving a column empty.

**Comment by desandro** [comment]
Thanks for reporting this issue. [You can resolve this issue by setting `columnWidth`.](http://packery.metafizzy.co/draggable.html#grid-drop-positions)

See demo http://jsfiddle.net/4shr1ssy/

> We recommend setting `columnWidth` to help align dropped items to a grid . Without `columnWidth` set, dragged items can only be dropped in place of other items.

---

> I'm not quite sure to understand the difference between a Draggable Masonry layout and a Draggable dashboard,

The only difference is how you size your items. I use these terms for SEO.


> I guess there's no difference between using Draggabilly or jQuery UI

Draggabilly supports touch devices. Touch support for jQuery UI is questionable.

**Comment by alvarotrigo** [comment]
Thanks for the answer and the explanations!
I knew I was missing something stupid :)
