### ISSUE TITLE
drag event not being fired

### ISSUE THREAD

**Issue by z1haze** [metafizzy/packery#363]
I have an issue with events not firing

```
$grid.on( 'dragItemPositioned',
        function( event, draggedItem ) {
            console.log( 'Packery drag item positioned',
                draggedItem.element );
        }
    );
```

I have dragging set up working with draggabilly, the functionality of the movement works, etc.. but i need to fire a dragItemPositioned event in order to save the user's widget locations. Please help to figure out why this event is not firing.

**Comment by z1haze** [comment]
To add to my previous issue, NONE of the events are firing, not even the default layout complete event, yet everything is still working.. what could be wrong here?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by z1haze** [comment]
Don't worry about this one I figured it out. I think it was an issue of having multiple query instances somehow. I included it jquery as a script tag then exposed it in browserify. That seemed to fix it
