### ISSUE TITLE
Draggable behavior is not working properly

### ISSUE THREAD

**Issue by reojavier439** [metafizzy/packery#364]
Hello there,

I'm having an issue with `Draggable`, it seems that every grid is always floating high above the mouse pointer when I started dragging it, something like it stick up against the top of the container. I have an instance of `Packery` with one option for `originTop: false`.

I just need an idea if the `originTop` set to `false` that is causing the issue. I might prepare a pen for this.

Thank you.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).

**Comment by reojavier439** [comment]
Thank you for the time looking into this issue. I have replicated the setup or prototype here:
http://codepen.io/ApparatoTeam/pen/PNQqqg

Apparently when I set the value for the attribute `originTop` to `true` it will be fine, the behavior is just not the way I expected when set to `false`.

Thanks!

**Comment by reojavier439** [comment]
I have just checked your pen here http://codepen.io/desandro/pen/qwyuF, and tried adding attribute
`originTop: false` from the JS editor `line 6`. The issue has been replicated for draggable application I have mentioned above.

**Comment by desandro** [comment]
Thank you for reporting this bug. We already have an issue open for this bug. See #244
