### ISSUE TITLE
 Cannot drag item to empty row

### ISSUE THREAD

**Issue by niconil** [metafizzy/packery#365]
similar to issue #362 i cannot drag an item to empty row when i use an horizontal layout.

you can see this behaviour here
http://codepen.io/oopee/pen/KktDg

in the horizontal layout if you put items on a single row you can not get one and put it on a new row

**Comment by desandro** [comment]
Thanks for reporting this bug. This is indeed a bug. I'll look into fixing this.

**Comment by joekoken** [comment]
I got the same problem for the vertical layout. Do you know the reason why?

**Comment by desandro** [comment]
v2.1.1 has been released with fixes for this bug. Thanks again for reporting this issue 🌈🐻
