### ISSUE TITLE
Packery Sorting

### ISSUE THREAD

**Issue by iamjonasmarlo** [metafizzy/packery#368]
Hey :)
Is there any way of sorting the grid-items using packery? This is my current javascript:
```
var $grid = $('.grid').isotope({
  layoutMode: 'packery',
  packery: {
      columnWidth: '.grid-sizer',
      gutter: '.gutter-sizer'
  },
    getSortData: {
    number: '[data-number]'
  },
  sortBy: 'number',
  itemSelector: '.grid-item',
  percentPosition: true
});
```
The sorting seems to work but the not every item is on it's right position.

You can check it out [here](http://relaunch.headonline.de/projekte/bahnsteig42-kommunikationskonzept/)!

Thanks :)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
