### ISSUE TITLE
Feature - add "offset" setting

### ISSUE THREAD

**Issue by yairEO** [metafizzy/packery#369]
I really need to add an offset (top & left) to each element (`itemSelector`) being re-positioned by Packery.

[Demo page](http://codepen.io/vsync/full/ONWmmq/) (might not be 100% stable, especially on Chrome)

My own grid system lets the use draw areas, and they are calculated with a gap all around them, and Packery's `gutter` doesn't work like that, it only leaves from the bottom and right, and **not** all around the element (like I want it to).

**Here's a photo before** running Packery: (each element is positioned with a padding in mind)

![1](https://cloud.githubusercontent.com/assets/845031/14587112/4b430a66-04b5-11e6-9688-1f99a64a29fc.png)

**Here's afte**r:
![2](https://cloud.githubusercontent.com/assets/845031/14587113/561461e2-04b5-11e6-893d-8773c4fb5c8c.png)

### Setup:

```
$('.grid').packery({
  itemSelector    : '.grid__area',
  resizeContainer : false,
  percentPosition : true,
  gutter          : 12
});
```

---------------------
Btw - it seems like the packing algorithm prefers to have "holes" between packed content, rather than organizing it in a way to minimize them. drawing a few random boxes and then clicking "pack" will show the issue pretty soon.

**Comment by desandro** [comment]
Interesting use case. Have you tried using CSS margin rather than Packery's `grid` option?

> Btw - it seems like the packing algorithm prefers to have "holes" between packed content, rather than organizing it in a way to minimize them. 

See #353

**Comment by yairEO** [comment]
yes I had considered `margins`, but that would require a headache of a change in the code, and I was wondering how come Packery doesn't offer `offset` out-of-the-box. Do you think it's something that could be done quickly or is it a pain-in-the-ass feature request? :)

**Comment by desandro** [comment]
I would say that it's a substantial feature request as it directly affects the layout algorithm. Looking at the bigger picture, this kind of feature is very similar to `gutter`, so it would be confusing for users. I appreciate your input for this request, but I'm afraid I cannot support this kind of feature.

**Comment by yairEO** [comment]
Thanks, I've modified my code to work with margins, it wasn't such a big change after all :)

http://codepen.io/vsync/pen/ONWmmq

But now there's a very bizarre case, where after packery is enabled, some areas are overflowed

## Pre-Packery:
![1](https://cloud.githubusercontent.com/assets/845031/14860221/713b56a8-0cb0-11e6-8a95-3d9a67cd7597.png)


## After:
![2](https://cloud.githubusercontent.com/assets/845031/14860222/716fa9bc-0cb0-11e6-87ee-a7d18e3e88e7.png)
