### ISSUE TITLE
stacked images and distribute images.

### ISSUE THREAD

**Issue by PixelArg** [metafizzy/packery#370]
Hello Desandro!
I take this opportunity to thank you for your tremendous work, thanks you very much!

I'm using Packery with AngularJS and when I entered on the gallery, images are one above each other:
![image](https://cloud.githubusercontent.com/assets/13700579/14659884/26bfc43c-0676-11e6-87b8-c35161315336.png)

or when I walk into an image and back again , the Packery is disabled

and the other cuestion, is how I can align/distribute the images between them, like this (the right image):
![image](https://cloud.githubusercontent.com/assets/13700579/14659995/1949243c-0677-11e6-83db-30d7f1568158.png)

And one last question . I need larger images to the screen to shrink , this will fix a "max-width: 100%" but also need the smaller images that the screen can not get smaller when they corralling between them.

Thanks you very much!

Agustín.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
