### ISSUE TITLE
v2.0.0 + RequireJS + pkgd version

### ISSUE THREAD

**Issue by danielefenix** [metafizzy/packery#372]
Good morning everyone,
I would like to thank you, first of all, for the amazing library.

I have a web interface based on RequireJS. 

I successfully used the v1.4.1 and v1.4.3 requiring the packery.pkgd.min.js script. The library could resolve the inner dependencies correctly when the pkgd version of the script was used.

I would like to upgrade the library version to v2.0.0 but when i require the pkgd version of the script the inner dependencies are not resolved. Dependencies like 'rect', 'item', 'packer'.

I read previous issues about this (e.g. [this](https://github.com/metafizzy/packery/issues/170)) and the solution suggested is to set the baseUrl to 'bower_components/' folder. 
Unfortunately it is not possible to do so for our project.

I would like to ask:

1 - Will the pkgd version of the library behave as the previous one? What i mean is that we configure RequireJS to resolve only the pkgd with no mention of the inner dependencies.

2 - Could you suggest an alternative to the baseUrl technique and to explicitly configure the inner dependencies paths?

Thank you very much for you time and your support.

**Comment by metaman** [comment]
We seem to have the same issue. v1 seems ok but in v2 the item, rect and packer deps are not found

**Comment by desandro** [comment]
Thank you for reporting this issue. Looks like the new way `pkgd.js` is being compiled has changed the file paths for Packery's internal files. I'll have to take a look and fix this in a future release.

**Comment by danielefenix** [comment]
Thank you very much @desandro

**Comment by NicolaFenix** [comment]
+1 - Thank you @desandro !!!

**Comment by danielefenix** [comment]
Just for your information, it seems that the issue persists in v2.1.0

**Comment by desandro** [comment]
v2.1.1 has been released with fixes for this bug. Thanks again for reporting this issue 🌈🐻
