### ISSUE TITLE
Making packery aware of css modifications  to DOM while laying out

### ISSUE THREAD

**Issue by pliablepixels** [metafizzy/packery#373]
Hello, I have a situation where certain images will be rotated on the canvas using webkit-transform:rotate 
It looks like packery does not take into consideration such transformations when laying out, even if the transformation was applied before packery is initialized.

Example:  http://codepen.io/pliablepixels/pen/qZyGPb?editors=1010

In this codepen, I've rotated the first image by 90 degrees but packery is not aware of that during layout. Is it possible for me to make this situation work?

thanks

**Comment by desandro** [comment]
CSS transforms do not change browser layout. If you want to use rotation, you'll have to calculate the new size of the item and change it explicitly, then trigger `.layout()`.

**Comment by pliablepixels** [comment]
@desandro - my situation is this:
I am using your library to display images from various cameras in a montage. For the most part, everything works great, except in a case where the camera is rotated when installed.

the backend server mandates that the receiving client swaps the width/height of the img tag when displaying. I can't change that. This works fine when I do a ``img src`` tag without packery, but with packery, things get ugly if I try and force change width="xx" and height="yy".

I guess my question therefore is, is there any way to swap the image w/h and have packery take it into account? I unfortunately can't share a codepen for this as the camera feeds are not public.

Thank you

**Comment by desandro** [comment]
If you make changes to item sizes, you can use [`layout`](http://packery.metafizzy.co/methods.html#layout-packery) or [`fit`](http://packery.metafizzy.co/methods.html#fit) to layout items. Try playing around with both demos. How and when you change item size is up to you. One solution is to use a wrapping elements for item, so you can set its size with CSS.

**Comment by pliablepixels** [comment]
ok thanks!
