### ISSUE TITLE
Unexpected gap.

### ISSUE THREAD

**Issue by SidKH** [metafizzy/packery#374]
Hi. I've run into strange issue:
When I have two narrow items and the wide one after them, I'll have a gap on the right.

**Test case:** https://jsfiddle.net/vn1qrudf/
Shouldn't they rearrange like this for example - http://prntscr.com/b0kdt5 ?

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like everything is working as expected. Packery does not re-order items. To create the expected layout, you can re-order the items so the wide item is second. See https://jsfiddle.net/vn1qrudf/1/

**Comment by SidKH** [comment]
Oh... Understood. 
I thought packery will reorder blocks to prevent this gaps, I think that would be a great feature. 
Anyway, thanks for the quick response.
Your libraries are outstanding.
