### ISSUE TITLE
Safari zoomed page invalid height

### ISSUE THREAD

**Issue by feropeterko** [metafizzy/packery#375]
When you zoom out in Safari and refresh the page, item width is computed incorrectly. This is because of the incorrect value of height. Outer height should be the same as element.offsetWidth (example below). Other browsers interpret given values correctly and the bug don't appear.

size.outerWidth = elem.offsetWidth;
size.outerHeight = elem.offsetHeight;

and height should be computed with subtracting margin:

size.width = size.outerWidth - marginWidth;
size.height = size.outerHeight - marginHeight;

Located at function **getSize**

Preview:
![bug](https://cloud.githubusercontent.com/assets/165651/15107631/23f2be52-15d1-11e6-91b7-3b406d66fa08.jpg)

**Comment by desandro** [comment]
Thank you for reporting this issue. We already have #273 opened to track it. I've added your comment there.
