### ISSUE TITLE
Move Packery items horizontally instead of vertically when Draggabilly used. 

### ISSUE THREAD

**Issue by Grey007** [metafizzy/packery#377]
Hi, 

I am wondering if it is possible to sort items horizontally when using Draggabilly. When using Draggabilly items shit down, instead of shifting left like in a order. 

Is this possible?

**Comment by desandro** [comment]
Thank you for submitting this issue. You can use [`horizontal: true`](http://packery.metafizzy.co/options.html#horizontal), if you want items to layout and shift horizontally. See demo http://codepen.io/desandro/pen/112c30cfe0191cb24c3512f0b933d25c/ . You might also be interested in Packery v1 behavior #353

**Comment by Grey007** [comment]
This doesn't seem to work. I am using the following test case as previously provided by you: http://codepen.io/desandro/pen/GcDbr 

If you add `horizontal: true`, the layout of items does not work.

**Comment by desandro** [comment]
Looks like you need to set a height on the container element. See demo http://codepen.io/desandro/pen/cd56885ca8eac7be059beb10477136de/

**Comment by ashubham** [comment]
Setting height `(horizontal: true)` would result in infinitely wide grids, which is undesirable.

I think, behaviour mentioned in #353 would be good to have, as tiles shifting down when dragging is not coming naturally to our users.

**Comment by jeffaltman** [comment]
I am having the same problem. When I drag an item sideways it shifts the replaced item down instead of swapping positions.

**Comment by desandro** [comment]
Sounds like this discussion is looking for Packery v1 behavior. Let's keep discussion there in #353. Closing this issue.
