### ISSUE TITLE
Packery won't let an element go back to where it was in the first place!

### ISSUE THREAD

**Issue by Ptival** [metafizzy/packery#379]
This is one of the codepens I found in Packery docs:

http://codepen.io/desandro/pen/cyvra

Open it and move the top-right square out of where it was.
Now try to put it back where it was: it is impossible, it will want to go in the left column with the other one.

In general, it is hard to put a teal square to the right of another teal square, they will want to stack vertically.

I don't understand if this is intended behavior.

**Comment by desandro** [comment]
Looks like this older v1 demo was missing [`columnWidth` for grid drop positions](http://packery.metafizzy.co/draggable.html#grid-drop-positions)

> We recommend setting columnWidth to help align dropped items to a grid . Without columnWidth set, dragged items can only be dropped in place of other items.

See updated demo http://codepen.io/desandro/pen/cyvra

Thanks for the heads up!

**Comment by Ptival** [comment]
Awesome! Thanks!
