### ISSUE TITLE
How to pull item to bottom or top if window width matched ?

### ISSUE THREAD

**Issue by l2aelba** [metafizzy/packery#380]
Is there any trick to pull item(s) to bottom or top if window width matched ?

I can not find any function on doc sorry.

```javascript
var $pull_bottoms = $('.grid-item--pull-bottom-mb');
$(window).resize(function() {
  if($(window).width() <= 500) {
    
  } else {
    
  }
}).resize()

```
http://codepen.io/l2aelba/pen/yOdEXZ

**Comment by desandro** [comment]
You can try using stamp with media queries:

http://codepen.io/desandro/pen/a8b0bcd48e6e397a9b45bc716566aef8/

It doesn't quite work with bottom set, as the container is collapsed when its measured. But this concept could work.
