### ISSUE TITLE
Possible to preserve "left to right" order?

### ISSUE THREAD

**Issue by olalonde** [metafizzy/packery#381]
Is it possible to preserve left-to-right order with packery? For example, I want elements to be in order, row by row and only remove the whitespace between elements within a column (all my elements have a fixed width). Is that possible?

**Comment by olalonde** [comment]
<img width="1144" alt="screenshot 2016-05-23 19 30 39" src="https://cloud.githubusercontent.com/assets/416585/15490439/e00376b2-211c-11e6-9d4f-566975e1d08b.png">

e.g.: I want to remove the gaps between elements in the same column.

**Comment by desandro** [comment]
Hello! Thank you for submitting this issue. Sorry, no. Packery's layout algorithm does not support maintaining left-to-right order. You may be interested in [Masonry Ordered](https://masonry-ordered.tasuki.org/), designed for this purpose. It's a bit old now (3 years) so I can speak for its quality.

**Comment by olalonde** [comment]
@desandro thanks!
