### ISSUE TITLE
layoutComplete is only being triggered the first time packery('layout') is called

### ISSUE THREAD

**Issue by ChubbyNinja** [metafizzy/packery#383]
Hey all, 

I have an issue with `layoutComplete` only being triggered the first time `grid.packery('layout')` is being used.

Here's a snippet of what I am doing:

```

    grid = $('.grid').packery({
        itemSelector: '.grid-item',
        gutter: 0,
        horizontal: true,
        initLayout: false
    });

    grid.on( 'layoutComplete', function() {

         setTimeout(function(){

             console.log('Triggered layoutComplete');

             var screen_width = $(window).width();
             var width = $('.grid').outerWidth();

             var offset = width - screen_width;

             container.css({
                 left: '-' + offset + 'px'
             });

         },20);

    });

    $(window).on('load',function(e){
        $('.grid-item').addClass('fade-in');
        grid.packery('layout');
    });


    window.removeSome = function(i) {
        $('.grid-item.data-' + i).hide();
        grid.packery('layout');
    }
```

So, when window has loaded fully, trigger the first `grid.packery('layout')` and this works fine, but, when I call `removeSome(3);` it removes the correct elements, and re-sorts them but it doesn't trigger the `layoutComplete` event.

The `layoutComplete` event is supposed to calculate the offset of the grid to screen, this works OK but as i say is only being triggered once.

In this reduced test case, I have automated the removeSome to a timeout (wait 10 seconds) so you can see.

**Test case:** http://codepen.io/ChubbyNinja/pen/NrWqrd

Is this a bug?

**Comment by desandro** [comment]
Thanks for reporting this issue. The trouble is that an element that is hidden with `display: none` is still considered 'visible' by Packery, so it expects its transition to end. That's why the second layoutComplete never gets triggered.

The way to fix this is to let Packery know that this item is hidden. One way to do this is with `hideItemElements` (an undocumented method — I'm not sure if its worth making public).

``` js
  var $hideItem = $('.grid-item.data-' + randomNumber());
  grid.packery( 'hideItemElements', $hideItem );
  grid.packery('layout');
```

See demo http://codepen.io/desandro/pen/7267bb5d71a268129c13211ac9ecd237/

**Comment by SanderMuller** [comment]
@desandro 
I want to hide grid elements and then relayout so it's a neat layout again, and at the same time receive the `layoutComplete` event.

As explained, `layoutComplete` doesn't fire when there are hidden grid items.
I tried the given solution:
```
 var $hideItem = $('.grid-item.data-' + randomNumber());
  grid.packery( 'hideItemElements', $hideItem );
  grid.packery('layout');
```

Both in my own code, and in the demo (http://codepen.io/desandro/pen/7267bb5d71a268129c13211ac9ecd237/) the grid doesn't trigger a layout anymore after hiding the elements (but the event is triggered). If I call `grid.packery('layout');` in the  `layoutComplete` event, then I get the correct layout again, but this adds a visible delay and a feedback loop of the events triggering a layout, which triggers the event, etc.

Do you have any pointers?
