### ISSUE TITLE
1px gap between images on percentPosition: true

### ISSUE THREAD

**Issue by ragazzin** [metafizzy/packery#387]
Hello,
i'm sorry for my english.

It's many days that i try to figure out an issue that i see trying to create a responsive fullwidth grid of images. For some resolution of my browser i see a 1px gap between images. I have read about this problem in many post (for example https://github.com/metafizzy/packery/issues/42) but no solution works for me.

I also have opened a question on Stackoverflow that can help you to understand my situation: http://stackoverflow.com/questions/37925902/1px-gap-using-isotope-masonry-or-packery-expecialy-on-safari 

I'm going to attach some of my code:
HTML
`<div class="grid">
	<div class="grid-item" ><a href="#"><img src="..." title="prova" class="lazy"></a></div>
	<div class="grid-item grid-item--width2 " style="position: absolute; left: 24.8916%; top: 0px;"><a href=#"><img src="..." title="Atletica mondiale – 30ma edizione" class="lazy"></a></div>
	<div class="grid-item grid-item--width2 " style="position: absolute; left: 0%; top: 612px;"><a href="#"><img src="..." title="la metamorfosi di Kafka di Città di Ebla" class="lazy"></a></div>
	<div class="grid-item" ><a href="#"><img src="..." title="Istituto Oncologico Romagnolo" class="lazy"></a></div>
	<div class="grid-item" ><a href="#"><img src="..." title="RomaOstia 2016" class="lazy"></a></div>
	...
</div>`

CSS
`.grid {
    margin: 0 auto;
    width: 100.5%;
    margin-bottom: 0px !important;
}
.grid-sizer,.grid-item {
	width: 24.9%;
	display: block;
    float: left;
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
    list-style: none!important;
}
/* 2 columns wide */
.grid-item--width2 {
	width: 49.8%;
	display: block;
    float: left;
}
.grid-item img{
	display:block;
}`

JS
`// init Packery
var grid = jQuery('.grid').packery({
  itemSelector: '.grid-item',
		percentPosition: true
});
// layout Packery after each image loads
grid.imagesLoaded().progress( function() {
  grid.packery();
});`

Anyone can help me?

**Comment by ragazzin** [comment]
I have updated the post excluding urls of images and links :)

**Comment by desandro** [comment]
1px gaps may appear in some layouts in some sizes. They occur due to pixel rounding differences between JavaScript and CSS. One way to resolve them is with this technique: http://metafizzy.co/blog/beyonce-seamless-fluid-image-masonry/

``` css
/* not quite 33.3% */
.item { width: 33.2%; }

/* images cover up the gap */
.item img { width: 100.5%; }
```

Or you can opt to not use fluid sizes, and fall back to fixed pixel sizes that will divide evenly. Or you can opt to not use Packery.

**Comment by ragazzin** [comment]
Really thanks @desandro!!! i have been able to solve the problem with your suggestion!! For more details please click here `http://stackoverflow.com/questions/37925902/1px-gap-using-isotope-masonry-or-packery-expecialy-on-safari`

**Comment by Destructorrr** [comment]
I have the same issue here. I'm using Isotope, Packery and ImagesLoaded to create 4 column grid with images. I tried the hack but it only help for gaps between columns but I have gaps on rows too. I've noticed that the browser fits the images if I open developer tools or use Isotope filter. I'm also using Infinite scroll and when appending new elements to the grid they are gap less. Can you review my issues at [this url](http://driveaholic.bg) and advice? Thank you in advance for you great work with the plugins!
