### ISSUE TITLE
Not filling the blank spaces for random items

### ISSUE THREAD

**Issue by kapilsurolia** [metafizzy/packery#388]
Hi Friend,
I have created a design using packery but blank spaces is not filling. I am changing the items position randomly with every page load with different sizes of items. When in the last rows landing the highest width or height items then not filling the items. Please send me any suggestion regarding this `issue.`

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).

**Comment by kapilsurolia** [comment]
Hi Friend,
You can see in this link - http://digitalmaddy.com/packery/index2.html
In the last row some time it has blank space not fill complete layout

**Comment by kapilsurolia** [comment]
![break layout](https://cloud.githubusercontent.com/assets/20179231/16415665/0001ec72-3d5c-11e6-8240-b5ead97e58b2.jpg)
Hi Friend,

You can see my problem in this attachment. If any solution please send me.

**Comment by desandro** [comment]
It looks like the layout is behaving as intended. Packery does not resort items for a efficiently packed layout, so there may be extra space at the end of the layout.

**Comment by kapilsurolia** [comment]
Hi Friend,
We want to resort items randomly per page load like https://www.chumbak.com/. This site is using packery and randomly sort the items.
Is Packery has any function to resort the items randomly ? Right now i have resort the items using jquery random function.

**Comment by desandro** [comment]
> Right now i have resort the items using jquery random function.

Packery does not have any sorting feature. Using jQuery here for sorting is one way to do it.
