### ISSUE TITLE
Adjusting height of grid item to push down on other grid items

### ISSUE THREAD

**Issue by coolwebs** [metafizzy/packery#389]
This is a continuation of an issue raised here https://github.com/metafizzy/packery/issues/386 but it deserves it's own separate issue log. @desandro, I decided to go with your 2nd option and put my three 1/3 grid item elements into a parent container to keep them altogether. Within those grid items, I have jQuery toggle menus that open up when clicked on. The issue is that when Packery is activated, the toggle action does not push down other elements below it, the toggle text just flows over the top of it. It happens whether the element below is within the Packery grid or not. When I disable Packery (and just rely on Bootstrap framework) it does not have this issue.

I am using Packery v1.4.3 as I am still required to support IE8 (unfortunately).

Link to branch in my repo: https://github.com/SLQ-web/Fauna/blob/Sugar-Glider/html/prototype-base.html (it's very "rough")
Link to a rawgit demo: https://rawgit.com/SLQ-web/Fauna/Sugar-Glider/html/prototype-base.html

I can't figure out what behaviour of Packery is not allowing me to dynamically change the height of the grid item element and force it to push down other grid items on the page. At first I thought it was the inline style declared height on parent grid element, `<div class="grid" style="position: relative; height: 1770px;">` but disabling that in inspector does not make a difference.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).

**Comment by desandro** [comment]
The layout is not changing because Packery needs the final size of items to properly lay them out. Because the menus are animated, the item size is not finalized until the animation completes.

You can either remove the animation, or trigger `layout` after the animation is completed.
