### ISSUE TITLE
Is that possible to disable auto-layout when some element with full-width is blocked on dragging

### ISSUE THREAD

**Issue by l2aelba** [metafizzy/packery#390]
Like **Tetris** but originTop mode.

![mzlvwjy68p](https://cloud.githubusercontent.com/assets/983458/16489448/e94b0e66-3ed5-11e6-82c5-3cd1906a71ad.gif)

- Any trick can I **prevent elements below the full-width going to top ?**
- If not possible. Any trick can I **lock (prevent auto-layout) when dragging ?**

**Why ?**
Bacause this is so bored to drag elements back to bottom. _(think if there is many elements)_

**Test case:** http://codepen.io/l2aelba/pen/akWkgO

Thanks for helping 👍

**Comment by desandro** [comment]
> Any trick can I prevent elements below the full-width going to top ?

You could use multiple packery instances, so that you can only drag items within the separated containers, but not between them.

> If not possible. Any trick can I lock (prevent auto-layout) when dragging ?

Sorry, no.

**Comment by l2aelba** [comment]
Thanks @desandro , There is not possible like `Origin : none` ? (no gravity)

**Comment by desandro** [comment]
You can disable Packery's drag behavior by not using `bindDraggabillyEvents` or `bindUIDraggableEvents`.
