### ISSUE TITLE
Force image dimensions in html

### ISSUE THREAD

**Issue by pliablepixels** [metafizzy/packery#391]
Hi there, I have a bit of a unique situation: I am using packery to lay out images that are constantly streamed as MJPEG from a NVR system (Camera surveillance). I display them using `img src` tags. 

The problem I am facing is that the server often streams empty MJPEGs and then corrects them with the right image later. This results in layouts messing up once in a while with packery. I use imagesLoaded to trigger a layout and due to this quirky behavior layouts occasionally mess up.

This is really a bug in the server - but its 3rd party.

I can fix this issue at my client end if I force specify the image width and height in html. I know the WxH for each camera image that is streamed. Packery however picks up w/h directly from the image source (trying to override with HTML `<img src=foo width="1024px" height="768px">` doesn't work. The question therefore is - is there any way (undocumented or otherwise) which I can use to specify an image wxh in HTML and have packery honor that ?

Thanks.

**Comment by desandro** [comment]
Thanks for reporting this issue. Setting size attributes in HTML is a good way to set image size before image loads. I'm surprised this technique doesn't work. Can you disable Packery and check that elements have correct height? The images might need `display: block`. Otherwise, you can set sizes of unloaded images using [padding-bottom hack](http://www.fredparke.com/blog/css-padding-trick-responsive-intrinsic-ratios), but this hack will have to be reset after image has loaded.

**Comment by pliablepixels** [comment]
Hi @desandro I set up a codepen - I was incorrect in saying "it doesn't work". Rather "it does't work correctly", at least from what I've done so far.

What I am doing is forcing both image size (to avoid the problem I discussed above) and using percent layout (I use it to increase/decrease image size)

http://codepen.io/pliablepixels/pen/qZyGPb

If you take out the forced img w/h in the attributes, it works fine

**Comment by desandro** [comment]
Thanks for that. You're setting the height and width in `style`, but you can set it with HTML attributes `height` and `width`. Then you can override these default sizes with CSS. See demo: http://codepen.io/desandro/pen/d4478e876c38a559a87507522a1fd9a2

**Comment by pliablepixels** [comment]
Ahhh thank you. The problem was with my grid-item img definition. I was using `max-width:100%` - changing to your setting makes overriding work well. Thank you again!

```
.grid-item img {
  display: block;
  width: 100%;
    height:auto;
  
}
```
