### ISSUE TITLE
How to preserve the html order of elements while dragging and dropping in v2.1.1?

### ISSUE THREAD

**Issue by srgsanky** [metafizzy/packery#392]
packery v1.4.2 preserves the html order of elements during drag and drop. What I mean is, when you drag a box (for e.g. http://codepen.io/anon/pen/dXKNwX?editors=0010) and drop it between 2 other boxes, the boxes following the dropped location move to the right, making room for the dropped box.

But with packery v2.1.1, the box(es) at the dropped location move to the bottom in order to make room for the dropped box. For e.g. http://codepen.io/anon/pen/OXEWAO?editors=0010

Is it possible to get the default behavior seen in v.1.4.2 while using v.2.1.1?

**Comment by desandro** [comment]
Thanks for submitting this request. We already have an issue opened for it. See #353
