### ISSUE TITLE
Can't turn off draggability?

### ISSUE THREAD

**Issue by jim-at-miramontes** [metafizzy/packery#394]
I may be dense, but I just can't figure out how to turn off draggability on a packery instance.

I can turn on draggability with:

    function enable_draggability() {
    	var grid = $('.item_list').packery();
    	grid.find('.item').each(function (i, gridItem) {
    		var draggie = new Draggabilly( gridItem );
    		grid.packery('bindDraggabillyEvents', draggie);
    	});
    }

but the following fails: draggie is undefined:

    function disable_draggability() {
    	var grid = $('.item_list').packery();
    	grid.find('.item').each(function (i, gridItem) {
    		var draggie = $(gridItem).data('draggabilly');
    		grid.packery('unbindDraggabillyEvents', draggie);
    	});
    }

Can anyone clarify what I'm doing wrong here?

**Comment by desandro** [comment]
I recommend using an array to keep track of Draggabilly instances. Then use [Draggabilly's `disable` and `enable` methods](http://draggabilly.desandro.com/#methods). See demo http://codepen.io/desandro/pen/vKjAPE

``` js
var $grid = $('.grid').packery({
});

// collection of Draggabillies
var draggies = [];
var isDrag = false;

// make all grid-items draggable
$grid.find('.grid-item').each( function( i, gridItem ) {
  var draggie = new Draggabilly( gridItem );
  draggies.push( draggie );
  // bind drag events to Packery
  $grid.packery( 'bindDraggabillyEvents', draggie );
});

$('.toggle-drag-button').on( 'click', function() {
  var method = isDrag ? 'disable' : 'enable';
  draggies.forEach( function( draggie ) {
    draggie[ method ]();
  });
  // switch flag
  isDrag = !isDrag;
});

```

**Comment by jim-at-miramontes** [comment]
Good suggestion; thanks!

**Comment by rkbansal** [comment]
Nice explanation but why it is blocking scrolling event on disable?
