### ISSUE TITLE
serialize option for the items? 

### ISSUE THREAD

**Issue by neuropass** [metafizzy/packery#397]
Is there a way to "serialize" the items?

for example:
https://api.jqueryui.com/sortable/#method-serialize

I think in this case this option would be perfect to be used with:

https://github.com/metafizzy/packery/issues/348

so you can save the order of the items and reload them to the last saved position on page load for example... 

The idea behind all of this is to get rid of  jQueryUI and use Packery instead.

EDIT: Just found this as well:
https://github.com/metafizzy/packery/issues/337

More complicated but I think "serialize" + "pack items horizontally" would be simpler to execute at least in theory. I would like to know your thoughts about this @desandro

**Comment by desandro** [comment]
Thanks for this issue. As you mention, I think what you're asking for could be delivered as one feature. See https://github.com/metafizzy/packery/issues/337#issuecomment-187306540

In the short term, if you need to serialize items, you can do so in your own code with [`getItemElements`](http://packery.metafizzy.co/methods.html#getitemelements).

Horizontal packing is really Packery v1 packing behavior. I'm evaluating adding this behavior back as well. See #353
