### ISSUE TITLE
Item order changes layout

### ISSUE THREAD

**Issue by fatk** [metafizzy/packery#399]
Hi,

I'm having difficulties understanding what's going on:

I've created 2 pens, the only thing that changes is the order of 1 HTML elements, yet in one case Packery leaves out a lot of blanks and in the other it packs everything as it should.

1st Pen: http://codepen.io/fatk/pen/oLRVKL
2nd Pen: http://codepen.io/fatk/pen/VjORom

I've been having this issue on a website i'm currently developing.

Thanks.

**Comment by desandro** [comment]
Thanks for reporting this issue. This behavior is intended. Packery will not re-sort the order of the items to achieve the tightest packed layout.

**Comment by fatk** [comment]
I'm sorry, what do you mean by re-sort?

I thought that was the point of using packery... I'm confused now, i bought a dev licence on that promise. Is there something I missed?

Do you have an idea on how to make this happen?

Thanks!

**Comment by desandro** [comment]
Packery does not re-sort the order of items to produce the most efficiently packed possible layout. It does not re-sort the order of the items in Pen 1 to produce the better packed Pen 2.

What Packery does do is fill gaps if a subsequent item can fit in it. Its layout algorithm goes item by item to find the best place to pack it.

We can offer refunds if you are unhappy with your purchase.

**Comment by fatk** [comment]
This is where i stop following you, when packery packs elements, it moves them arround and sometimes puts them in a very different order than the HTML order. Given that fact, i don't understand why the order of the HTML element matter. To me, the same elements should give the same layout no matter the HTML order.

Can you point me to a possible solution for this?

Thanks

**Comment by fatk** [comment]
Ok thanks...
