### ISSUE TITLE
Save/Restore dragged tiles with Gutter and fluid layout.

### ISSUE THREAD

**Issue by ashubham** [metafizzy/packery#401]
@desandro So the solution mentioned in #337 seems to fail, when there is a gutter with %age position. http://codepen.io/anon/pen/XKLWJY

Try, make the screen small, drag position and then make the screen bigger and refresh, In some configurations one can find that the positions are now staggered. 

The percentage position of the items is not maintained with screen size. There are slight rounding errors like with a gutter of 1%, two column 49.5% items should be, `left: 0%` and `left:50.5%` respectively. But its like `left:0%` and `left:50.348%` or something similar depending on the screensize.

**Comment by desandro** [comment]
Thanks for reporting this issue. The code in #337 is still experimental. I'll add your comment to that issue so we can track everything there.
