### ISSUE TITLE
Packery layout is not working as expected in meteor with react

### ISSUE THREAD

**Issue by deepupathak** [metafizzy/packery#402]
I am using packery layout for layouting the several items. Its working fine in initial mode, but when I create new item, then that newly created item is overlap with the first item, and when I refresh the page, then its working fine.<br>
Here is the code sample I am using while an item is rendered ..<br>
```
   componentDidMount(){        
        $('#packery-layout').packery({
            itemSelector: '.item',
            gutter: 10
        });
    }
    componentDidUpdate(){
        $('#packery-layout').packery({
            itemSelector: '.item',
            gutter: 10
        });
    }
```
what I want is that, when I create a new design, then newly created design should not be overlapped with the first item.<br>
Any clue/solution for this issue ?<br>
Thanks.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).
