### ISSUE TITLE
Newly created item is overlapped with the first item

### ISSUE THREAD

**Issue by divyanshupathak** [metafizzy/packery#403]
Hello, Currently I am using metafizzy/packery package for layouting items. In my code, There are a parent component (SubscribedDesignsList) and there are two child of this component (NewDesignCard and SubscriptionItem).

Here is the code sample of parent component (SubscribedDesignsList)-

```
componentDidMount(){
    $('.grid').imagesLoaded(function () {
        $('.grid').packery({
            itemSelector: '.item',
            gutter: 10
        });
    });
}
render(){
    return(
        <div className="grid col-centered" id="packery-layout">
            <NewDesignCard checkState={that.checkState.bind(that)}  />
            {   this.props.Ready?this.props.items?
                this.props.items.map(function(item){
                    return <SubscriptionItem />
                }):'':<Loading />
            }
        </div>
    )
}
```

Here is the code sample of child component (NewDesignCard)-

```
componentDidUpdate(){
    $('.grid').imagesLoaded(function () {
        // images have loaded
        // Use the Packery jQuery plugin
        $('.grid').packery({
            // options
            itemSelector: '.item',
            gutter: 10
        });
    }); 
}
```

Here is the code sample of child component (SubscriptionItem)-

```
componentDidUpdate(){
    $('#packery-layout').packery({
        itemSelector: '.item',
        gutter: 10
    });
}
```

When I create new item, then that newly created item is overlapped with the first item. Please advise how to place new item at required position.

Any clue/solution for this issue ?
Thanks.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).

**Comment by divyanshupathak** [comment]
Sorry, My fault. In the end I successfully solved the issue and items are rendered as expected.
Now closing this issue.
