### ISSUE TITLE
How to resize in Vanilla JS

### ISSUE THREAD

**Issue by agomezs** [metafizzy/packery#404]
With Jquery I can do resize pretty easy [https://codepen.io/desandro/pen/cyvra](https://codepen.io/desandro/pen/cyvra).

But how to use it with Draggabilly in [Vanilla JS](https://codepen.io/desandro/pen/cyvra)?

**Comment by desandro** [comment]
Draggabilly does dragging, not resizing. If you want to resize the element with vanilla JS, you'll have to use another library.
