### ISSUE TITLE
Set direction of expanding element

### ISSUE THREAD

**Issue by TMcLoone** [metafizzy/packery#406]
I'm trying to figure out a way to set the direction that the element expands, for example if you click on a far right element [here](http://codepen.io/desandro/pen/paFEH), it expands from right to left. 
I'm wondering what is causing it to do that? Is it something to do with the fit method or the functions that are animating it? Any help is greatly appreciated!!

**Comment by desandro** [comment]
`fit` works by finding the closest position to the item's current position (if no specific position has been passed in) that will fill inside the container. So items on the right appear to expand to the left, but that's because they cannot expand to the right.

**Comment by TMcLoone** [comment]
Ok cool. Do you think there could be a way of setting which direction they open? 

Thanks,
Tim

**Comment by desandro** [comment]
You can set the direction by setting the [position in `fit`](http://packery.metafizzy.co/methods.html#fit).

``` js
// jQuery
$container.packery( 'fit', element, x, y )
// vanilla JS
pckry.fit( element, x, y )
```

See demo http://codepen.io/desandro/pen/fguJH
