### ISSUE TITLE
View Model change using Knockout js, layout and Draggable feature not working

### ISSUE THREAD

**Issue by sri-aleti** [metafizzy/packery#409]
On View Model change using Knockout js, layout and draggable feature not working.

It is working fine on initial load:
When the page is loaded with dynamic 'div' using  , where 'widgets' is Observable array and grid is defined in document.ready()
//code: START
     var $grid = $('.grid').packery({
            columnWidth: '.grid-sizer',
            itemSelector: '.grid-item',
            gutter: 0
        });
        var $griditems = $grid.find('.grid-item').draggable();
        $grid.packery('bindUIDraggableEvents', $griditems);
//code: End

But when you update your View Model i mean the observable array which binds data the div, the layout and draggable is feature is not working.

Is there any way to define packery outside of document and ready and call it to refresh it when viewmodel updated? Can anyone please help ASAP if you have faced similar issue...

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).
