### ISSUE TITLE
How to use reloadItems

### ISSUE THREAD

**Issue by ghost** [metafizzy/packery#41]
Hello,

Just wondering how I can use the reloadItems method? I am trying to get my items to readjust after a user clicks on a link, or after another function finishes.

This is what I currently have: http://jsfiddle.net/trewknowledge/Bp3Gr/

Any ideas?

**Comment by prajapati-gautam** [comment]
@desandro 
I have an issue with dragged items blanks fill with another element and I want to stop that.
there is any way to stop that.

like not using auto layout
I tried with stamp element when loading and then unstamp after setting on position.
@desandro you are doing awesome on that can you help me out with this problem.
thank for the awesome plugin.
