### ISSUE TITLE
Images not fully shown first load.

### ISSUE THREAD

**Issue by fourroses666** [metafizzy/packery#412]
![loaded](https://cloud.githubusercontent.com/assets/523389/19539051/9a8ff910-9657-11e6-9ce1-7659f99449b6.png)

and:

![height](https://cloud.githubusercontent.com/assets/523389/19539054/a0335858-9657-11e6-8a32-63d7f71aee89.png)

---
After refresh images are visible. First time height 5px.
Any idea how to fix this?

```
<script src="/js/imagesloaded.pkgd.js"></script>
<script src="/js/packery.pkgd.js"></script>
<script>
	var grid = document.querySelector('.grid');
	var pckry = new Packery(grid, { itemSelector: '.grid-item' });
</script>
```

Also tried:
```
 $('.grid').imagesLoaded(function () {
        $('.grid').packery({	
```

I have tried docReady and remove webfonts, load as last script below </ body> but no luck.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).

**Comment by fourroses666** [comment]
Oke, so I tried to make a jsfiddle but somehow it doesn't work. Sorry.

I can give some more info about the issue;

Started to do some changes, removing some other scripts etc;
I use FF on my iMac but noticed on Safari the issue was there every time even after reload! 
Then used the script external that was solved for Safari, but only after the first reload, after the page is being cached, just like Firefox.

Looks like the script needed to be triggered again. Because after resizing the browser its starting to show the full images again and there where no issues anymore.

BUT somehow I don't have issues a.t.m. anymore even when using internal script and this code:

```
	var $grid = $('.grid').packery({});
	$grid.imagesLoaded().progress( function() {
	  $grid.packery();
	});
```

But still I need to keep testing, pritty sure it didn't work at some time, maybe the shared hosting got faster or every page is already being cached, really have no clue if this will keep working. 

Will report back later..

**Comment by fourroses666** [comment]
so far so good, i think its fixed

**Comment by PrestaShark** [comment]
Sorry for bothering but i have the same issue :(
Banner module show messed images one on another on the first page load (hard refresh CTRL+F5) and with another soft refresh CTRL+R all is good on position - just as above @fourroses666 case.

Initialize with jQuery and HTML gives the same result.
It seams FF related and Chrome. IE11 works well! Windows 8.1 64bit.

Help! Need to finish my project ASAP and buy commercial licence for Packery :(


@fourroses666 how did you fixed it?

**Comment by fourroses666** [comment]
Rename .htaccess in /cache and / cache/images might help for now

**Comment by fourroses666** [comment]
Oh sorry lol, this is a whole different story. I thought you where talking about something different. I have fixed it but because I'm on mobile I can't help right now.

**Comment by PrestaShark** [comment]
Ha!! Ok 👍 :)
Thanks for hint! :)

**Comment by fourroses666** [comment]
@PrestaShark 

This worked for me. 

```
<script src="/assets/templates/site/js/imagesloaded.pkgd.js" type="text/javascript"></script>
<script src="/assets/templates/site/js/packery.pkgd.js" type="text/javascript"></script>
<script>	
	var $grid = $('.grid').packery({});
	$grid.imagesLoaded().progress( function() {
	  $grid.packery();
	});
</script>	
```

**Comment by muneebbug** [comment]
This is My solution!

```
<script src="/assets/templates/site/js/imagesloaded.pkgd.min.js" type="text/javascript"></script>
<script src="/assets/templates/site/js/packery.pkgd.min.js" type="text/javascript"></script>
<script>
      var $Pack= $('.packery').packery({});
           $Pack.imagesLoaded().progress( function() {
	   $Pack.packery();
	    });

</script>

```
