### ISSUE TITLE
Packery items overlapping on mobile

### ISSUE THREAD

**Issue by Dynz** [metafizzy/packery#413]
Hi All,

I have an issue on my mobile site. The packery items are overlapping on the mobile version of the site. The container height appears to be smaller than the contents. If I change the view from portrait to landscape mode on my phone or vice versa the items display correctly. The issue is on the first load.

Here is the site: http://www.kadealo.com
Mobile version: http://m.kadealo.com

All ideas and suggestions welcome.

Thank you

**Comment by desandro** [comment]
Looks like this is  your Packery domain code

``` js
	var container = document.querySelector('.packery');
	var pckry = new Packery( container);
  
	$('.item img').each(function(){
		$(this).on('load', function(){
			var pckry = new Packery( container);
		});
	});
	
	$("img.lazy").lazyload();
```

This initializes a new Packery instance every time an image is loaded. Instead, you want to trigger [layout](http://packery.metafizzy.co/methods.html#layout-packery). Try this code:

``` js
var container = document.querySelector('.packery');
var pckry = new Packery( container);

$('.item img').on( 'load', function() {
  pckry.layout();
});
```

**Comment by Dynz** [comment]
Hi David, 

Thanks for feedback.

I have implemented the code and still see the issue. I noticed the following error:

TypeError: $(...).on is not a function [Learn More]catalogues.js:36:2

The error links to this line: "$('.item img').on( 'load', function()"

Any further ideas?

Thanks

**Comment by desandro** [comment]
Sorry, but I am not able to personally debug your site.
