### ISSUE TITLE
Prepending an item moving only the first column down?

### ISSUE THREAD

**Issue by oldtinroof** [metafizzy/packery#415]
Hi,

Is there a way to prepend a new item to a grid without forcing a horizontal re-layout?

I'd like to add a new item in the top left, and just have the first column move down if possible.  I've tried combinations of packery.addItems() and packery.shiftLayout(), but can't seem to work it out.  Is there something that prepended is doing that forces the horizontal shift?

I would put together a test case, but it's not really a bug - I was playing with a codepen: http://codepen.io/oldtinroof/pen/eBzPKQ but that's pretty much just showing what I don't want to happen :)

Any help would be much appreciated!

**Comment by desandro** [comment]
Yes, we can do this, but it will require some hacking. Add this code:

``` js
Packery.prototype.fitPrepended = function( elems, x, y ) {
  var items = this._itemize( elems );
  if ( !items.length ) {
    return;
  }
  var item = items[0];
  // add item to beginning of collection
  this.items.unshift( items[0] );
  // fit item
  this.fit( item.element, x, y );
}
```

You can then use a `fitPrepended` method just like you would [the `fit` method](http://packery.metafizzy.co/methods.html#fit)

``` js
  // prepend element to container
  $grid.prepend( $item )
    // add and lay out newly prepended element
    .packery( 'fitPrepended', $item, 0, 0 );
```

See demo http://codepen.io/desandro/pen/mOOrzQ

This will only work with single elements, because `fit` works with single elements.

**Comment by oldtinroof** [comment]
Brilliant, that's exactly what I was looking for - thank you Desandro!
