### ISSUE TITLE
Console Errors on bower install.

### ISSUE THREAD

**Issue by opemily** [metafizzy/packery#416]
I'm getting the following errors in my console after installing Packery
[console](https://cloud.githubusercontent.com/assets/12058589/20637975/17a135c4-b366-11e6-9071-e845981fb9eb.jpeg)

I did the bower.json override  but I'm still getting those errors in the console. Will Packery still work?

**Comment by desandro** [comment]
What module loader (Wiredep, Browserify, etc) are you using with Bower?

**Comment by opemily** [comment]
Gulp and Browsersync

**Comment by opemily** [comment]
figured it out. Added this to bower.json file:



`"packery": {
      "main": [
        "js/rect.js",
        "js/packer.js",
        "js/item.js",
        "js/packery.js"
      ]
    },
    
    "outlayer": {
      "main": [
        "item.js",
        "outlayer.js"
    ]`
