### ISSUE TITLE
Packery and Imagesloaded using WordPress and Webpack

### ISSUE THREAD

**Issue by JakeHenshall** [metafizzy/packery#417]
Hi,

I'm trying to include Packery with WordPress using Webpack but it doesn't seem to be working 

http://stackoverflow.com/questions/40856052/packery-and-imagesloaded-using-wordpress-and-webpack

Any help would be much appreciated.

Thanks Jake.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).
