### ISSUE TITLE
After dragging, the 2 involved columns auto-swap positions

### ISSUE THREAD

**Issue by fohoco** [metafizzy/packery#418]
Sorry that I am not a developer so I don't know what a reduced test case is, I am asking this on behalf of my hired developer... hope we can still find a solution:

After dragging a photo say from column A to B, the 2 columns swap positions.... see if you can see this screen recording: https://www.dropbox.com/s/yd4c694lxezgisr/Bugs_ManageGallery_PhotoRearrange.mov?dl=0

Thank you for your time!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? Your developer should be able to put one together. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).
