### ISSUE TITLE
percentPosition

### ISSUE THREAD

**Issue by getprice** [metafizzy/packery#419]
Hi
i have an issue when using the percentPosition
it seems that only the left position is in percents but the top position is in pixels
is there an option to make both positions to be in percents?

thank you

**Comment by desandro** [comment]
Sorry, no. See desandro/masonry#916

> Masonry cannot use percent values for top because it sets the height of the container itself. top values are determined by the height of the container. So it would induce a circular logic. Sorry, Masonry does not support this feature.

**Comment by getprice** [comment]
thank you for the answer
