### ISSUE TITLE
Elements not aligning correctly with responsive layou

### ISSUE THREAD

**Issue by jurgen-ll** [metafizzy/packery#42]
On init the images won't align at all, after resize they do.
But in most cases the elements are not aligned correctly. See attached screenshots. I've tried a lot to fix this, but haven't been able to unfortunately. Please send me your IP so I can give you access if you'd like to see it working, it's a closed dev env.

Used JS code:
  $usersPack = $('#users-mason').packery({
    itemSelector: '.user',
    gutter: 0,
    isInitLayout: true,
    isResizeBound: true
  });

![schermafbeelding 2013-05-22 om 17 56 46](https://f.cloud.github.com/assets/4501146/549397/6a5c125a-c2f8-11e2-9ebb-459ea1fb13dc.png)
![schermafbeelding 2013-05-22 om 17 57 54](https://f.cloud.github.com/assets/4501146/549398/6a5e9d90-c2f8-11e2-9eb6-5eee1fa54366.png)

**Comment by desandro** [comment]
[`v1.3.2`](https://github.com/metafizzy/packery/releases/tag/v1.3.2) has been released with several improvements to resolve responsive sizing across browsers. [Please try it out](http://packery.metafizzy.co/) and let me know if you see any improvements with your implementations.

**Comment by desandro** [comment]
Closing here as fixed. Please open a new issue if you run into trouble.

**Comment by englishextra** [comment]
I try to always use msnry.layout() / pckry.layout() with setTimeout/setInterval (depending on your logic) right after the msnry/pckry have been initialized. Yes, init and then trigger .layout() some 100 ms after. That way your vertical gaps will be realigned/recalculated.

As for 1px gaps, avoid 0.33333 percentages. use plain 0.25 0.5 etc.
