### ISSUE TITLE
[How To] Horizontal layout fill in empty cell 

### ISSUE THREAD

**Issue by Ajeey** [metafizzy/packery#422]
So my initial layout is in the form of - 

1 | 3 | 5
2 | 4 | 6

as I have set `horizontal: true`

Now when I drag and drop 6 on 3, my layout become 

1 | 6 | 3 | 5
2 | 4

But actually I want it to fill up the second row. i.e

1 | 6 | 3
2 | 4 | 5

Please suggest me on how do I achieve this behaviour?

**Test case:** http://codepen.io/ajey/pen/WRebPE

**Comment by desandro** [comment]
Sounds like you're asking for Packery v1 behavior. See #353

**Comment by Ajeey** [comment]
Can you point me to the older version of the library?

**Comment by desandro** [comment]
http://packery.metafizzy.co/v1
