### ISSUE TITLE
Unable to initalize with JS/jQuery fine with HTML

### ISSUE THREAD

**Issue by perpixon** [metafizzy/packery#425]
Hi,
I must be misunderstanding on how the JS and jquery programming works. I have created a responsive grid which initalizes with HTML 
<div class="grid" data-packery='{ "itemSelector": ".grid-item", "gutter": 0 }'>
and it works amazingly well, apart form i need to add imageloader to get the differing image sizes to fit correctly on first load. The problem is i just cant seem to activate packery when using JS or jquery. I have tested the page with a simple JS and that runs ok (so i know js will run and i am activating it ok). I think i must need to change to match some of the names in the programming below, however i don't know what they need to be or how to find out. Do you have a simple explanation as to what each part of the programming is and how it is derived so i can work out what i need to name items?  Or is there a way to add imageloader via HTML?

var elem = document.querySelector('.grid');
var pckry = new Packery( elem, {
  // options
  itemSelector: '.grid-item',
  gutter: 10
});

// element argument can be a selector string
//   for an individual element
var pckry = new Packery( '.grid', {
  // options
});

Sorry for what i am sure is a very basic and probably stupid question, as i am sure you can tell i am very new to programming.

Many thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).

**Comment by perpixon** [comment]
Hi,
I have done some more testing etc.
This is really odd. using one of the existing codepen examples e.g. http://codepen.io/desandro/pen/pgVEzb (which obviously works). However when i copy the exact code to my site i cant get Packery to initialize using jQurey or js however it works fine using the html code to initialize, apart form i need to have imagesloaded. I have changed in codepen all of the css, js files and code to run directly from my site and that's OK. Is there any known reasons as to why i might be unable to activate packery via jqurey etc. 

**TEST PAGE HTML**

<!DOCTYPE html>

```
<html>
<head>
<title>Your Title Here</title>
<link href="http://mytestdomain.com/packery.css" type="text/css" rel="stylesheet">
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="http://mytestdomain.com/js/packery/packery.pkgd.min.js"></script>
<script type="text/javascript" src=http://mytestdomain.com/js/packery/imagesloaded.pkgd.min.js"></script>
<script type="text/javascript" src="http://mytestdomain.com/js/packery/initialize_packery_query.js"></script>
</head>
<body>
<h1>Packery - imagesLoaded callback, vanilla JS</h1>
<div class="grid">
  <div class="grid-item">
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/orange-tree.jpg" />
  </div>
  <div class="grid-item">
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/submerged.jpg" />
  </div>
  <div class="grid-item">
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/look-out.jpg" />
  </div>
  <div class="grid-item">
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/one-world-trade.jpg" />
  </div>
  <div class="grid-item">
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/drizzle.jpg" />
  </div>
  <div class="grid-item">
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/cat-nose.jpg" />
  </div>
  <div class="grid-item">
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/contrail.jpg" />
  </div>
  <div class="grid-item">
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/golden-hour.jpg" />
  </div>
  <div class="grid-item">
    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/flight-formation.jpg" />
  </div>
</div>
</body>

```

**TEST PAGE CSS**

```
* { box-sizing: border-box; }

/* force scrollbar */
html { overflow-y: scroll; }

body { font-family: sans-serif; }

/* ---- grid ---- */

.grid {
  background: #ddd;
}

/* clear fix */
.grid:after {
  content: '';
  display: block;
  clear: both;
}

/* ---- .grid-item ---- */

.grid-item {
  width: 33.333%;
}

.grid-item {
  float: left;
}

.grid-item img {
  display: block;
  max-width: 100%;
}
```

**MY JS INITIALIZE FILE**

```
// external js: packery.pkgd.js, imagesloaded.pkgd.js

var $grid = $('.grid').imagesLoaded( function() {
  // init Packery after all images have loaded
  $grid.packery({
    itemSelector: '.grid-item',
    percentPosition: true
  });
});  
```

I do not what my domain address to be public. I can PM you the page link?

Thank you so much. I just can't understand as to why i cant get it to work.

**Comment by perpixon** [comment]
Working now.
I need to add and extra }); on the end and add a no conflict.

```
jQuery(document).ready(function() {
    var $grid = jQuery('.grid').imagesLoaded( function() {

        // init Packery after all images have loaded
        $grid.packery({
            itemSelector: '.grid-item',
            percentPosition: true
        });
    });
});
```
