### ISSUE TITLE
Animating Responsive Item Size Issue

### ISSUE THREAD

**Issue by KingBier** [metafizzy/packery#426]
Hello,

I wanted to use the following example to resize my items on a masonry layout.
http://codepen.io/desandro/pen/jGJKL

But as I played around with the example, I noticed, that everytime I click an item (that is located at the right side of the grid) to shrink it, it will **replace** it **to the wrong place**. It always shrinks to the left upper side.
Then the **whole layout gets mixed up** and looks bad.

How can I layout it properly and place the shrunk item onto the place where it was before (like it works with every other animating size example)??

_**EDIT:**_
I found a partly solution (fit in previous position):
http://codepen.io/desandro/pen/WxjJJW/

Is there a possibility to get the startingPosition (original order) instead of previousPosition?
Cause sometimes, the layout gets mixed up again (when more than one item is enlarged).

Or is there a combination with the sort-Algorithm of Isotope to sort the items when they are shrinking?

Thanks in advance.

**Comment by desandro** [comment]
Thanks for submitting this issue.

> Is there a possibility to get the startingPosition (original order) instead of previousPosition?

Perhaps. You can give it a shot. But my hunch is that you'll run into difficulty because if two cells are enlarged at the same time, that throws off the layout. If only one cell is open at a time, it could work.

> Or is there a combination with the sort-Algorithm of Isotope to sort the items when they are shrinking?

You can give [packery layout mode for Isotope a try](http://isotope.metafizzy.co/layout-modes/packery.html)

**Comment by zerocoolElite** [comment]
@desandro does packery still invoke proto.layout() on resize event even the main container(<div>) is hidden?

**Comment by desandro** [comment]
@zerocoolElite Yes.
