### ISSUE TITLE
After Append, then Drag, layout isn't working properly.

### ISSUE THREAD

**Issue by lunarose23** [metafizzy/packery#427]
I want to append an item, then drag an item, and then have dragged item go to where I place it, shifting the current items down if need be.  Right now after I drag the whole thing it does a weird layout with lots of space at the top. 

I can fix it if I destroy the packery instance then re-init the instance, but I don't want it to relayout every time I append. I just want it to append. 

**Reduced Test case:** http://codepen.io/lunarose23/pen/xgpjev?editors=0010

**Comment by desandro** [comment]
Thanks for putting this demo together. I'm sorry to say. Packery does not support dragging from multiple containers. This has been a hotly requested feature. See #27 

I'm closing this issue as a duplicate. Let's keep discussion there.
