### ISSUE TITLE
Can't drop elements freely on a grid

### ISSUE THREAD

**Issue by coorasse** [metafizzy/packery#428]
I'd like to be able to position an element next to another even if there is no other element on the top of it.
http://codepen.io/anon/pen/RKvNGX

I can't place elements like in the picture below:
<img width="554" alt="screen shot 2017-02-13 at 19 13 43" src="https://cloud.githubusercontent.com/assets/1319150/22896505/ae76837a-f220-11e6-83df-8078d1794999.png">

I know I can set the `horizontal` option but this doesn't solve my issue since I'm not free to position elements vertically anymore (can't for example place an element between other two)

**Comment by desandro** [comment]
Sorry, Packery does not support this feature. You're better off using [jQuery UI Draggable](http://jqueryui.com/draggable/)
