### ISSUE TITLE
Compatibility issue with Draggabilly 2.1.1?

### ISSUE THREAD

**Issue by Regisc** [metafizzy/packery#429]
Hello, using:
- Packery v2.1.1
- Draggabilly v2.1.1

And the code in the test case, some error is thrown when a drag&drop is made: 

```
packery.pkgd.js:2824 Uncaught TypeError: Cannot read property 'x' of undefined
    at HTMLDivElement.dragMove (packery.pkgd.js:2824)
    at HTMLDivElement.dispatch (jquery.js:4430)
    at HTMLDivElement.r.handle (jquery.js:4116)
    at Object.trigger (jquery.js:4345)
    at HTMLDivElement.<anonymous> (jquery.js:4896)
    at Function.each (jquery.js:374)
    at n.fn.init.each (jquery.js:139)
    at n.fn.init.trigger (jquery.js:4895)
    at Draggabilly.proto.dispatchEvent (draggabilly.pkgd.js:1235)
    at Draggabilly.proto.dragMove (draggabilly.pkgd.js:1410)
```

**Test case:** http://codepen.io/anon/pen/LWdoaO

<hr/>

I was able to fix the issue, using this drag&drop handler:

```javascript
Packery.prototype._bindDraggabillyEvents = function(draggie, method) {
    var _this = this;
    draggie[ method ]( 'dragStart', function() {
        var draggabilly = $(this).data('draggabilly');
        _this.itemDragStart( draggabilly.element );
    });
    draggie[ method ]( 'dragMove', function() {
        var draggabilly = $(this).data('draggabilly');
        _this.itemDragMove( draggabilly.element, draggabilly.position.x, draggabilly.position.y );
    });
    draggie[ method ]( 'dragEnd', function() {
        var draggabilly = $(this).data('draggabilly');
        _this.itemDragEnd( draggabilly.element );
    });
};
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like you're trying to use both Packery and Draggabilly with the jQuery plugin. While this works to initialize both, in order to hook these behaviors together, you'll need to access the Draggabilly instances — as you've done in your proposed code.

Rather than add this additional code, [I recommend you use the code I put together in the docs](http://packery.metafizzy.co/draggable.html):

``` js
```

**Comment by Regisc** [comment]
Thanks for your reply, I will try your recommended code tomorrow.

**Comment by Regisc** [comment]
Using your code did work. Thanks for your time

=> closing (not an issue)
