### ISSUE TITLE
Problem with height not updating in responsive layout with images

### ISSUE THREAD

**Issue by sasoriza** [metafizzy/packery#430]
I am trying to set up a layout with images that need to resize properly depending on viewport size while no item should overlap the the bottom.
While this is generally working, I am having problems with the height of the items not adjusting, instead the height defined for .grid-sizer / .grid-item will always be used. I have compared my version to the rowHeight, element sizing example (http://codepen.io/desandro/pen/dElba) and have no idea why this isn't working in my case. ~~What am I doing wrong?~~

**Edit: I see now why this problem only occurs in my version - the items in the example have a fixed height while the ones in my layout have a dynamic height. How can I achieve the layout I am trying to accomplish?**

**Test case:** http://codepen.io/vit6/pen/gmzNGE
(Resize viewport to see wrong behavior)

**Comment by desandro** [comment]
This is a bit of a tricky one. While `width` can be fluid and use percent values, `height` cannot, as its based on the height of the container. The height of the container is dynamically set by Packery ... which needs to measure the height of items.

My recommendation is to remove both `columnWidth` and `rowHeight` and see how things get laid out. Also remove height values in CSS and let the images provide the height. See demo http://codepen.io/desandro/pen/0e8fd305a4311d5730d2e498cc556d07/

**Comment by sasoriza** [comment]
Thanks for your reply! While your solution was almost working, I came up with something that behaves exactly as I wanted it to: http://codepen.io/vit6/pen/ryKGJX
