### ISSUE TITLE
Draggable packery items on bootstrap sticking to each other (No gutter) on first page load

### ISSUE THREAD

**Issue by shaani88** [metafizzy/packery#431]
Hi,

My draggable packery grid-items are sticking to each other with no gutter at the first page load. It becomes ok when i click and drag a grid item. What may be causing the issue?I am using bootstrap columns. My code is as follows:

    $('document').ready(function() {
        var $grid = $('.grid').packery({
          itemSelector: '.grid-item',
            percentPosition: true,
            isResizeBound: true
        });
           // make all grid-items draggable
        $grid.find('.grid-item').each( function( i, panel ) {
              var draggie = new Draggabilly( panel );
              // bind drag events to Packery
              $grid.packery( 'bindDraggabillyEvents', draggie );
            
            });

            $grid.on( 'layoutComplete');
            $grid.on( 'dragItemPositioned');
            
           
             $('body').on( 'click', '#panel1', function( event ) {
            //$('#panel1').click(function() {
            if (this.checked) {
                var $items = $('<div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 grid-item"><div class="panel"><div class="rum-chart-header rum-v-align-middle"><div class="meta-cell col-xs-12 col-sm-8 col-md-8 col-lg-8"><h3 class="rum-h3">New Panel</h3></div><div class="meta-cell col-xs-12 col-sm-4 col-md-4 col-lg-4"><button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button></div></div><div class="panel-body"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-4"><div class="testBlock"></div></div></div></div></div>');
                 // prepend items to grid
                $grid.prepend( $items )
            // add and lay out newly prepended items
            .packery( 'prepended', $items );
                var draggie2 = new Draggabilly('.grid-item');
                $grid.packery( 'bindDraggabillyEvents', draggie2 );
                $draggie2.remove();
            }   
        });

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).

**Comment by shaani88** [comment]
Hi Desandro, I cannot recreate the issue in codepen. Is it possible if I email the code to you?

**Comment by desandro** [comment]
Sorry, **reduced test case** is the best way to debug an issue.

**Comment by shaani88** [comment]
The issue is I am using d3 charts and i have a bootstrap layout where i am displaying d3 charts in 2 columns and many rows. In the page reload, the charts overlap on to each other. This maybe because the charts are of different heights. Any suggestions how i can fix it? Because i have to load d3 charts into panels, it is hard for me to show a reduced test case.

**Comment by shaani88** [comment]
This is fixed. I put grid.packery() where i am returning charts. then the overlapping is resolved. thanks.
