### ISSUE TITLE
Possible to bin pack the drop placeholder?

### ISSUE THREAD

**Issue by Kilian** [metafizzy/packery#433]
When using drag and drop in Packery and showing the drop placeholder, it shows the drop placeholder in the grid. However if you call Packery (to bin-pack the layout) after dropping an element, it could be that the element moves to a different place than the drop placeholder indicated. 

This makes sense (the drag-and-drop, and the subsequent bin-packing are two different things), but is difficult to explain to end users. Would it be possible to show the drop placeholder in a bin-packed place during dragging?

**Comment by desandro** [comment]
Sounds like you're asking for #353. Add your 👍  there!

**Comment by Kilian** [comment]
Not exactly. There is a "hidden" requirement: We want reproducible layouts, so we need to bin pack after drag-and-drop to make sure the layout is the same as a "fresh load". 

I prefer the Packery 2 packing method. However during dragging the preview shows up at it's "naive" position (e.g. a position in the current column) but not necessarily one the widget would end up eventually after bin-packing. 

This works when you're at the top of columns, (preview position == position where your item will end up) But if you're at bottom of a column, an item's preview is still in the current column whilst subsequent packing will move the actual item more to the left. 

I would like the behaviour of Packery 2, but if I for example drag a widget in the lowest "row", I would like the preview to show up at the left most position because that's where the widget will eventually end up at in order to have a reproducible layout.

**Comment by desandro** [comment]
Ah gotcha. What you're asking for would be difficult to deliver. When dragging with packery v2, it uses a 'shift pack' algorithm, that keeps other items in their current horizontal position, but changes vertical position. The bin pack algorithm is different, as it changes both horizontal and vertical position. What you're asking for is like a two-fold algorithm that does the shift pack, then bin pack. It may produce better results in theory, but I don't think its worth the extra complexity to implement.

**Comment by Kilian** [comment]
I figured as much, and I'm inclined to agree with your worth/complexity assessment. If we switch my question around: what would it take to make the shift layout positions reproducible on "fresh load"?

**Comment by desandro** [comment]
Shift layout only works if there's a bin packed layout to start with. It requires a horizontal position. So you can't initialize Packery with a shift layout.
