### ISSUE TITLE
CDN compromised

### ISSUE THREAD

**Issue by santyanna** [metafizzy/packery#435]
Discovered our site was compromised due to using the following cdn link:

https ://unpkg.com/packery@2.1/dist/packery.pkgd.min.js

(broken for your protection!)

**Comment by efreila** [comment]
Any way to fix this issue as of now?

**Comment by santyanna** [comment]
unpkg confirmed it was an issue on their end that should be fixed but maybe consider alternatives?

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry about the interuption
