### ISSUE TITLE
Grid-item has incorrect height when a video element is served as content

### ISSUE THREAD

**Issue by OneTimeUser** [metafizzy/packery#438]
I'm testing using packery for three types of content within the grid-item class. It seems that text content and image content display correctly (i'm also using imagesLoaded for the images). But a video element (a very small mp4 video clip I'm self serving) seems to not show the proper height:

https://codepen.io/onetimeuser/pen/eWdKRj

I could set a height for the grid item with a video class but wanted to actually see if there were content restrictions for packery, specifically with video.  

Thanks.

**Comment by desandro** [comment]
Sounds like you're running into same kind of unloaded image issue, but with video.

Since you're using jQuery, you could use the `load` and video `loadeddata` events to check when the video loads and trigger layout.

``` js
  // trigger layout after any video loads
  $grid.find('video').each( function( i, vid ) {
    $(vid).on( 'load loadeddata', function() {
      $grid.packery();
    });
  });
```

See demo https://codepen.io/desandro/pen/6bf1d6bfdee0b80bf0102e78deee0c74/
