### ISSUE TITLE
Dealing with grid-items that grow in height?

### ISSUE THREAD

**Issue by nehero** [metafizzy/packery#439]
**Test case:** https://codepen.io/nehero/pen/BRZJXV

When having content that grows / shrinks the grid item, the grid container does not resize the height until the grid item is dragged and/or layout() is called. If you click the toggle button on the first grid item you can see how it now goes over the footer.

Is there any workaround for this? Calling `layout()` on packery is an option to re-calc the height of the grid but this will shift all of the grid items around if there is any blank-space (i.e if you were to put both items on the right if would shift one over to the left).

**Comment by desandro** [comment]
Sounds like [`shiftLayout`](http://packery.metafizzy.co/methods.html#shiftlayout) could be the solution for this issue:

> After an item has changed, shiftLayout will move items up and down to best fit the change. This maintains more order compared to using layout/.packery(), where item positions can be completely changed.

See demo https://codepen.io/desandro/pen/b4de90ff4b85a7a194c1189311e53d99/

**Comment by nehero** [comment]
`shiftLayout` ended up being an OK fix for now with the issue we're having. 

The solution is a little less than elegant as that you have to manually call that function in every situation where a grid item could grow in height.

I'm not sure of a native packery solution, but I'd be open to helping figure it out
