### ISSUE TITLE
Problems with Draggabilly with right to left

### ISSUE THREAD

**Issue by gilteitelbaum** [metafizzy/packery#440]
I am having a problem with Draggabilly when setting originLeft to false.   The test case below works perfectly when originLeft is true - but when originLeft is false the placement of the elements doesnt function smoothly at all.

**Test case:** http://codepen.io/GilTeitelbaum/pen/aWKJLv

**Comment by desandro** [comment]
Sorry to hear you're running into this issue. Yes this is a bug. I have another issue opened to track it. #244
