### ISSUE TITLE
Add resizable feature in pure vanilla javascript (without jQuery)

### ISSUE THREAD

**Issue by vlodko** [metafizzy/packery#441]
Draggabilly works very well!
I would like have same option for resizable tiles.
We don't have jQuery and don't want to add it to our app.

How is it possible to make tiles resizable without writing own solution?
Do you have any plans for implementing this feature?

Thanks in advance!

**Comment by desandro** [comment]
> How is it possible to make tiles resizable without writing own solution?

Neither Packery nor Draggabilly offer resizable behavior. You'll have to search for a separate vanilla JS solution

> Do you have any plans for implementing this feature?

Sorry, no. You may want to add it as request for [Metafizzy's next project](https://github.com/metafizzy/next-project/)

**Comment by vlodko** [comment]
@desandro I just posted a request on Metafizzy's side.

But this issue is still relevant. I'm hoping for your help on this in future.

**Comment by desandro** [comment]
Thank you for your submission. We'll track the request over at metafizzy/next-project#21
