### ISSUE TITLE
Getting the old and new indexes for the dragged element on dragItemPositioned

### ISSUE THREAD

**Issue by renatoslcdevshop** [metafizzy/packery#442]
I'm using vue, so I want to sync dom changes with data. Using dragItemPositioned, how can I get both the old and new indexes for the dragged element? Something like what jQueryUI sortable does with its `from` and `to` on the `stop` event.

I managed to get the old index by unsing a data attribute in the rendered list (data-item-id), but I'd rather not to modify the dom.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).
