### ISSUE TITLE
Item moves to the end of the list instead of up the list

### ISSUE THREAD

**Issue by renatoslcdevshop** [metafizzy/packery#444]
Hello,

When dropping an item, I expect the items positioned between its old and its new position to be sequentially reordered to make room. But what actually happens is that the item that was in the new position moves to the end of the list.

For instance, in the following test scenario, the items should simply switch position. Instead, one of them moves to the end of the list, leaving a blank space and requiring extra work to persist the order to a database.

![reordering-notes](https://user-images.githubusercontent.com/29046708/27513005-568a372e-592c-11e7-9d0f-69a659cf31e6.gif)

So is this the expected behavior? Is it configurable?

**Comment by desandro** [comment]
Thanks for reporting this issue. What you're asking for would be similar to Packery v1 drag & packing behavior. See issue #353
