### ISSUE TITLE
Infinite Scroll with packery items became extremely laggy when scrolling fast

### ISSUE THREAD

**Issue by tonystaark** [metafizzy/packery#445]
I have created a website using packery to output the blog posts. I have also applied infinite scrolling plugin here to load items from the next page into the current page, and etc. However, when the webpage was being scrolled downwards at a faster speed, the appearance of the next badge of items became so much laggy. 
Is it a packery or infinite scroll issue?

This is the website I built:  `https://vase.ai/blog/` 

This is the infinite scroll CDN that I use:
    `<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery 
     infinitescroll/2.1.0/jquery.infinitescroll.min.js"></script>`

here was my code for packery and infinite scroll:

    `$(document).ready(function() {
      var grid = $('.grid');

      grid.packery({
        itemSelector: '.grid-blog',
        gutter: 20,
      }) 

      grid.infinitescroll({
        // Pagination element that will be hidden
        navSelector: '.pagination',

        // Next page link
        nextSelector: '.pagination a',

        // Selector of items to retrieve
        itemSelector: '.grid-blog',

        // Loading message
        loadingText: "",
        loadingImage: ""
      },

      // Function called once the elements are retrieved
      function(new_elts) {
        var elts = $(new_elts).css('opacity', 0);

        elts.animate({opacity: 1});
        grid.packery('appended', elts);

        $('.target-resize').textfill({
          maxFontPixels: 36,
          changeLineHeight:false
        })

        grid.packery({
          itemSelector: '.grid-blog',
          gutter: 20,
          
        })
      });    
    });

**Comment by desandro** [comment]
Looks like you're using the old version of Infinite Scroll (v2). I just recently released an all-new version of [Infinite Scroll, v3](https://infinite-scroll.com). It has much better support for Packery layouts, [see `outlayer` option](https://infinite-scroll.com/options.html#outlayer). See also [upgrading from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

I recommend you try upgrading to Infinite Scroll v3 and seeing if this issues persist.

**Comment by tonystaark** [comment]
Hi David,
Thank you so much. The latest plugin works fine on the homepage. However, when I tried to switch between tags, there were issues.
For example, when I clicked on ‘Market Research’ and ‘Branding & Marketing” tabs, there are errors as shown in the snapshot here. 
But if I clicked on ‘Latest Trends’ and ‘Entrepreneurship’ tabs, things are okay. 
So I wonder what could be done. This is my code:

$grid.infiniteScroll({
      // Pagination element that will be hidden
      hideNav: '.pagination',

      // Next page link
      path: '.pagination a',

      // Selector of items to retrieve
      append: '.grid-blog',
      outlayer: pckry,

      scrollThreshold: 200,
      checkLastPage:true
    })

    $grid.on( 'append.infiniteScroll', function( items ) {
      $grid.packery({
        itemSelector: '.grid-blog',
        gutter: 20,
      }) 
     
      $('.target-resize').textfill({
        maxFontPixels: 36,
        changeLineHeight:false
      });

    });

    $grid.on( 'error.infiniteScroll', function( items ) {
      $('.loading').css('display', 'none'),
      $grid.packery({
        itemSelector: '.grid-blog',
        gutter: 20,
      }) 
    })

**Comment by desandro** [comment]
Looks like you're still using `jquery.infinitescroll.min.js` instead of [infinite-scroll.pkgd.min.js](https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.min.js). Sorry I am not able to debug this issue with the previous version currently in use.

**Comment by tonystaark** [comment]
The screenshots attached are what happened when I used the latest version. I can’t allow it to be live so I had to revert back to previous version instead.
