### ISSUE TITLE
Bin packing not working as I expected

### ISSUE THREAD

**Issue by tdsmoore** [metafizzy/packery#446]
Hi,

I had a particular set of grid items (see codepen example) on a dynamic site which I had expected to pack neatly into a 12 tile grid of either 2x6, 3x4, 4x3 however 3x4 produces an odd result.

At first I thought it might be one of the "1 pixel" issues faced by some using responsive layouts but it isn't. Is this a limitation of the bin packing algorithm???

**Test case:** https://codepen.io/anon/pen/xrJyYy

Thanks,

Tom

**Comment by desandro** [comment]
Thanks for reporting this issue

> Is this a limitation of the bin packing algorithm?

I would say this is how Packery's algorithm was designed. From https://github.com/metafizzy/packery/issues/298#issuecomment-173614566

> Packery's packing algorithm is designed to keep elements higher up in the DOM, higher up in the layout. This is intuitive behavior.

Packery will not re-sort the items to more efficiently pack the available area.  If you unsatisfied with the packing algorithm, you may want to try forking Packery and coding your own solution.
