### ISSUE TITLE
Is it possible to programatically move an element? 

### ISSUE THREAD

**Issue by alexiskattan** [metafizzy/packery#449]
Is there a way to programatically move an element from position (0,0) to (20,20) say?  Or when adding a new element, can I specify that it need to be added at location (20, 20)?

**Comment by desandro** [comment]
Yes! [Use the `fit` method](https://packery.metafizzy.co/methods.html#fit). You can specify a position for the element

``` js
 $grid.packery( 'fit', element, 120, 60 );
```
