### ISSUE TITLE
"Re-Packing" after side menu slide open - margin issues

### ISSUE THREAD

**Issue by tophat1986** [metafizzy/packery#450]
Hi.  I'm stuck with how to figure this one out.  Shared my full code here - https://codepen.io/top_hat/pen/OgKbgJ

My design has a side bar style menu on the left, with your packery layout on the right. 

Now opening the sub menu from clicking on the arrow, re-adjusts the right container to fit the new width after side menu opens.  Done through a little jquery I've just learnt!  But how do we tell the Packery code to refresh, or adjust itself?   I'm seeing a strange issue with margins being adjusted to the items themselves?  I'm not experienced enough to know how to figure this one out :(

_(Also, there's no way I could get the "gutter" to work with div heights set in pixels and having lots of different sizes, especially spanning collumns.   This created voids and not perfectly packed.  Because of the fluid nature of the widths being in % which is required.  Unless I went full crazy on developing a fluid % height algo somehow, but no need.  So I've cheated and just added borders you'll note.  If there was a solution here, I would like to know though and maybe others too)._

(p.s. fanstastic work on this library - thank you!)

**Comment by desandro** [comment]
Thanks for providing a reduced test case. I believe the best way to resolve this issue is to set [`percentPosition: true`](https://packery.metafizzy.co/options.html#percentposition). See demo https://codepen.io/desandro/pen/adebb5d2b9270d9c960a77cde2f47dba/

**Comment by tophat1986** [comment]
Thank you for your epic fast response and 2 word solution! :)
