### ISSUE TITLE
Packery demo - Draggabilly with appended items With vanilla JS 

### ISSUE THREAD

**Issue by aasim110** [metafizzy/packery#451]
How can I write Vanilla JS for following demo ?

https://codepen.io/desandro/pen/mjcGq

**Comment by desandro** [comment]
See demo https://codepen.io/desandro/pen/qXOZdB

``` js
// https://packery.metafizzy.co/packery.pkgd.js and 
// https://draggabilly.desandro.com/draggabilly.pkgd.js added as external resource

var grid = document.querySelector('.grid');

var pckry = new Packery( grid, {
  columnWidth: 80,
  rowHeight: 80
});

// bind draggabilly events to item elements
pckry.items.forEach( function( item ) {
  makeItemDraggable( item.element )
});

function makeItemDraggable( itemElem ) {
  // make element draggable with Draggabilly
  var draggie = new Draggabilly( itemElem );
  // bind Draggabilly events to Packery
  pckry.bindDraggabillyEvents( draggie );
}

var addItemsButton = document.querySelector('#add-items');

addItemsButton.addEventListener( 'click', function() {
  var itemElems = [
    getItemElement('w2 h2'),
    getItemElement('w4 h2'),
    getItemElement('w4 h4'),
    getItemElement('w2 h2'),
    getItemElement('w2 h4'),
    getItemElement('w2 h2'),
  ];
  // append to grid via document fragment
  var fragment = document.createDocumentFragment();
  itemElems.forEach( function( itemElem ) {
    fragment.appendChild( itemElem )
  });
  grid.appendChild( fragment );
  // add to packery & make draggable
  pckry.appended( itemElems );
  itemElems.forEach( makeItemDraggable );
});

// get item element
function getItemElement( className ) {
  var itemElem = document.createElement('div');
  itemElem.className = 'item ' + className;
  return itemElem;
}
```

**Comment by aasim110** [comment]
@desandro  Great :+1:  Thanks for the help.

**Comment by krunalsheth3** [comment]
Can we achieve the same thing for packery with jquery ui draggable ?
In the example above it doesnt scroll the webpage if the widget is suppose to go all the at the bottom
How can we do that using vanilla javascript ?

**Comment by desandro** [comment]
@krunalsheth3 If you're using jQuery UI Draggable then I recommend you use the jQuery plugin version of Packery.

**Comment by krunalsheth3** [comment]
Unfortunately I am using packery with draggable.
Can I still achieve the jquery ui drag capability on top of it ?

**Comment by krunalsheth3** [comment]
If yes, then whats the code snippet I should follow.
Thanks

**Comment by desandro** [comment]
Vanilla JS with Draggabilly: https://codepen.io/desandro/pen/qXOZdB

jQuery with jQuery UI Draggable: https://codepen.io/desandro/pen/mjcGq

**Comment by Hulk93** [comment]
Hi all, 
I need to save the default positions of the grid items on a button click.
I'm able to save and reload the grid items. but, after resetting the grid items, if I hit F5 it is taking me back to previous grid positions. 

I want to save default positions on a click. please help.

// I'm not able to save the default grid positions after this line of code.
**$grid.packery('reloadItems');**

thanks in advance.
