### ISSUE TITLE
The elements are not displayed correctly until a page reload

### ISSUE THREAD

**Issue by barbudour** [metafizzy/packery#452]
Good afternoon, faced such problem, when I open the page the elements are mixed with each other, if you refresh the page, everything falls into place. What could be the problem? The link to the page: http://apriori.barbudour.ru/kejsy/

Screenshot before: 
![d0e3d3dfb37d6d8fda127a13bc81b6d0](https://user-images.githubusercontent.com/29177814/28578175-8df13468-7161-11e7-9fbe-5f2b209841c2.png)
Screenshot after: 
![image](https://user-images.githubusercontent.com/29177814/28578120-67e4c85c-7161-11e7-8a0d-2d7e2cdc8a0c.png)

**Comment by desandro** [comment]
Are you using [imagesLoaded](https://packery.metafizzy.co/layout.html#imagesloaded)?
