### ISSUE TITLE
Packery with masonry horizontalOrder

### ISSUE THREAD

**Issue by osa1313** [metafizzy/packery#453]
Hi I wanted to know if there is a way of forcing packery to use horizontalOrder from masonry?
I want to load items from database and display them in the order they are loaded using horizontalOrder.
I can achieve the above, but at the instance I drag&drop a grid-item, packery just starts using its own sorting algorithm, which causes some items to move.

You can see this effect by dragging item 5. https://codepen.io/tom39/pen/GvpQpN

In addition, but not relevant to this problem:
Is there a way of keeping number of grid-items in each column balanced? So that each column contains the same or a very similar number of grid-items.

**Comment by desandro** [comment]
Thank you for reporting this issue.

> is a way of forcing packery to use horizontalOrder from masonry

Sorry no, you can only use Packery or Masonry. You cannot use two layout plugins on the same set of elements. You'll have to pick between one or the other.
