### ISSUE TITLE
reloadItems method ruins the order of getItemElements

### ISSUE THREAD

**Issue by connoro10** [metafizzy/packery#454]
Thank you for your awesome work on Packery! I am using Packery in an Angular 2 project. In the project, there is a button that will create a new draggable div. In order for Packery to detect the new div, reloadItems must be called. Unfortunately after reloadItems is called the order of elements returned by getItemElements reverts back to its original state, which is causing issues. I've provided an example of the issue here: https://codepen.io/connorotte/pen/ayvQrV
Try rearranging a few of the divs and then clicking on the Reload Items button in the top left. You will see the numbers do not correctly represent the order anymore. If you continue to rearrange the divs, chaos ensues. If layout() is called after rearranging and reloading, the layout of the divs is restored to its original state which is undesirable. I've provided a Layout Items button to call layout.

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. The cause of this issue is that Packery does not re-sort the the order of items in the DOM after they are moved around.

You can resolve this issue by adding code to re-sort items in the DOM.

``` js
$grid.on( 'dragItemPositioned', function() {
  orderItems();
  var itemElems = $( $grid.packery('getItemElements') );
  $grid.empty().append( itemElems );
} );
```

See demo https://codepen.io/desandro/pen/MvaxEa

**Comment by connoro10** [comment]
Thanks for the solution! I'm curious to see more of the code, but the codepen link appears to be broken.

**Comment by vnngoc156** [comment]
The link doesn't not work for me as well and even with the full solution code, the issue still remains.
