### ISSUE TITLE
Question: Packery + Flickity

### ISSUE THREAD

**Issue by solcre** [metafizzy/packery#455]
Hi! Do you think this Packery will work inside slides of Flickity or it will have some position/calculation problems?
Thanks for your help!

**Comment by desandro** [comment]
Yes, Packery will work fine within Flickity slides. You'll need to initialize Packery grid first. If you have a **reduced test case** I can take look if you're having trouble.  See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).
