### ISSUE TITLE
New release needed for browsers

### ISSUE THREAD

**Issue by DanielRuf** [metafizzy/packery#456]
Currently the packaged dist files still use EvEmitter 1.0.2 which does not provide this fix.

https://github.com/metafizzy/packery/blob/09118f5a53511432101b73547eec5266090f75cf/dist/packery.pkgd.js#L368

https://github.com/metafizzy/ev-emitter/issues/1

**Comment by desandro** [comment]
Thanks for reporting this issue. This will be resolved in the next release.

**Comment by desandro** [comment]
[v2.1.2 has been released](https://github.com/metafizzy/packery/releases/tag/v2.1.2)

**Comment by DanielRuf** [comment]
Awesome, thanks =)
