### ISSUE TITLE
ItemElements are not showing in order after applying shiftLayout

### ISSUE THREAD

**Issue by rkbansal** [metafizzy/packery#457]
ItemElements are not showing in order using $grid.data('packery').getItemElements() after removing the element and applying shiftLayout. But in UI it is showing it in correct order.
It works fine when i simply uses $grid.packery() instead of $grid.packery('shiftLayout'). I think remove and shiftLayout don't like each other.

Here is the reduced case
https://codepen.io/rkbansal/pen/VzbWgR

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you elaborate on what you mean by "not showing in order." What order do you expect?

**Comment by rkbansal** [comment]
Hey.. nice to see that you are that much active. Okay now let me explain it.
Here "not showing in order" means the order in $grid.data().getItemElements() is not matching with the order of items in the UI. I have updated the reduced case, please go through it. Lets consider an example.
In that on removal of item 1 i want this order - 9,11,2,3,4,5,6,7,8,15,10,12,13,14,16,17,18... which the order showing in the UI after apply shiftLayout but when i am fetching the itemElements using $grid.data('packery').getItemElements() it is coming in the order - 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
Hope this will help you understand what i am trying to say. If you need more explanation let me know because my company is planning to buy it and i don't want that we have suffer from this issue.

**Comment by desandro** [comment]
Sounds like you could be asking for #353
