### ISSUE TITLE
on Click and Draggable cannot both work on mobile device

### ISSUE THREAD

**Issue by robertwong68** [metafizzy/packery#458]
I am using Packery on mobile. Both the $grid.on( 'click', '.grid-item', function( event ){} and the draggable work perfectly ok but cannot work together. If I put draggable $grid.packery( 'bindDraggabillyEvents', draggie ) and on Click together, it will be draggable but cannot click. Any alternative ?
Thanks.

$grid.find('.grid-item').each( function( i, gridItem ) {
  var draggie = new Draggabilly( gridItem );
  // bind drag events to Packery
  $grid.packery( 'bindDraggabillyEvents', draggie );
});
$grid.on( 'click', '.grid-item', function( event ) {
  // change size of item by toggling large class
  $(event.currentTarget).toggleClass('grid-item--large');

**Comment by desandro** [comment]
Thanks for reporting this issue. With Draggabilly, I recommend using its [`staticClick` event](https://draggabilly.desandro.com/#staticclick) so click events do not conflict with drag events.

**Comment by robertwong68** [comment]
Thanks, it is working.

**Comment by ttarrant** [comment]
That solution works if you want to get a click event on the _whole draggable item_ but what if you have a button inside a draggable item? and need the click event to fire on that button only and not the whole thing?
