### ISSUE TITLE
After append an item how to make reference to it and make it draggable ?

### ISSUE THREAD

**Issue by robertwong68** [metafizzy/packery#460]
I have appended the items and is working but how can I reference to these new items to make it draggable ?
Thanks.

$('.append-button').on( 'click', function() {
    // create new item elements
    var $items = getItemElement().add( getItemElement() ).add( getItemElement() );
    // append elements to container
    $grid.append( $items )
      // add and lay out newly appended elements
      .packery( 'appended', $items );

**Comment by yaodingyd** [comment]
Initialize a new `Draggabilly` instance and bind its events to a Packery instance with `bindDraggabillyEvents`.

```javascript
var draggie = new Draggabilly( $items );
  // bind drag events to Packery
  $grid.packery( 'bindDraggabillyEvents', draggie );
```

**Comment by robertwong68** [comment]
I have added accordingly but the newly added item cannot be dragged.


$('.append-button').on( 'click', function() {
     var $items = getItemElement();
        $grid.append( $items )
        $grid.packery( 'appended', $items );
        var draggie = new Draggabilly( $items );
  	$grid.packery( 'bindDraggabillyEvents', draggie );
        $grid.packery('shiftLayout');

**Comment by yaodingyd** [comment]
@robertwong68 I have updated my previous comment for init with jQuery instance.

**Comment by robertwong68** [comment]
Thanks for the reply and I have tried but still cannot drag.
Please see my codepen below.

https://codepen.io/robertwong68/pen/jLYMEJ

**Comment by yaodingyd** [comment]
`var draggie = $items.draggabilly();` You misspell `$item`. Variable name should be `$items`.

**Comment by robertwong68** [comment]
Sorry for that stupid mistake and I have revised.
However, this time drag is enabled but not binding to packery ?

https://codepen.io/robertwong68/pen/jLYMEJ?editors=1010

**Comment by yaodingyd** [comment]
My bad. You have to get the `Draggabilly` instance through `data` for a jQuery instance. like this: `var draggie = $items.draggabilly().data('draggabilly');`

**Comment by robertwong68** [comment]
Thank and it works perfectly.
