### ISSUE TITLE
Horizontal option causes dragging item to increase container width.

### ISSUE THREAD

**Issue by nckrtl** [metafizzy/packery#461]
When I have the horizontal option enabled it keeps increasing the container width upon dragging an item. This results in having a container width of 3000px +. I have set a rowHeight + a width on the container. I also tried to leave out the width on the container but this also doesn't help. When not using the horizontal option it all works fine.

It seems to only occur when I drag an item from the 2nd row to the 1 row. The outer right item of the first row *should* be pushed to the 2nd row. Instead it increases the container width. How can I prevent the container of getting wider and the outer right element of row 1 getting to pushed to the first position of row2?

Got any tips? 

**Test case:** http://codepen.io/desandro/pen/QyrEgX

**Comment by deybyd182** [comment]
The horizontal option is for that purpose, to make Packery grow at sides, if you want that grows vertically, disable that option.

**Comment by desandro** [comment]
@deybyd182 Has the correct answer
