### ISSUE TITLE
Packery layout doesn't work properly with dynamically created objects

### ISSUE THREAD

**Issue by deybyd182** [metafizzy/packery#462]
I need to create and append items elements dynamically, but when I do that, instead create them at HTML code, the items overlap, does get their 'own space' and when I drag them, sometimes, they take 'strange positions'. What I can do?

I tried with imagesLoaded, but that doesn't fix the problem, I tried with Vanilla JS and jQuery also, but nothing works.

Some of the main bugs that I have...
![error_mover](https://user-images.githubusercontent.com/31019120/29320766-e4169864-819d-11e7-9d89-95fe66f950d9.png)
![overlapping1](https://user-images.githubusercontent.com/31019120/29320767-e416f44e-819d-11e7-9668-3950b9515434.png)
![sobrepuesto](https://user-images.githubusercontent.com/31019120/29320765-e4169ef4-819d-11e7-8bcf-6858e852bd3a.png)
![strangepos](https://user-images.githubusercontent.com/31019120/29322473-3a4c5c00-81a3-11e7-961a-e00ba0cc7281.png)

Codepen [here](https://codepen.io/deybyd182/pen/brYEEJ)

**Comment by fran-worley** [comment]
You need to make sure you run packery layout after the DOM elements have loaded. As they are being added dynamically you need to trigger a function to run either after each item has loaded, or after they all have and in the function run `$yourGrid.packery()`.

Images loaded won't help you here as it checks that images have loaded or are broken, not regular dom elements.

Your final example looks like there might be css issues at play. You might want to pull it up with dev tools and see what is blocking packery from using that central space at the top (possible a rogue margin, or conflict positioning).

**Comment by desandro** [comment]
Thanks for reporting this issue.

Looks like you need to [trigger imagesLoaded](https://packery.metafizzy.co/layout.html#imagesloaded) after they have been added to the page. @fran-worley had it right. Your code was triggering imagesLoaded before the images had been added.

See demo https://codepen.io/desandro/pen/712529dbc11862804b65aff3e7994e4f/

**Comment by deybyd182** [comment]
@fran-worley  @desandro Thank you very much to both, but I'm still having the unwanted gap's problem 

![29322473-3a4c5c00-81a3-11e7-961a-e00ba0cc7281](https://user-images.githubusercontent.com/31019120/29474691-67721cca-8422-11e7-889f-2b9efd55fff9.png)

**Comment by fran-worley** [comment]
@deybyd182 see my final comment:
>Your final example looks like there might be css issues at play. You might want to pull it up with dev tools and see what is blocking packery from using that central space at the top (possible a rogue margin, or conflict positioning).

Have you got a reduced code pen of just that example I'd be happy to take a quick look and see if I can spot the problem.

**Comment by deybyd182** [comment]
@fran-worley There is nothing in that spaces, the strange position is the generated by Packery (position: absolute; top: FOOpx; Left: FOOpx)

[Codepen here](https://codepen.io/deybyd182/pen/RZQyKg)

For getting the bug drag the 'Test 4' under 'Test 3' 

![sdfs](https://user-images.githubusercontent.com/31019120/29475517-b15e8a50-8425-11e7-9885-7960ed08a328.png)
like this...

and then drag 'Test 4' to the initial position.

**Comment by deybyd182** [comment]
@desandro look at this... I noticed a very curious thing about my problem... 

if I create 5 elements or more (minimum a row and an element or more), Packery works perfectly, but if I create only 4 elements (just a row), then fails..

Code pen here(https://codepen.io/deybyd182/pen/WEPeee?editors=0010)

I leave two vars, docXML and docXML2, try with each one and you'll see.

**Comment by desandro** [comment]
Sorry, I don't know if I'm able to see a bug.

**Comment by deybyd182** [comment]
in cargarReportes' function try with $generarPlantillaReporte(docXML); and $generarPlantillaReporte(docXML2);
