### ISSUE TITLE
Isotope with Packery, cannot start the program with masonry layout 

### ISSUE THREAD

**Issue by robertwong68** [metafizzy/packery#463]
This program works perfectly except when it started it will be in fitRows layout mode. If I click any grid item, it will be back to masonry layout. How can I start the program in masonry  layout ?

If I change the layoutMode to packery, the program will not work accordingly.

https://codepen.io/robertwong68/pen/rzJydV

**Comment by desandro** [comment]
Thanks for reporting this bug. Looks like you're trying to use both Packery and Isotope on the same elements. These layout libraries will conflict with one another.  Isotope's packery layout mode does not support dragging. See https://github.com/metafizzy/packery/issues/46#issuecomment-18617291

You'll have to pick one of these libraries.

**Comment by robertwong68** [comment]
Actually, Packery and Isotope seems working together very well. The only issue I have is the initial display it used isotope fitRows and afterward it go back perfectly to packery layout.
Anyway, is there a way to switch between Packery and Isotope ? because most of the time, packery is perfect but sometimes I need to sort and filter some of the grid-items.

**Comment by desandro** [comment]
Sorry, Packery and Isotope are separate layout libraries not designed to work on top of one another. Conflicts are inevitable. I recommend you choose between one or the other.
