### ISSUE TITLE
is there a possibility to drag divs within another draggable 

### ISSUE THREAD

**Issue by holzfelix** [metafizzy/packery#464]
Hi together,

is there a possibility to drag divs within another draggable div.

And is there a way to make not the whole div draggable? I thought about an anchor?

thanks

**Comment by desandro** [comment]
> is there a possibility to drag divs within another draggable div.

In theory, yes, You can initializing the inner Packery instance then initialize the outer packery instance. The inner instance would act as an item in the outer instance. That said, it may be a complex thing, both in code and for user experience. I cannot recommend it. Packery works best as designed, with one 'layer' of dragging interactions.

> And is there a way to make not the whole div draggable? I thought about an anchor?

If you're using Draggabilly, use [`handle`](https://draggabilly.desandro.com/#handle) option, see demo on CodePen http://codepen.io/desandro/pen/znAuH
