### ISSUE TITLE
Can't figure out how to set widths on elements when save/restore a resized layout

### ISSUE THREAD

**Issue by jlb0170** [metafizzy/packery#466]
**Test case:** https://codepen.io/desandro/pen/PZrXVv

This codepen doesn't work as is (I can't drag anything) but I did get the basic save and restore working in my app. 

However, I can't figure out how to get the resized state of my blocks to restore. 
here is (roughly) the code i'm using.

https://codepen.io/anon/pen/LjvBxB

If this is the correct approach and you think it isn't working because of a detail bug, I can try to get this reduced test case working as well as my app code is working unreduced. I'm hoping you can look at what I'm setting in initShiftLayout on the items before calling shiftLayout and tell me something obvious I'm doing wrong though.

**Comment by desandro** [comment]
Thanks for the heads up. I fixed the demo https://codepen.io/desandro/pen/PZrXVv

I'm not sure if I understand the issue. The demo should handle window resizing.

**Comment by jlb0170** [comment]
I'm using resizable to allow the user to change the size of the boxes. When I load a saved layout, I'm trying to set the x, y, and width attributes of the item.rect before calling shiftLayout, but it isn't respecting the width attribute at all.

**Comment by desandro** [comment]
This code is not set up for keeping track of item widths. Packery deals with item positions, so there's no 'hooks' for this kind of behavior. You'll have to engineer a separate solution to persist item width across browser sessions.
