### ISSUE TITLE
GetItemElements not reordering correctly when transitionsDuration is 0

### ISSUE THREAD

**Issue by Thodor20** [metafizzy/packery#468]
I've stumbled upon a bug when disabling transition on the grid items, the order of elements kept in the packery object does not update correctly anymore when you use transition durations of 0.

In the test case I added a transition duration of 0 and you will see that the numbers in the blocks update wrong. However once you delete the transition duration it goes back to normal.

**Test case:** https://codepen.io/Thodor12/pen/wrwLVN

Quick fix: If you don't want transitions add a transitionDuration of 1, this will still make the ordering of items correct while you visually see no transition.

**Comment by desandro** [comment]
Thanks for reporting this issue. I'll look into what's going on.
