### ISSUE TITLE
reloadItems() not working with Webpack

### ISSUE THREAD

**Issue by lamka02sk** [metafizzy/packery#472]
I am rewriting my existing project to webpack and got stuck at reloadItems function which is very very important for me. Browser console says: `TypeError: this.element is undefined`, so there is clearly something wrong with the packery scope inside this function. Any help?

Here is my code: 
```javascript
const Packery = require('packery');

let packery = new Packery('.content-settings', {
            itemSelector: '.component-element',
            gutter: 22
});

// .. then I try to reload items and error happens
packery.reloadItems();
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).

**Comment by lamka02sk** [comment]
I made a CodePen demo of this problem, but as CodePen does not support Webpack, error does not occur there: https://codepen.io/anon/pen/XeNGXv
+ I included everything to easy check the code of my project directly

**Comment by desandro** [comment]
Sorry without a reduced test case I cannot debug this issue.
