### ISSUE TITLE
Can not place bigger containers under smaller ones

### ISSUE THREAD

**Issue by dodul** [metafizzy/packery#475]
It seems we can not place bigger containers under smaller ones. We can place smaller ones under the bigger ones or the same sized ones below one another. Please check the attached screenshot. I tried it from:  https://packery.metafizzy.co/draggable.html

![packery](https://user-images.githubusercontent.com/13984819/32008391-56a9111a-b969-11e7-8780-8375974beb3a.png)

Is there a way to do this ? Thanks in advanced!

**Comment by dodul** [comment]
+1

**Comment by desandro** [comment]
This kind of behavior was possible with Packery v1's drag behavior. Add your reaction to #353
