### ISSUE TITLE
How to do Ridiculous (organic size)?

### ISSUE THREAD

**Issue by ariadnaguitian** [metafizzy/packery#476]
I do pixel art and the images need to be in the original size, how I can do a organic template with packery? this feature was named by you on the v1 with "ridiculous" but I dont know how to use! Thanks you very much!!

**Test case:** http://codepen.io/desandro/pen/QyrEgX

**Comment by desandro** [comment]
Thanks for this question. The organic layout, as presented in the [Packery v1 docs](https://packery.metafizzy.co/v1) was done by not setting columnWidth or rowHeight, and just using random item sizes and letting Packery's packing algorithm fit them as best as they can. 

See demo https://codepen.io/desandro/pen/ac5f9adc9561235ad1cf6d19a5135805/
