### ISSUE TITLE
Polymer 2 + init Grid

### ISSUE THREAD

**Issue by kmoreauSilab** [metafizzy/packery#478]
Hello,

I have a little problem with our library on the page loading. I use polymer 2 and bootstrap 3 and i want to include a drag and drop system in my component. I used several examples but no one works when the web page was finish loading.

I have for exemple this screen : 

![image](https://user-images.githubusercontent.com/26548114/32486816-14770d26-c3a8-11e7-851a-26702c54424a.png)

It's append when i load my page and i touch anything. BUT when i open my console (dev tools browser) or i resize my window, the grid will be OK ! ...

![image](https://user-images.githubusercontent.com/26548114/32488884-7213257c-c3ae-11e7-8b07-1b7401d1d875.png)

So when an action will do, the grid will be updated i think. So do you have an idea to solve this little  problem ? 

I think the problem is with the CSS attribute at the init : 
position: absolute; 
left: 0px
top 0px

thank you :)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).

**Comment by kmoreauSilab** [comment]
Hello, thx for you reply but i finally use a dynamic init with a tempo between adds and it work fine :)
