### ISSUE TITLE
isEnabled

### ISSUE THREAD

**Issue by EazyServer** [metafizzy/packery#479]
Thanks for the great package.

I don't have an issue per se but it's more of a suggestion if you prefer!

I needed this package to only layout a bunch of boxes, not really cared about order or re-ordering so I needed to disable the ordering functionality completely! However, I still wanted the boxes to be draggable for drag/drop (using [Draggabilly](https://draggabilly.desandro.com/), again thank you).

It's was not documented/supported so I had to dig in your code until i found `isEnabled` which greatly served the purpose.

<img width="555" alt="screen shot 2017-11-10 at 14 54 11" src="https://user-images.githubusercontent.com/19202935/32663967-b6d96b14-c627-11e7-8133-eaca20ac79cc.png">

it would be great if we could have this option available in the options array and maybe document it as well.

Thanks

**Comment by desandro** [comment]
Thanks for reporting your finding. I'm having trouble understanding how your behavior works. If you could provide a **reduced test case**, people could be better understand. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).
