### ISSUE TITLE
Possible getItem() efficiency concern

### ISSUE THREAD

**Issue by dvstans** [metafizzy/packery#480]
This is not a bug, but while troubleshooting an unrelated problem I noticed the code for the Packery getItem(elem) function compares elements using the == operator. I believe this will compare all fields in the elements, which there are many, but it seems only the "id" fields needs to be compared. I hacked my local packery code to do this, and it seems to work fine.

**Comment by desandro** [comment]
Thanks for reporting this issue. I consider this kind of code a micro-optimization. Checking `==` is easily readable and understandable for other developers. I don't feel making a change here would produce much benefit.

Thanks! but I'll have to pass on this one.
