### ISSUE TITLE
Stamp + originTop: false exhibit unstable behaviour

### ISSUE THREAD

**Issue by asmeikal** [metafizzy/packery#481]
If I add the `originTop: false` option to the [stamp example](https://packery.metafizzy.co/options.html#stamp), the grid becomes unstable. In the test case the grid items overlap the stamped items. I've noticed different behavior on different screen sizes.

Calling `$(".grid").packery()` again usually changes the layout in unpredictable ways.

**Test case:** http://codepen.io/asmeikal/pen/ooExvY

**Comment by desandro** [comment]
Thanks for reporting this issue. Yes, a stamp that uses `top` for its position will not work on a bottom-up grid with `originTop: false`.  However, you can use `bottom` for stamp positions with `originTop: false`. See demo https://codepen.io/desandro/pen/21408b93f55af2e1cba99f3e5026921a/

**Comment by asmeikal** [comment]
Thank you, I understand the problem now and why it's not possible to do what I was trying to do. I'll see if I can find a workaround!
