### ISSUE TITLE
Distinguish between drag and click events

### ISSUE THREAD

**Issue by drinkwater99** [metafizzy/packery#482]
I am using dragging with jQuery UI Draggable.

How can I distinguish between a click or a drag ?
That is, when I click on a grid item I want to show an alert() box but not when dragging a grid item.
Is there some way to do this ?

**Comment by frank-dspeed** [comment]
@drinkwater99 you need to handle that in the click event handler there you need to track mouse up event
if its still down then your dragging simply then track if mouse moves while down and then finaly if all that not happens fire your alert on mouse up

**Comment by desandro** [comment]
Or you can switch to [Draggabilly and use its staticClick event](https://draggabilly.desandro.com/#staticclick).

[See also solutions for jQuery UI draggable from this thread](https://forum.jquery.com/topic/can-the-same-element-have-draggable-and-click-event)

**Comment by drinkwater99** [comment]
In case anyone else falls on to this, here is the solution 

$(".element")
      .draggable()
      .click(function(){
            if ( $(this).is('.ui-draggable-dragging') ) {
                  return;
            }
            // click action here
      });

**Comment by frank-dspeed** [comment]
@drinkwater99 

```js
$(".element")
.draggable()
.click(function(){
  if ( $(this).is('.ui-draggable-dragging') ) {
   return;
  }
// click action here
});
```
