### ISSUE TITLE
Horizontal Layout with Elements in specific columns possible?

### ISSUE THREAD

**Issue by thomasaull** [metafizzy/packery#485]
I'm trying to accomplish a specific layout, something like this: https://packery.metafizzy.co/options.html#horizontal but I want all elements to be in specific columns, e.g. element 1 should be column 1, element 4 should be column 3, while elements can have widths multiple factors of columnWidth. Is this possible at all with packery?

**Comment by desandro** [comment]
Sorry, this is not possible with Packery. [Isotope v1 had this kind of feature](https://isotope.metafizzy.co/v1/custom-layout-modes/category-rows.html), but that's years old now so i can longer recommend it either. I recommend you try to find another solution.
