### ISSUE TITLE
Swap grid items

### ISSUE THREAD

**Issue by drinkwater99** [metafizzy/packery#488]
Is there any way to have it function where it would simply swap items when dragging ?

My grid has items will fixed sizes (width and height) so in theory it should make sense visually since none of the other grid items would need to move.

I have read the docs and github issues and it seems that it's not possible.

Is there some hacky way of achieving this (how ever dirty or even modifying the packery source code)?

**Comment by desandro** [comment]
Sorry, swapping is not possible as items may not have the same size. You may be interested in other library like [Shopify Draggable](https://shopify.github.io/draggable/). Otherwise, add a reaction to  #353 for a similar behavior.
