### ISSUE TITLE
Packery not working with Salesforce Lightning Components

### ISSUE THREAD

**Issue by suresh83kumar** [metafizzy/packery#493]
Hi Desandro,

I work for a large global IT consulting firm, we have a business requirement where we have to enable rich UI in Salesforce and i feel packery is a perfect fit for it.

Packery (auto resize of tiles) works perfectly fine in salesforce lightning components. When i enable [ locker service](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_code.htm) for lightning components then packery fails to auto resize tiles and throws an error. 
![packery](https://user-images.githubusercontent.com/12747966/35945821-13889ac0-0c27-11e8-931e-05d9cc4ad9e7.jpg)

I used click event (tried to use vanilla JS code with Jquery) to resize my tile and getting this error.

 `      elem.addEventListener( 'click', function( event1 ) {`
  `        // filter for grid-item clicks`
   `        var target = event1.target;`
    `      if ( !event1.target.classList.contains('grid-item') ) {`
     `       return;`
      `    }`
       `  target.classList.toggle('grid-item--large');`
        `    grid.layout();`
        `        });`

Currently, Packery doesn't comply with Salesforce locker service. Wanted to check with you to see if packery can be made compatible with Salesforce locker service?

**Lightning Component Reference:** https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/intro_framework.htm
**Salesforce Locker Service Reference:** https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_code.htm

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry, but I don't have any interest in integrating Packery as a Salesforce locker service component. From glancing at their documentation, their requirements may be too stringent for Packery.
