### ISSUE TITLE
Packery arranges differently on Safari vs Chrome

### ISSUE THREAD

**Issue by faisal-ijaz** [metafizzy/packery#495]
Hi,

Is there a known variation of the way packery arranges the grid-items on chrome vs safari?

Chrome:
![chrome](https://user-images.githubusercontent.com/18067537/36762948-ee08e3b8-1bf3-11e8-8aba-cdd781a5d0d6.png)

Safari:
![safari](https://user-images.githubusercontent.com/18067537/36762949-ee20cdca-1bf3-11e8-89d8-52c20191c796.png)

On Chrome it displays the way it is supposed to, but on Safari it displays a little weird. The grid items are set to percentages for width and vh for height and they all add up to 100% in total width and height. Position percentage is set to true as well so not sure what is going on. Any ideas what may be causing this?

I would do codepen, but I am not sure if it will be replicable there, but let me know I can set one up if it helps.

Thank you

**Comment by faisal-ijaz** [comment]
So I further investigated and here are my findings:

- When I zoom out 1 level from the 'actual size' in safari (so 90%~), the grid items seem to fall into place like they are in chrome. Not sure why Safari would do this with same resolution vs Chrome.

- Based on my testing this problem does not occur on grid-items with a fixed height in pixels instead of vh. But doing so, I lose the responsive nature of the page. Since the idea is to have the entire viewport filled with those colored tiles (screenshot above).

- I am trying to achieve a 100% by 100% display of the tile/masonry layout and not show any gaps, overflow or hidden areas that may occur if I use fixed height.

- I further tested with Chrome to determine if the behavior was replicable by resizing of chrome window and seems like the issue is indeed replicable on chrome as well. 
     - I later somewhat resolved this by doing a destroy on init Packery on resize event with a timer. 
     - This resolved the issue, however, would only work 95% of different sizes. 


Instead of doing tons of grid-item height manipulation through media queries to reflect fixed pixel-based height that seems to resolve the problem, is there a better solution to this?

**Comment by faisal-ijaz** [comment]
I did some further testing by using verge.js to get total height of the viewport and then dynamically assigning fixed pixel height to each grid-item 

`
viewportHeight = verge.viewportH() // Get the viewport height in pixels.
    var height1 = (10 / 100) * viewportHeight;
    var height2 = (20 / 100) * viewportHeight;
    var height3 = (30 / 100) * viewportHeight;
    var height4 = (40 / 100) * viewportHeight;
    var height5 = (50 / 100) * viewportHeight;
    var height6 = (60 / 100) * viewportHeight;
    var height7 = (70 / 100) * viewportHeight;


    $('.grid-item').height(height1);
    $('.grid-item--height2').height(height2);
    $('.grid-item--height3').height(height3);
    $('.grid-item--height4').height(height4);
    $('.grid-item--height5').height(height5);
    $('.grid-item--height6').height(height6);
    $('.grid-item--height7').height(height7);
`

I was hoping this would resolve the issue with Packery having different arrangements of items across different browsers because of the height. But even after doing this method and ensuring that all grid-items height wise would add up to the total height of the viewport, safari still seems to have a mind of its own. Additionally, I realized that while testing different viewport sizes on chrome, it sometimes mimics the arrangement of safari. 

Example: on 1280 X 800
![2018-03-01 12 42 54 am](https://user-images.githubusercontent.com/18067537/36828716-861a9b6a-1ce9-11e8-98e9-d6d67e61f5e4.png)


- If I resize the browser window width, the grid-item stay in place and just shrink or expand to fit the viewport.

- if I resize the browser window height, the grid-item mostly stays in place, shrinks and expands until it hits certain viewport dimensions and it just arranges some grid-items out of the view.

- On safari, it seems to be an issue regardless which viewport dimension is available, it doesn't arrange the grid-items properly

**Comment by desandro** [comment]
> Is there a known variation of the way packery arranges the grid-items on chrome vs safari?

Yes. Because of CSS vs JS pixel measurements differences, layouts can be different across browsers due a pixel rounding difference.

**Comment by faisal-ijaz** [comment]
Thank you for the response @desandro. Would you be able to suggest something for what I am trying to achieve? Sorry, I am fairly new to web development and if you could point me in the right direction, that be awesome. 

I came across the safari pixel rounding difference in other posts on here and figured that if I calculate the viewport height and dynamically assign the gird items based on the percentage of total viewport height, it would resolve the issue, but it didn't work out as anticipated. Is there some other method I can try?

**Comment by desandro** [comment]
If pixel perfection across browsers is important to your design, then Packery might not be the solution for you. You could try using explicit `px` values instead of percent values. Sorry, I do not have a good solution here.
