### ISSUE TITLE
Draggable item overlaps another item in Internet Explorer 11

### ISSUE THREAD

**Issue by vlodko** [metafizzy/packery#496]
1. Open https://packery.metafizzy.co/ in IE11.

2. Arrange elements like on image below:

![image](https://user-images.githubusercontent.com/2395824/36927707-a421443e-1e3c-11e8-9983-ece04ff75c90.png)

3. Then drag highlighted rectangle to bottom right.

4. Dragged block covers second rectangle.

5. Expected result: Dragged block covers second rectangle

![image](https://user-images.githubusercontent.com/2395824/36927888-0445005c-1e3e-11e8-847c-9cc60ad1af07.png)

**I was able to reproduce the issue with other block in the same dashboard demo**

Would you be so kind to fix it or give some instructions on how to resolve the issue on my side?
Thanks

**Comment by desandro** [comment]
Thanks for reporting this bug. Looks to be the same as #343. Please subscribe to that issue for any updates. Sorry, I do not have a solution at this time.

**Comment by vlodko** [comment]
@desandro thanks for response.
it's been two years since you opened #343 and last change in the codebase was 8 months ago - what is the priority of this bug in your TODO list?
Can we expect a fix in next 1-2 months at least?
Thanks a lot!

**Comment by desandro** [comment]
I cannot commit to a response time. I apologize for that. Packery has lower usage than other plugins like Flickity and Isotope. These drop-target issues are tricky to pin down.

**Comment by vlodko** [comment]
@desandro got it
We have built a dashboard of our app using it, I guess we should switch some other library :(
