### ISSUE TITLE
problem with originTop false and dragging

### ISSUE THREAD

**Issue by ccowen** [metafizzy/packery#497]
I'm having trouble dragging when originTop is set to false. There are unexpected movements, and you can't always place items were you would like.

Adding originTop false to the dragged class names helps, but placement can be challenging. Also, there is a second where the item moves (usually upwards) then snaps back. 

https://codepen.io/parallelexpressions/pen/JLPGqR

**Comment by desandro** [comment]
I'm sorry to say Packery does support drag & drop with originTop: false or originLeft: false. I do have a separate issue open tracking this: #244
