### ISSUE TITLE
How to rearrange many elements using Javascript?

### ISSUE THREAD

**Issue by sakibanda** [metafizzy/packery#500]
Hi,

I want to rearrange all packery elements using JavaScript.

Like
Send Element - 5 to Postition - 1
Send Element - 10 to Postion - 2

Is there is any built-in methods to do this or is there any other easyway?

I tried many different ways but nothing is working well.

Like use Drag-Drop Simulate but its not working to re-arranging many elements as there are positioned absolute. When elements are re-positioned its not possible to get updated order of elements to target to specific position. 

Like if i sent 
Element 5 To Position 1
Then Send Element 8 - Position 5
Its sending Element 8 To Position 1 as DOM index of 5 is still Element 5 still.

Is there any Packery method to get elements sorted by position in grid?
How to solve this?

**Comment by desandro** [comment]
> Is there any Packery method to get elements sorted by position in grid?

You could use [Isotope with the Packery layout mode.](https://isotope.metafizzy.co/layout-modes/packery.html) Although, you cannot use drag & drop with Isotope

Otherwise, if you want to position items at certain locations, use the [`fit` method](https://packery.metafizzy.co/methods.html#fit)
