### ISSUE TITLE
packery tile is distorted in firefox browser

### ISSUE THREAD

**Issue by gautbava** [metafizzy/packery#502]
**Test case:** http://codepen.io/desandro/pen/QyrEgX

I have coded packery to build complex tile system with showing map and visualizations in rest of the tiles. Its working as expected in Chrome, IE and Safari but first tile having map with different shape not working in firefox. Please let me know if there is fix for it?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).
