### ISSUE TITLE
Update layout on browser height change

### ISSUE THREAD

**Issue by babyPrince** [metafizzy/packery#505]
Hey there,

A quick question about updating the layout.
I'm using 50% height/width for each item, so you end up with a 2x2 "fullscreen" grid. It's working as should when resizing the width of the browser, but I've noticed when I trigger the Bookmarks bar in Chrome, or Search Bar in Windows (they both change the viewport to be shorter in height), the height of each item is updated, but they now overlap. If the browser window is slightly resized horizontally, the layout is adjusted. What would be a way to listen for height change?

**Comment by desandro** [comment]
> I'm using  50% height

Packery does not support percent heights for vertical layouts, by default. Packery resizes the height of container so it can fit the laid-out items. But if items are sized based on the container, then we run into cyclical logic and layout can collapse.

You could try disabling Packery's resize behavior by setting [`resize: false` in your options](https://packery.metafizzy.co/options.html#resize)
