### ISSUE TITLE
Disabling 'swap' on specific item

### ISSUE THREAD

**Issue by JozefJavorsky** [metafizzy/packery#506]
Hello, I'm building a web app (vocalbulary) where I have 4 colums. Each column contains a set of <li> tags. I am using packery for reordering the list. The goal of the app is to find the pairs among columns. It is basically 4 colums with words, a column for each language and you have to reorder the words so that they match the translation ( car - coche - auto). After the pair is found I want the <li> tag to be "frozen" and disable the "swap" with other elements, if that makes sense. If i use .draggable('disable'), it prevents the element from moving, but the element can still be swapped with other elements. I would Like to ask if there is any method for achieving this (dragable elements ignoring the frozen element) thanks

**Comment by desandro** [comment]
>  if there is any method for achieving this (dragable elements ignoring the frozen element)

You can use the [`stamp`](https://packery.metafizzy.co/methods.html#stamp) and `unstamp` methods
