### ISSUE TITLE
Moving elements with css percent width and percentPosition cause some problems

### ISSUE THREAD

**Issue by cassiolana** [metafizzy/packery#507]
https://codepen.io/anon/pen/qyWxmV

I'm facing 3 problems using a 12 columns layout with percentage width and position.
Switching the elements up and down in the last column overlaps the elements and the small ones fail to be positioned in the last column.
And with the elements in the middle sometimes other elements move together when they are not supposed to move.

**Comment by desandro** [comment]
This is the way Packery v2 drag layout behavior is designed. Sounds related to #353. Closing here as a duplicate.
