### ISSUE TITLE
Expand/shrink percentages by 1%

### ISSUE THREAD

**Issue by pliablepixels** [metafizzy/packery#508]
Good day, this is a question, not a bug report.
I use your amazing library to create a montage of video monitors in my angularJS app (security CCTV feeds). 

I use the following packery init settings:

```
 pckry = new Packery('.grid', {
        itemSelector: '.grid-item',
        percentPosition: true,
       //columnWidth: '.grid-sizer',
        gutter: 0,
        initLayout: layouttype,
        shiftPercentResize: true,
        transitionDuration: 0

      });
```

My users want to be able to increase/decrease image sizes by 1% as it offers them maximum flexibility to fill the window width. Looking at all the examples, it looks like they all use CSS classes, each with different widths.  Following that cue, [I've actually created 100 CSS grid-width classes](https://github.com/pliablepixels/zmNinja/blob/master/www/css/style.css#L1054
), each with their own width. Is there a better way or is this what one needs to do?

**Comment by desandro** [comment]
Thanks for asking this question. Packery does not require `columnWidth` to be set. `columnWidth` is useful if you want to rearrange items and align them to columns. That said, you can set item sizes however you want: via 100 CSS classes, or dynamically with JavaScript.

**Comment by pliablepixels** [comment]
thank you!
