### ISSUE TITLE
 1-for-1 swapping when dragging

### ISSUE THREAD

**Issue by pixedd** [metafizzy/packery#509]
Hello !

I'm using Packery with Draggability, I would like to swap items without changing the whole order of my grid. 

For example i've got 9 items with a grid of 3 columns (col-sm-4), if I move the first one with the second one, I expect the second one to take the first one place and not going down (5th place).

Is there a way to achieve that ? or an option ?

Thanks !

**Comment by desandro** [comment]
Packery does not provide this behavior but we may be able to get close by using its older v1 behavior. See #353
