### ISSUE TITLE
Draggability: Disable on hover over specfic element, and allow marking of text

### ISSUE THREAD

**Issue by cod3gen** [metafizzy/packery#511]
Codepen example: https://codepen.io/anon/pen/JaaPGE

In this example, hovering over one element disables draggability over all elements, is it possible do disable draggability on the specfic element instead?

And even though draggability is disable, im not able to mark and/or copy text inside the draggable element - is there a way around this?

**Comment by desandro** [comment]
> And even though draggability is disable, im not able to mark and/or copy text inside the draggable element - is there a way around this?

You can use the back handle technique with Draggabilly. See https://codepen.io/desandro/pen/znAuH

**Comment by cod3gen** [comment]
Yeah, handle was the one i where looking for.. And thats more or less the answer for both questions. Thanks 👍
