### ISSUE TITLE
How to use Packery with contenteditable div?

### ISSUE THREAD

**Issue by mgeth** [metafizzy/packery#524]
Is it possible to use Packery and Draggabilly with content editable div? For some reason I can not get contenteditable div to work with Packery and Draggabilly. 

Test case: https://codepen.io/anon/pen/vwmEvG

**Comment by desandro** [comment]
My recommendation is to use a [back-handle method with Draggabilly](https://codepen.io/desandro/pen/znAuH), so that the text is clickable and editable, but the rest of the item is draggable.

**Comment by mgeth** [comment]
I'll use this, thanks for your help
