### ISSUE TITLE
Bootstrap Collapse, Draggabilly and Packery height issues on expand

### ISSUE THREAD

**Issue by bokac91** [metafizzy/packery#525]
Hello there!

First of all - great library. It's really impressive!
This is my issue: at the moment, I have a grid of items and I am using Draggabilly to move them around, and I am using some of the bootstrap's classes. Items (**col-sm-4 grid-item**) are basically cards with the heading and the body **(panel-heading** and **panel-body**). I tried to implement a collapsible card that, when clicked, would expand its height and reveal its content; however, when I do that, my card just expands above the card that is below it, instead of pushing the below's card down to make room for the collapsible one. 

Is this issue solvable? I assume that I need to implement some sort of jQuery function, but I'm just not sure how. I've seen a similar issue with the hidden paragraph; however, my collapsible div is not literally hidden - it's just of **tab-content** class that is toggleable. Thanks!

**Comment by desandro** [comment]
Yes, you can solve this issue by using [`fit` method](https://packery.metafizzy.co/methods.html#fit). See more in [Animating Item sizes](https://packery.metafizzy.co/extras.html#animating-item-size)

**Comment by bokac91** [comment]
Okay, gotcha. Thanks!
