### ISSUE TITLE
How can I make sure a grid align is always aligned top?

### ISSUE THREAD

**Issue by xjester** [metafizzy/packery#527]
I'm trying to figure out how to always align the items to the top, as in right on the edge to the next element. It fixes itself sometimes, and other times not.

**Test case:** http://dev.oozy.me/el/

![image](https://user-images.githubusercontent.com/42355996/58378045-36854a80-7f5a-11e9-945c-e4e62559f265.png)

It should look like:

![image](https://user-images.githubusercontent.com/42355996/58378047-3f761c00-7f5a-11e9-8c8a-6ca0673cbace.png)

Which does,s sometimes.

jQuery:

```
    function initIsotope() {
      var $grid = $(".file-list").packery({
        itemSelector: "li",
        gutter: 0,
        percentPosition: false
      });

      $grid.imagesLoaded().progress(function() {
        $grid.packery();
      });
    }
```

    $(document).ready(function() {
	  initIsotope();
    });

What am I doing wrong?

**Comment by desandro** [comment]
If you're dynamically adding content, you'll need to trigger `initIsotope` after that content has been added to the page, not just on document.ready.
