### ISSUE TITLE
Responsive Packery with different heights - keep getting white spaces

### ISSUE THREAD

**Issue by kreativstau** [metafizzy/packery#536]
Hello, 

i am trying to create a responsive Packery/Masonry with different-sized images. Do I get it right that Packery needs fixed heights as in this demo: https://codepen.io/desandro/pen/tonpx ? I always get white spaces. Some of my images are wider that others for example two rows wide, others are one row wide. I am also using percentages, not fixed widths: http://dev.kreativstau.de/work

How can I fixe this? Will I need to have to work with fixed ratios? Does Packery need fixed heights and widthes? 

/Edit: I get white spaces in the third row on the right under the red/blue image and under the seventh image on the left. 

Thanks

**Comment by kashifkiduniya** [comment]
I am having same issue of auto height. It is having spaces on bottom.
Did you find any fixed for it?
Please share if you have.

Thanks

**Comment by kreativstau** [comment]
Hello, 

I am sorry, I did not find a solution. 

Best

**Comment by kashifkiduniya** [comment]
I already spend too much time with this plugin 😩

But thanks for you instance response!

**Comment by kreativstau** [comment]
Never mind :) Good luck :)
