### ISSUE TITLE
Is swapping possible with Packery?

### ISSUE THREAD

**Issue by stereokai** [metafizzy/packery#55]
The upgraded [Gridster](https://github.com/dustmoo/gridster.js) fork by Dustmoo, has swapping functionality implemented quite nicely.

By swapping I mean that when dragging items around, you don't reorder then entire grid, but just swap between the item you're dragging and the items you're hovering, leaving the rest of the grid intact.

Is this kind of thing possible with Packery? Has there been any work on this kind of functionality?

If you'd like to see an example, you have to download Dustin's repo and open the sample page. The official website is not updated anymore.

Thanks!

**Comment by desandro** [comment]
[Packery v2 is out :tada: ](http://packery.metafizzy.co/) and has [all new drag behavior](https://twitter.com/desandro/status/694547335720751105). Dragging is way more intuitive. Dragged items will snap into position, reducing gaps. Other items shift up and down, so no more random movement. Plus, Packery adds a [drop placeholder](http://packery.metafizzy.co/draggable.html#drop-placeholder) so you can display where the item is going to land.

Time to close this one up! Thanks for your interest over the years. If you run into any issues with the drag behavior, please open a new issue :grin:

**Comment by stereokai** [comment]
@desandro I saw it on the website yesterday, well done :)

**Comment by timothymarois** [comment]
> The upgraded [Gridster](https://github.com/dustmoo/gridster.js) fork by Dustmoo, has swapping functionality implemented quite nicely.
> 
> By swapping I mean that when dragging items around, you don't reorder then entire grid, but just swap between the item you're dragging and the items you're hovering, leaving the rest of the grid intact.
> 
> Is this kind of thing possible with Packery? Has there been any work on this kind of functionality?
> 
> If you'd like to see an example, you have to download Dustin's repo and open the sample page. The official website is not updated anymore.
> 
> Thanks!

I know this is super old... sorry. 

You've mentioned Gridster has swapping? Where do you see that exactly because I've tested the package and while you can swap up or down, you cant swap two times left or right, it just pushes the other item below. Is there a configuration you used to give you actual swapping?

**Comment by stereokai** [comment]
Sorry mate, it was so long ago...
