### ISSUE TITLE
access gaps array with jQuery init

### ISSUE THREAD

**Issue by netzproductions** [metafizzy/packery#551]
@desandro, you mentioned using pckry.packer.spaces to get access to all gaps rendered. Would you please so kind to tell how to get the spaces array using jQuery init? Thanks in advance, Alex

**Comment by desandro** [comment]
Use [`.data('packery')` to get the Packery instance](https://packery.metafizzy.co/methods.html#jquery-fn-data-packery) `pckry`

``` js
let pckry = $grid.data('packery');
console.log( pckry.packer.spaces )
```
