### ISSUE TITLE
Activation of the packery without changing the positions of the layouts

### ISSUE THREAD

**Issue by RanItzhakiB** [metafizzy/packery#552]
Hello,
I would like to know if there's a possibility for activating the packery without actually changing the positions of the layouts?
I've implemented the packery library in a dashboard page, which has the option of saving the positions of the layout in the DOM and once the DOM is loaded,  the packery changes the saved  positions of a few elements in the DOM.  I want to use the packery's dragging only after the DOM is completely loaded and I know the packery must be active, so I want to know if there's a possibility for what I'm asking.

Thanks.

**Comment by desandro** [comment]
See #337. Closing here.

**Comment by RanItzhakiB** [comment]
Thanks
