### ISSUE TITLE
Fluid grid with gutter?

### ISSUE THREAD

**Issue by oskarrough** [metafizzy/packery#7]
What is the recommended way to implement a fluid grid with a gutter? There can't be any (or at least a minimum for percentage roundings) extra spacing in the grid.

With element sizing for the columns and gutter (plus an extra element) I got it working like this: http://jsfiddle.net/oskarrough/7WB2c/

Although not adviced in the docs I'm using an element in the grid as sizing element for the column width. Seems to work? How could it be improved?

**Comment by netwire88** [comment]
Hi @desandro , just to clarify, if I have fluid width, and I'd like 2 columns per row and 2% gutter, I'd use 100% - 2% / 2 = 49% for each column width?

**Comment by desandro** [comment]
@netwire88 Yes! See http://codepen.io/desandro/pen/myOwNY

**Comment by notflip** [comment]
Any idea how to get this working with 3 columns? I can't seem to get it right with the above formula.
Thank you

**Comment by desandro** [comment]
I've got to update the docs. Until then, take a look at the gutter demo for Packery with Isotope: http://codepen.io/desandro/pen/fGrKe

Using Packery, the options would look like:

``` js
$('.grid').packery({
  itemSelector: '.grid-item',
  percentPosition: true,
  gutter: '.gutter-sizer'
});
```
