### ISSUE TITLE
Memorize and store the positions per user, or in config file?

### ISSUE THREAD

**Issue by pepperstreet** [metafizzy/packery#70]
Hello, amazing project and script!
I recently came across GRIDSTER.js and a resulting WP plugin, that utilize the script as a visual layout editor.

SO, i had two use-cases and ideas for Packery:

1.) store positions per user/session.
How to store the positions for the visiter. In Browser session and cookie? Maybe with reset button. Is there any jQuery plugin, that might handle this functionality...

2.) store positions for a layout editor like WP Gridster 
How to collect and store the position information. Which file format is most useful? JSON, XML etc. 

Any thoughts and comments are much appreciated.
Thanks for listening.

**Comment by desandro** [comment]
Packery v2 has new drag behavior, which requires a new technique to save & restore drag position. Closing this issue here, picking it up in #337
