### ISSUE TITLE
.destroy() does not unbind draggable events

### ISSUE THREAD

**Issue by desandro** [metafizzy/packery#72]
From Chris G, via email

> The best part about Packery it is that it works with Draggability, but if pckry.destroy() is called, it works but then it does nothing to all the Draggability events, so they all stay in place, and I just can't figure out how to unbind them from draggie instance and/or the packery instance after pckry.bindDraggabilityEvents(draggie). There is no "unbindDraggabilityEvents" method :) (or :( as the case may be).
> 
> So while packery stops on .destroy(), the drag/touch events are still all active and triggered.

**Comment by Jivings** [comment]
Opened a pull request allowing you to unbind `.draggabilly` events in the same manner they are attached. For instance before `destroy()` I do:

     draggies.forEach(function (draggie) {
          $el.packery('unbindDraggabillyEvents', draggie);
     });

Where `draggies` is an array of Draggabilly instances and `$el` is my Packery element.

**Comment by UziTech** [comment]
same thing occurs with 'bindUIDraggableEvents'
