### ISSUE TITLE
Center objects like in Isotope

### ISSUE THREAD

**Issue by steffimueller** [metafizzy/packery#91]
Is there a way to center objects like in JQuery Isotope? I want to center objects where I see this example: http://codepen.io/desandro/pen/nfkth

But, this does not solve the problem when you have only 1 or two items and want to center them. I see that the container is centered but the elements inside aren't is there a way to adopt this fix from Isotope?

**Comment by digelim** [comment]
@desandro, your solution works, but the elements are now trembling while dragging them. Could you check this please? Thks
