### ISSUE TITLE
Cannot read Packery.Rect since v1.1.1 

### ISSUE THREAD

**Issue by raphaelokon** [metafizzy/packery#96]
Hej,

I recently updated my development code with bower and now Packery is throwing errors:

Uncaught TypeError: Cannot read property 'Rect' of undefined

**Comment by thedamon** [comment]
Having same issue with 1.4.1.. what dependency could it be?

**Comment by thedamon** [comment]
Nm.. looked in the dependencies at the top.. added this to my bower.json overrides to get things working with wiredep:

    "packery": {
      "main": [
        "js/rect.js",
        "js/packer.js",
        "js/item.js",
        "js/packery.js"
      ]
    },

Not sure about item.js.. it seems to work if it's not there since I have (a different :?) item.js through outlayer

**Comment by dagobertrenouf** [comment]
@thedamon thanks this helped me big time !

**Comment by lloydud** [comment]
Tried thedamons suggestion but didnt work for me but instead adding this to overrides in bower.json did:

    "packery": {
      "main": [
        "./dist/packery.pkgd.min.js"
      ]
    }
